"""Module for Buffer Tank Sensors."""

from homeassistant.components.sensor import EntityCategory, SensorDeviceClass

from .const import ModbusDataType, ModbusSensorEntityDescription

SENSOR_TYPES = [
    ModbusSensorEntityDescription(
        name="Buffer Tank Temperature 1",
        key="buffer_tank_temperature_1",
        register=8710,
        data_type=ModbusDataType.INT16,
        native_unit_of_measurement="°C",
        device_class=SensorDeviceClass.TEMPERATURE,
        scale=0.1,
        status_sensor="buffer_tank_temperature_1_status",
    ),
    ModbusSensorEntityDescription(
        name="Buffer Tank Temperature 1 status",
        key="buffer_tank_temperature_1_status",
        register=8711,
        data_type=ModbusDataType.INT16,
        device_class=SensorDeviceClass.ENUM,
        entity_category=EntityCategory.DIAGNOSTIC,
        options={0: "Faulty", 1: "Missing", 2: "OK"},
        is_status_sensor=True,
    ),
    ModbusSensorEntityDescription(
        name="Buffer Tank Temperature 2",
        key="buffer_tank_temperature_2",
        register=8744,
        data_type=ModbusDataType.INT16,
        native_unit_of_measurement="°C",
        device_class=SensorDeviceClass.TEMPERATURE,
        scale=0.1,
        status_sensor="buffer_tank_temperature_2_status",
    ),
    ModbusSensorEntityDescription(
        name="Buffer Tank Temperature 2 status",
        key="buffer_tank_temperature_2_status",
        register=8745,
        data_type=ModbusDataType.INT16,
        device_class=SensorDeviceClass.ENUM,
        entity_category=EntityCategory.DIAGNOSTIC,
        options={0: "Faulty", 1: "Missing", 2: "OK"},
        is_status_sensor=True,
    ),
    ModbusSensorEntityDescription(
        name="Buffer Tank Temperature 3",
        key="buffer_tank_temperature_3",
        register=8778,
        data_type=ModbusDataType.INT16,
        native_unit_of_measurement="°C",
        device_class=SensorDeviceClass.TEMPERATURE,
        scale=0.1,
        status_sensor="buffer_tank_temperature_3_status",
    ),
    ModbusSensorEntityDescription(
        name="Buffer Tank Temperature 3 status",
        key="buffer_tank_temperature_3_status",
        register=8779,
        data_type=ModbusDataType.INT16,
        device_class=SensorDeviceClass.ENUM,
        entity_category=EntityCategory.DIAGNOSTIC,
        options={0: "Faulty", 1: "Missing", 2: "OK"},
        is_status_sensor=True,
    ),
    ModbusSensorEntityDescription(
        name="Buffer Tank Temperature 4",
        key="buffer_tank_temperature_4",
        register=8812,
        data_type=ModbusDataType.INT16,
        native_unit_of_measurement="°C",
        device_class=SensorDeviceClass.TEMPERATURE,
        scale=0.1,
        status_sensor="buffer_tank_temperature_4_status",
    ),
    ModbusSensorEntityDescription(
        name="Buffer Tank Temperature 4 status",
        key="buffer_tank_temperature_4_status",
        register=8813,
        data_type=ModbusDataType.INT16,
        device_class=SensorDeviceClass.ENUM,
        entity_category=EntityCategory.DIAGNOSTIC,
        options={0: "Faulty", 1: "Missing", 2: "OK"},
        is_status_sensor=True,
    ),
    ModbusSensorEntityDescription(
        name="Buffer Tank Temperature 5",
        key="buffer_tank_temperature_5",
        register=8846,
        data_type=ModbusDataType.INT16,
        native_unit_of_measurement="°C",
        device_class=SensorDeviceClass.TEMPERATURE,
        scale=0.1,
        status_sensor="buffer_tank_temperature_5_status",
    ),
    ModbusSensorEntityDescription(
        name="Buffer Tank Temperature 5 status",
        key="buffer_tank_temperature_5_status",
        register=8847,
        data_type=ModbusDataType.INT16,
        device_class=SensorDeviceClass.ENUM,
        entity_category=EntityCategory.DIAGNOSTIC,
        options={0: "Faulty", 1: "Missing", 2: "OK"},
        is_status_sensor=True,
    ),
]

SELECT_TYPES = []
