"""Constants for the growatt_rs232 integration testing."""

from zlib import crc32

from growattRS232 import (
    ATTR_DERATING,
    ATTR_DERATING_MODE,
    ATTR_FAULT,
    ATTR_FAULT_CODE,
    ATTR_FIRMWARE,
    ATTR_FREQUENCY,
    ATTR_INPUT_1_AMPERAGE,
    ATTR_INPUT_1_ENERGY_TODAY,
    ATTR_INPUT_1_ENERGY_TOTAL,
    ATTR_INPUT_1_POWER,
    ATTR_INPUT_1_VOLTAGE,
    ATTR_INPUT_2_AMPERAGE,
    ATTR_INPUT_2_ENERGY_TODAY,
    ATTR_INPUT_2_ENERGY_TOTAL,
    ATTR_INPUT_2_POWER,
    ATTR_INPUT_2_VOLTAGE,
    ATTR_INPUT_ENERGY_TOTAL,
    ATTR_INPUT_POWER,
    ATTR_IPM_TEMPERATURE,
    ATTR_MODEL_NUMBER,
    ATTR_N_BUS_VOLTAGE,
    ATTR_OPERATION_HOURS,
    ATTR_OUTPUT_1_AMPERAGE,
    ATTR_OUTPUT_1_POWER,
    ATTR_OUTPUT_1_VOLTAGE,
    ATTR_OUTPUT_2_AMPERAGE,
    ATTR_OUTPUT_2_POWER,
    ATTR_OUTPUT_2_VOLTAGE,
    ATTR_OUTPUT_3_AMPERAGE,
    ATTR_OUTPUT_3_POWER,
    ATTR_OUTPUT_3_VOLTAGE,
    ATTR_OUTPUT_ENERGY_TODAY,
    ATTR_OUTPUT_ENERGY_TOTAL,
    ATTR_OUTPUT_POWER,
    ATTR_OUTPUT_REACTIVE_ENERGY_TODAY,
    ATTR_OUTPUT_REACTIVE_ENERGY_TOTAL,
    ATTR_OUTPUT_REACTIVE_POWER,
    ATTR_P_BUS_VOLTAGE,
    ATTR_SERIAL_NUMBER,
    ATTR_STATUS,
    ATTR_STATUS_CODE,
    ATTR_TEMPERATURE,
    ATTR_WARNING,
    ATTR_WARNING_CODE,
    ATTR_WARNING_VALUE,
    DERATINGMODES,
    FAULTCODES,
    STATUSCODES,
    WARNINGCODES,
)
from growattRS232.const import DEFAULT_ADDRESS, DEFAULT_PORT

from homeassistant.config_entries import SOURCE_USER
from homeassistant.const import CONF_ADDRESS, CONF_PORT


def s2f(input_string):
    """CRC32 hash a string to a float."""
    return float(crc32(input_string.encode("utf-8")) & 0xFFFFFFFF) / 2 ** 32


VALUE_SERIAL_NUMBER = ATTR_SERIAL_NUMBER

VALUES = {}
VALUES[ATTR_SERIAL_NUMBER] = ATTR_SERIAL_NUMBER
VALUES[ATTR_MODEL_NUMBER] = ATTR_MODEL_NUMBER
VALUES[ATTR_FIRMWARE] = ATTR_FIRMWARE
VALUES[ATTR_STATUS] = 0
VALUES[ATTR_STATUS_CODE] = STATUSCODES[0]
VALUES[ATTR_INPUT_POWER] = s2f(ATTR_INPUT_POWER)
VALUES[ATTR_INPUT_ENERGY_TOTAL] = s2f(ATTR_INPUT_ENERGY_TOTAL)
VALUES[ATTR_INPUT_1_VOLTAGE] = s2f(ATTR_INPUT_1_VOLTAGE)
VALUES[ATTR_INPUT_1_AMPERAGE] = s2f(ATTR_INPUT_1_AMPERAGE)
VALUES[ATTR_INPUT_1_POWER] = s2f(ATTR_INPUT_1_POWER)
VALUES[ATTR_INPUT_1_ENERGY_TODAY] = s2f(ATTR_INPUT_1_ENERGY_TODAY)
VALUES[ATTR_INPUT_1_ENERGY_TOTAL] = s2f(ATTR_INPUT_1_ENERGY_TOTAL)
VALUES[ATTR_INPUT_2_VOLTAGE] = s2f(ATTR_INPUT_2_VOLTAGE)
VALUES[ATTR_INPUT_2_AMPERAGE] = s2f(ATTR_INPUT_2_AMPERAGE)
VALUES[ATTR_INPUT_2_POWER] = s2f(ATTR_INPUT_2_POWER)
VALUES[ATTR_INPUT_2_ENERGY_TODAY] = s2f(ATTR_INPUT_2_ENERGY_TODAY)
VALUES[ATTR_INPUT_2_ENERGY_TOTAL] = s2f(ATTR_INPUT_2_ENERGY_TOTAL)
VALUES[ATTR_OUTPUT_POWER] = s2f(ATTR_OUTPUT_POWER)
VALUES[ATTR_OUTPUT_ENERGY_TODAY] = s2f(ATTR_OUTPUT_ENERGY_TODAY)
VALUES[ATTR_OUTPUT_ENERGY_TOTAL] = s2f(ATTR_OUTPUT_ENERGY_TOTAL)
VALUES[ATTR_OUTPUT_REACTIVE_POWER] = s2f(ATTR_OUTPUT_REACTIVE_POWER)
VALUES[ATTR_OUTPUT_REACTIVE_ENERGY_TODAY] = s2f(ATTR_OUTPUT_REACTIVE_ENERGY_TODAY)
VALUES[ATTR_OUTPUT_REACTIVE_ENERGY_TOTAL] = s2f(ATTR_OUTPUT_REACTIVE_ENERGY_TOTAL)
VALUES[ATTR_OUTPUT_1_VOLTAGE] = s2f(ATTR_OUTPUT_1_VOLTAGE)
VALUES[ATTR_OUTPUT_1_AMPERAGE] = s2f(ATTR_OUTPUT_1_AMPERAGE)
VALUES[ATTR_OUTPUT_1_POWER] = s2f(ATTR_OUTPUT_1_POWER)
VALUES[ATTR_OUTPUT_2_VOLTAGE] = s2f(ATTR_OUTPUT_2_VOLTAGE)
VALUES[ATTR_OUTPUT_2_AMPERAGE] = s2f(ATTR_OUTPUT_2_AMPERAGE)
VALUES[ATTR_OUTPUT_2_POWER] = s2f(ATTR_OUTPUT_2_POWER)
VALUES[ATTR_OUTPUT_3_VOLTAGE] = s2f(ATTR_OUTPUT_3_VOLTAGE)
VALUES[ATTR_OUTPUT_3_AMPERAGE] = s2f(ATTR_OUTPUT_3_AMPERAGE)
VALUES[ATTR_OUTPUT_3_POWER] = s2f(ATTR_OUTPUT_3_POWER)
VALUES[ATTR_OPERATION_HOURS] = s2f(ATTR_OPERATION_HOURS)
VALUES[ATTR_FREQUENCY] = s2f(ATTR_FREQUENCY)
VALUES[ATTR_TEMPERATURE] = s2f(ATTR_TEMPERATURE)
VALUES[ATTR_IPM_TEMPERATURE] = s2f(ATTR_IPM_TEMPERATURE)
VALUES[ATTR_P_BUS_VOLTAGE] = s2f(ATTR_P_BUS_VOLTAGE)
VALUES[ATTR_N_BUS_VOLTAGE] = s2f(ATTR_N_BUS_VOLTAGE)
VALUES[ATTR_DERATING_MODE] = 0
VALUES[ATTR_DERATING] = DERATINGMODES[VALUES[ATTR_DERATING_MODE]]
VALUES[ATTR_FAULT_CODE] = 0
VALUES[ATTR_FAULT] = FAULTCODES[VALUES[ATTR_FAULT_CODE]]
VALUES[ATTR_WARNING_CODE] = 0x0000
VALUES[ATTR_WARNING_VALUE] = s2f(ATTR_WARNING_VALUE)
VALUES[ATTR_WARNING] = WARNINGCODES[VALUES[ATTR_WARNING_CODE]]

DATA_NORMAL = {}
DATA_NORMAL[ATTR_SERIAL_NUMBER] = VALUES[ATTR_SERIAL_NUMBER]
DATA_NORMAL[ATTR_MODEL_NUMBER] = VALUES[ATTR_MODEL_NUMBER]
DATA_NORMAL[ATTR_FIRMWARE] = VALUES[ATTR_FIRMWARE]
DATA_NORMAL[ATTR_STATUS] = VALUES[ATTR_STATUS]
DATA_NORMAL[ATTR_STATUS_CODE] = VALUES[ATTR_STATUS_CODE]
DATA_NORMAL[ATTR_INPUT_POWER] = VALUES[ATTR_INPUT_POWER]
DATA_NORMAL[ATTR_INPUT_ENERGY_TOTAL] = VALUES[ATTR_INPUT_ENERGY_TOTAL]
DATA_NORMAL[ATTR_INPUT_1_VOLTAGE] = VALUES[ATTR_INPUT_1_VOLTAGE]
DATA_NORMAL[ATTR_INPUT_1_AMPERAGE] = VALUES[ATTR_INPUT_1_AMPERAGE]
DATA_NORMAL[ATTR_INPUT_1_POWER] = VALUES[ATTR_INPUT_1_POWER]
DATA_NORMAL[ATTR_INPUT_1_ENERGY_TODAY] = VALUES[ATTR_INPUT_1_ENERGY_TODAY]
DATA_NORMAL[ATTR_INPUT_1_ENERGY_TOTAL] = VALUES[ATTR_INPUT_1_ENERGY_TOTAL]
DATA_NORMAL[ATTR_INPUT_2_VOLTAGE] = VALUES[ATTR_INPUT_2_VOLTAGE]
DATA_NORMAL[ATTR_INPUT_2_AMPERAGE] = VALUES[ATTR_INPUT_2_AMPERAGE]
DATA_NORMAL[ATTR_INPUT_2_POWER] = VALUES[ATTR_INPUT_2_POWER]
DATA_NORMAL[ATTR_INPUT_2_ENERGY_TODAY] = VALUES[ATTR_INPUT_2_ENERGY_TODAY]
DATA_NORMAL[ATTR_INPUT_2_ENERGY_TOTAL] = VALUES[ATTR_INPUT_2_ENERGY_TOTAL]
DATA_NORMAL[ATTR_OUTPUT_POWER] = VALUES[ATTR_OUTPUT_POWER]
DATA_NORMAL[ATTR_OUTPUT_ENERGY_TODAY] = VALUES[ATTR_OUTPUT_ENERGY_TODAY]
DATA_NORMAL[ATTR_OUTPUT_ENERGY_TOTAL] = VALUES[ATTR_OUTPUT_ENERGY_TOTAL]
DATA_NORMAL[ATTR_OUTPUT_REACTIVE_POWER] = VALUES[ATTR_OUTPUT_REACTIVE_POWER]
DATA_NORMAL[ATTR_OUTPUT_REACTIVE_ENERGY_TODAY] = VALUES[
    ATTR_OUTPUT_REACTIVE_ENERGY_TODAY
]
DATA_NORMAL[ATTR_OUTPUT_REACTIVE_ENERGY_TOTAL] = VALUES[
    ATTR_OUTPUT_REACTIVE_ENERGY_TOTAL
]
DATA_NORMAL[ATTR_OUTPUT_1_VOLTAGE] = VALUES[ATTR_OUTPUT_1_VOLTAGE]
DATA_NORMAL[ATTR_OUTPUT_1_AMPERAGE] = VALUES[ATTR_OUTPUT_1_AMPERAGE]
DATA_NORMAL[ATTR_OUTPUT_1_POWER] = VALUES[ATTR_OUTPUT_1_POWER]
DATA_NORMAL[ATTR_OUTPUT_2_VOLTAGE] = VALUES[ATTR_OUTPUT_2_VOLTAGE]
DATA_NORMAL[ATTR_OUTPUT_2_AMPERAGE] = VALUES[ATTR_OUTPUT_2_AMPERAGE]
DATA_NORMAL[ATTR_OUTPUT_2_POWER] = VALUES[ATTR_OUTPUT_2_POWER]
DATA_NORMAL[ATTR_OUTPUT_3_VOLTAGE] = VALUES[ATTR_OUTPUT_3_VOLTAGE]
DATA_NORMAL[ATTR_OUTPUT_3_AMPERAGE] = VALUES[ATTR_OUTPUT_3_AMPERAGE]
DATA_NORMAL[ATTR_OUTPUT_3_POWER] = VALUES[ATTR_OUTPUT_3_POWER]
DATA_NORMAL[ATTR_OPERATION_HOURS] = VALUES[ATTR_OPERATION_HOURS]
DATA_NORMAL[ATTR_FREQUENCY] = VALUES[ATTR_FREQUENCY]
DATA_NORMAL[ATTR_TEMPERATURE] = VALUES[ATTR_TEMPERATURE]
DATA_NORMAL[ATTR_IPM_TEMPERATURE] = VALUES[ATTR_IPM_TEMPERATURE]
DATA_NORMAL[ATTR_P_BUS_VOLTAGE] = VALUES[ATTR_P_BUS_VOLTAGE]
DATA_NORMAL[ATTR_N_BUS_VOLTAGE] = VALUES[ATTR_N_BUS_VOLTAGE]
DATA_NORMAL[ATTR_DERATING_MODE] = VALUES[ATTR_DERATING_MODE]
DATA_NORMAL[ATTR_DERATING] = VALUES[ATTR_DERATING]
DATA_NORMAL[ATTR_FAULT_CODE] = VALUES[ATTR_FAULT_CODE]
DATA_NORMAL[ATTR_FAULT] = VALUES[ATTR_FAULT]
DATA_NORMAL[ATTR_WARNING_CODE] = VALUES[ATTR_WARNING_CODE]
DATA_NORMAL[ATTR_WARNING_VALUE] = VALUES[ATTR_WARNING_VALUE]
DATA_NORMAL[ATTR_WARNING] = VALUES[ATTR_WARNING]

SENSOR_INPUT_POWER = f"sensor.{ATTR_SERIAL_NUMBER}_{ATTR_INPUT_POWER}"

CONFIG = {CONF_PORT: DEFAULT_PORT, CONF_ADDRESS: DEFAULT_ADDRESS}

CONTEXT_USER = {"source": SOURCE_USER}

TITLE = f"Growatt {ATTR_SERIAL_NUMBER}"

UNIQUE_ID = ATTR_SERIAL_NUMBER

PATCH = "growattRS232.GrowattRS232.async_update"
