config_entry:
  versions:
    - version:
        major: 1
        minor: 1
      data:
        fields:
          include_only_feed_id:
            required: true
            selector:
              text: {}
      options:
        fields:
          include_only_feed_id:
            required: false
            selector:
              text: {}
  subentries: {}
