config_entry:
  versions:
    - version:
        major: 1
        minor: 3
      data:
        fields: {}
      options:
        fields:
          process:
            required: false
            selector:
              text: {}
  subentries: {}
