"""Constants for the Channels component."""
DOMAIN = "channels"
SERVER_URL = "server_url"
SERVICE_SEEK_FORWARD = "seek_forward"
SERVICE_SEEK_BACKWARD = "seek_backward"
SERVICE_SEEK_BY = "seek_by"
SERVICE_CHANNEL_UP = "channel_up"
SERVICE_CHANNEL_DOWN = "channel_down"
SERVICE_PREVIOUS_CHANNEL = "previous_channel"
SERVICE_TOGGLE_CC = "toggle_cc"
SERVICE_TOGGLE_RECORD = "toggle_record"
SERVICE_NAVIGATE = "navigate"
