config_entry:
  versions:
    - version:
        major: 2
        minor: 1
      data:
        fields:
          auth_implementation:
            required: true
            selector:
              text: {}
          token:
            required: true
            selector:
              object: {}
      options:
        fields: {}
  subentries: {}
