"""Constants for Neato integration."""

NEATO_DOMAIN = "neato"

CONF_VENDOR = "vendor"
NEATO_CONFIG = "neato_config"
NEATO_LOGIN = "neato_login"
NEATO_MAP_DATA = "neato_map_data"
NEATO_PERSISTENT_MAPS = "neato_persistent_maps"
NEATO_ROBOTS = "neato_robots"

SCAN_INTERVAL_MINUTES = 1

MODE = {1: "Eco", 2: "Turbo"}

STR_REPLACE_BATTERY = "Replace battery"
STR_CHECK_NEATO_APP = "Check Neato app"
STR_CLEAR_MY_PATH = "Clear my path"
STR_VACUUM_IS_STUCK = "Vacuum is stuck"

ACTION = {
    0: "Invalid",
    1: "House Cleaning",
    2: "Spot Cleaning",
    3: "Manual Cleaning",
    4: "Docking",
    5: "User Menu Active",
    6: "Suspended Cleaning",
    7: "Updating",
    8: "Copying logs",
    9: "Recovering Location",
    10: "IEC test",
    11: "Map cleaning",
    12: "Exploring map (creating a persistent map)",
    13: "Acquiring Persistent Map IDs",
    14: "Creating & Uploading Map",
    15: "Suspended Exploration",
}

ERRORS = {
    "ui_error_battery_battundervoltlithiumsafety": STR_REPLACE_BATTERY,
    "ui_error_battery_critical": STR_REPLACE_BATTERY,
    "ui_error_battery_invalidsensor": STR_REPLACE_BATTERY,
    "ui_error_battery_lithiumadapterfailure": STR_REPLACE_BATTERY,
    "ui_error_battery_mismatch": STR_REPLACE_BATTERY,
    "ui_error_battery_nothermistor": STR_REPLACE_BATTERY,
    "ui_error_battery_overtemp": STR_REPLACE_BATTERY,
    "ui_error_battery_overvolt": STR_REPLACE_BATTERY,
    "ui_error_battery_undercurrent": STR_REPLACE_BATTERY,
    "ui_error_battery_undertemp": STR_REPLACE_BATTERY,
    "ui_error_battery_undervolt": STR_REPLACE_BATTERY,
    "ui_error_battery_unplugged": STR_REPLACE_BATTERY,
    "ui_error_brush_stuck": "Brush stuck",
    "ui_error_brush_overloaded": "Brush overloaded",
    "ui_error_bumper_stuck": "Bumper stuck",
    "ui_error_check_battery_switch": "Check battery",
    "ui_error_corrupt_scb": "Call customer service corrupt board",
    "ui_error_deck_debris": "Deck debris",
    "ui_error_dflt_app": STR_CHECK_NEATO_APP,
    "ui_error_disconnect_chrg_cable": "Disconnected charge cable",
    "ui_error_disconnect_usb_cable": "Disconnected USB cable",
    "ui_error_dust_bin_missing": "Dust bin missing",
    "ui_error_dust_bin_full": "Dust bin full",
    "ui_error_dust_bin_emptied": "Dust bin emptied",
    "ui_error_hardware_failure": "Hardware failure",
    "ui_error_ldrop_stuck": STR_CLEAR_MY_PATH,
    "ui_error_lds_jammed": STR_CLEAR_MY_PATH,
    "ui_error_lds_bad_packets": STR_CHECK_NEATO_APP,
    "ui_error_lds_disconnected": STR_CHECK_NEATO_APP,
    "ui_error_lds_missed_packets": STR_CHECK_NEATO_APP,
    "ui_error_lwheel_stuck": STR_CLEAR_MY_PATH,
    "ui_error_navigation_backdrop_frontbump": STR_CLEAR_MY_PATH,
    "ui_error_navigation_backdrop_leftbump": STR_CLEAR_MY_PATH,
    "ui_error_navigation_backdrop_wheelextended": STR_CLEAR_MY_PATH,
    "ui_error_navigation_noprogress": STR_CLEAR_MY_PATH,
    "ui_error_navigation_origin_unclean": STR_CLEAR_MY_PATH,
    "ui_error_navigation_pathproblems": "Cannot return to base",
    "ui_error_navigation_pinkycommsfail": STR_CLEAR_MY_PATH,
    "ui_error_navigation_falling": STR_CLEAR_MY_PATH,
    "ui_error_navigation_noexitstogo": STR_CLEAR_MY_PATH,
    "ui_error_navigation_nomotioncommands": STR_CLEAR_MY_PATH,
    "ui_error_navigation_rightdrop_leftbump": STR_CLEAR_MY_PATH,
    "ui_error_navigation_undockingfailed": STR_CLEAR_MY_PATH,
    "ui_error_picked_up": "Picked up",
    "ui_error_qa_fail": STR_CHECK_NEATO_APP,
    "ui_error_rdrop_stuck": STR_CLEAR_MY_PATH,
    "ui_error_reconnect_failed": "Reconnect failed",
    "ui_error_rwheel_stuck": STR_CLEAR_MY_PATH,
    "ui_error_stuck": "Stuck!",
    "ui_error_unable_to_return_to_base": "Unable to return to base",
    "ui_error_unable_to_see": "Clean vacuum sensors",
    "ui_error_vacuum_slip": STR_CLEAR_MY_PATH,
    "ui_error_vacuum_stuck": STR_CLEAR_MY_PATH,
    "ui_error_warning": "Error check app",
    "batt_base_connect_fail": "Battery failed to connect to base",
    "batt_base_no_power": "Battery base has no power",
    "batt_low": "Battery low",
    "batt_on_base": "Battery on base",
    "clean_tilt_on_start": "Clean the tilt on start",
    "dustbin_full": "Dust bin full",
    "dustbin_missing": "Dust bin missing",
    "gen_picked_up": "Picked up",
    "hw_fail": "Hardware failure",
    "hw_tof_sensor_sensor": "Hardware sensor disconnected",
    "lds_bad_packets": "Bad packets",
    "lds_deck_debris": "Debris on deck",
    "lds_disconnected": "Disconnected",
    "lds_jammed": "Jammed",
    "lds_missed_packets": "Missed packets",
    "maint_brush_stuck": "Brush stuck",
    "maint_brush_overload": "Brush overloaded",
    "maint_bumper_stuck": "Bumper stuck",
    "maint_customer_support_qa": "Contact customer support",
    "maint_vacuum_stuck": STR_VACUUM_IS_STUCK,
    "maint_vacuum_slip": STR_VACUUM_IS_STUCK,
    "maint_left_drop_stuck": STR_VACUUM_IS_STUCK,
    "maint_left_wheel_stuck": STR_VACUUM_IS_STUCK,
    "maint_right_drop_stuck": STR_VACUUM_IS_STUCK,
    "maint_right_wheel_stuck": STR_VACUUM_IS_STUCK,
    "not_on_charge_base": "Not on the charge base",
    "nav_robot_falling": STR_CLEAR_MY_PATH,
    "nav_no_path": STR_CLEAR_MY_PATH,
    "nav_path_problem": STR_CLEAR_MY_PATH,
    "nav_backdrop_frontbump": STR_CLEAR_MY_PATH,
    "nav_backdrop_leftbump": STR_CLEAR_MY_PATH,
    "nav_backdrop_wheelextended": STR_CLEAR_MY_PATH,
    "nav_floorplan_zone_path_blocked": STR_CLEAR_MY_PATH,
    "nav_mag_sensor": STR_CLEAR_MY_PATH,
    "nav_no_exit": STR_CLEAR_MY_PATH,
    "nav_no_movement": STR_CLEAR_MY_PATH,
    "nav_rightdrop_leftbump": STR_CLEAR_MY_PATH,
    "nav_undocking_failed": STR_CLEAR_MY_PATH,
}

ALERTS = {
    "ui_alert_dust_bin_full": "Please empty dust bin",
    "ui_alert_recovering_location": "Returning to start",
    "ui_alert_battery_chargebasecommerr": "Battery error",
    "ui_alert_busy_charging": "Busy charging",
    "ui_alert_charging_base": "Base charging",
    "ui_alert_charging_power": "Charging power",
    "ui_alert_connect_chrg_cable": "Connect charge cable",
    "ui_alert_info_thank_you": "Thank you",
    "ui_alert_invalid": "Invalid check app",
    "ui_alert_old_error": "Old error",
    "ui_alert_swupdate_fail": "Update failed",
    "dustbin_full": "Please empty dust bin",
    "maint_brush_change": "Change the brush",
    "maint_filter_change": "Change the filter",
    "clean_completed_to_start": "Cleaning completed",
    "nav_floorplan_not_created": "No floorplan found",
    "nav_floorplan_load_fail": "Failed to load floorplan",
    "nav_floorplan_localization_fail": "Failed to load floorplan",
    "clean_incomplete_to_start": "Cleaning incomplete",
    "log_upload_failed": "Logs failed to upload",
}
