"""Test the daikin_onecta config flow."""

from ipaddress import ip_address
from unittest.mock import patch
from urllib.parse import parse_qs, urlparse

import pytest

from homeassistant import config_entries
from homeassistant.components.application_credentials import (
    ClientCredential,
    async_import_client_credential,
)
from homeassistant.components.daikin_onecta.const import (
    CONF_HOMEKIT_FAN_MODE_ALIASES,
    DOMAIN,
    OAUTH2_AUTHORIZE,
    OAUTH2_TOKEN,
)
from homeassistant.config_entries import SOURCE_ZEROCONF
from homeassistant.core import HomeAssistant
from homeassistant.helpers import config_entry_oauth2_flow
from homeassistant.helpers.service_info.zeroconf import ZeroconfServiceInfo
from homeassistant.setup import async_setup_component

from .conftest import FAKE_ACCESS_TOKEN

from tests.common import MockConfigEntry
from tests.test_util.aiohttp import AiohttpClientMocker
from tests.typing import ClientSessionGenerator

TEST_CLIENT_ID = "test-client-id"
TEST_CLIENT_SECRET = "test-client-secret"
HTTP_OK = 200


def oauth_state(result: dict[str, str]) -> str:
    """Return the state generated by the public OAuth flow response."""
    return parse_qs(urlparse(result["url"]).query)["state"][0]


@pytest.fixture(autouse=True)
async def setup_credentials(hass: HomeAssistant) -> None:
    """Fixture to setup credentials."""
    assert await async_setup_component(hass, "application_credentials", {})
    await async_import_client_credential(
        hass,
        DOMAIN,
        ClientCredential(TEST_CLIENT_ID, TEST_CLIENT_SECRET),
        DOMAIN,
    )


@pytest.mark.usefixtures("current_request_with_host")
async def test_full_flow(
    hass: HomeAssistant,
    hass_client_no_auth: ClientSessionGenerator,
    aioclient_mock: AiohttpClientMocker,
    setup_credentials,
) -> None:
    """Check full flow."""
    assert await async_setup_component(hass, "daikin_onecta", {})

    await async_import_client_credential(
        hass, DOMAIN, ClientCredential(TEST_CLIENT_ID, TEST_CLIENT_SECRET)
    )

    result = await hass.config_entries.flow.async_init(
        "daikin_onecta", context={"source": config_entries.SOURCE_USER}
    )
    state = oauth_state(result)

    assert result["url"] == (
        f"{OAUTH2_AUTHORIZE}?response_type=code&client_id={TEST_CLIENT_ID}"
        "&redirect_uri=https://example.com/auth/external/callback"
        f"&state={state}"
        f"&scope=openid+onecta:basic.integration+offline_access"
    )

    client = await hass_client_no_auth()
    resp = await client.get(f"/auth/external/callback?code=abcd&state={state}")
    assert resp.status == HTTP_OK
    assert resp.headers["content-type"] == "text/html; charset=utf-8"

    aioclient_mock.post(
        OAUTH2_TOKEN,
        json={
            "refresh_token": "mock-refresh-token",
            "access_token": FAKE_ACCESS_TOKEN,
            "type": "Bearer",
            "expires_in": 60,
        },
    )

    with patch(
        "homeassistant.components.daikin_onecta.async_setup_entry", return_value=True
    ) as mock_setup:
        await hass.config_entries.flow.async_configure(result["flow_id"])

    assert len(hass.config_entries.async_entries(DOMAIN)) == 1
    assert len(mock_setup.mock_calls) == 1


async def test_options_flow_homekit_fan_mode_aliases_default(
    hass: HomeAssistant,
) -> None:
    """Test HomeKit fan mode aliases option defaults to disabled."""
    config_entry = MockConfigEntry(domain=DOMAIN, data={})
    config_entry.add_to_hass(hass)

    result = await hass.config_entries.options.async_init(config_entry.entry_id)
    assert result["type"] == "form"

    result = await hass.config_entries.options.async_configure(
        result["flow_id"],
        {
            "high_scan_interval": 10,
            "low_scan_interval": 30,
            "high_scan_start": "07:00:00",
            "low_scan_start": "22:00:00",
            "scan_ignore": 30,
            CONF_HOMEKIT_FAN_MODE_ALIASES: False,
        },
    )

    assert result["type"] == "create_entry"
    assert result["data"][CONF_HOMEKIT_FAN_MODE_ALIASES] is False


async def test_options_flow_rejects_high_interval_above_low_interval(
    hass: HomeAssistant,
) -> None:
    """Test the high-frequency interval may not exceed the low-frequency interval."""
    config_entry = MockConfigEntry(domain=DOMAIN, data={})
    config_entry.add_to_hass(hass)

    result = await hass.config_entries.options.async_init(config_entry.entry_id)
    result = await hass.config_entries.options.async_configure(
        result["flow_id"],
        {
            "high_scan_interval": 30,
            "low_scan_interval": 10,
            "high_scan_start": "07:00:00",
            "low_scan_start": "22:00:00",
            "scan_ignore": 30,
            CONF_HOMEKIT_FAN_MODE_ALIASES: False,
        },
    )

    assert result["type"] == "form"
    assert result["errors"] == {"base": "high_scan_interval_greater_than_low"}


ZEROCONF_DISCOVERY = ZeroconfServiceInfo(
    ip_address=ip_address("10.0.0.131"),
    ip_addresses=[ip_address("10.0.0.131")],
    hostname="altherma.local.",
    name="altherma.local._tcp.local.",
    port=4321,
    type="_daikin._tcp.local.",
    properties={
        "miconID": "17003904",
        "devID": "[0]",
        "sernum": "172300018",
        "disvers": "1.0.0",
        "fwvers": "436CC152000",
        "areaInfo": "/MNCSEBase/mgo-123456789",
    },
)


@pytest.mark.usefixtures("current_request_with_host")
async def test_zeroconf_flow_uses_oauth_discovery(
    hass: HomeAssistant,
    hass_client_no_auth: ClientSessionGenerator,
    aioclient_mock: AiohttpClientMocker,
    setup_credentials,
) -> None:
    """Test zeroconf flow uses the OAuth discovery confirmation step."""
    assert await async_setup_component(hass, "daikin_onecta", {})

    await async_import_client_credential(
        hass, DOMAIN, ClientCredential(TEST_CLIENT_ID, TEST_CLIENT_SECRET)
    )

    result = await hass.config_entries.flow.async_init(
        DOMAIN,
        context={"source": SOURCE_ZEROCONF},
        data=ZEROCONF_DISCOVERY,
    )
    assert result["type"] == "form"
    assert result["step_id"] == "oauth_discovery"

    result = await hass.config_entries.flow.async_configure(result["flow_id"], {})
    state = oauth_state(result)

    assert result["url"] == (
        f"{OAUTH2_AUTHORIZE}?response_type=code&client_id={TEST_CLIENT_ID}"
        "&redirect_uri=https://example.com/auth/external/callback"
        f"&state={state}"
        f"&scope=openid+onecta:basic.integration+offline_access"
    )

    client = await hass_client_no_auth()
    resp = await client.get(f"/auth/external/callback?code=abcd&state={state}")
    assert resp.status == HTTP_OK
    assert resp.headers["content-type"] == "text/html; charset=utf-8"

    aioclient_mock.post(
        OAUTH2_TOKEN,
        json={
            "refresh_token": "mock-refresh-token",
            "access_token": FAKE_ACCESS_TOKEN,
            "type": "Bearer",
            "expires_in": 60,
        },
    )

    await hass.async_block_till_done()
    assert result["type"] == "external"
    assert result["url"].startswith(OAUTH2_AUTHORIZE)

    with patch(
        "homeassistant.components.daikin_onecta.async_setup_entry", return_value=True
    ) as mock_setup:
        await hass.config_entries.flow.async_configure(
            result["flow_id"],
            {},
        )

    await hass.async_block_till_done()
    assert len(hass.config_entries.async_entries(DOMAIN)) == 1
    assert len(mock_setup.mock_calls) == 1


async def test_invalid_oauth_token(
    hass: HomeAssistant,
) -> None:
    """Abort when the OAuth access token is not a valid JWT."""
    flow = config_entries.HANDLERS[DOMAIN]()
    flow.hass = hass

    result = await flow.async_oauth_create_entry({"token": {"access_token": "invalid"}})

    assert result["type"] == "abort"
    assert result["reason"] == "invalid_token"


async def test_reauth_confirm_form(
    hass: HomeAssistant,
    config_entry: MockConfigEntry,
) -> None:
    """Show the reauthentication confirmation form."""
    config_entry.add_to_hass(hass)

    result = await hass.config_entries.flow.async_init(
        DOMAIN,
        context={
            "source": config_entries.SOURCE_REAUTH,
            "entry_id": config_entry.entry_id,
        },
        data=config_entry.data,
    )

    assert result["type"] == "form"
    assert result["step_id"] == "reauth_confirm"


async def test_zeroconf_already_configured(
    hass: HomeAssistant,
    config_entry: MockConfigEntry,
) -> None:
    """Ignore zeroconf discovery when the integration is already configured."""
    config_entry.add_to_hass(hass)

    result = await hass.config_entries.flow.async_init(
        DOMAIN,
        context={"source": SOURCE_ZEROCONF},
        data=ZEROCONF_DISCOVERY,
    )

    assert result["type"] == "abort"
    assert result["reason"] == "already_configured"


async def test_reauth_oauth_create_entry(
    hass: HomeAssistant,
    config_entry: MockConfigEntry,
) -> None:
    """Update the existing entry after successful reauthentication."""
    hass.config_entries.async_update_entry(config_entry, unique_id="1234567890")
    flow = config_entries.HANDLERS[DOMAIN]()
    flow.hass = hass
    flow.context = {
        "source": config_entries.SOURCE_REAUTH,
        "entry_id": config_entry.entry_id,
    }
    data = {
        "auth_implementation": "cloud",
        "token": {
            "access_token": FAKE_ACCESS_TOKEN,
            "refresh_token": "new-refresh-token",
        },
    }

    with patch.object(hass.config_entries, "async_reload") as reload_entry:
        result = await flow.async_oauth_create_entry(data)

    assert result["type"] == "abort"
    assert result["reason"] == "reauth_successful"
    assert config_entry.data == data
    reload_entry.assert_called_once_with(config_entry.entry_id)


@pytest.mark.usefixtures("current_request_with_host")
async def test_reauth_oauth_create_entry_rejects_wrong_account(
    hass: HomeAssistant,
    hass_client_no_auth: ClientSessionGenerator,
    aioclient_mock: AiohttpClientMocker,
    config_entry: MockConfigEntry,
) -> None:
    """Reject reauthentication with an OAuth token for another account."""
    hass.config_entries.async_update_entry(config_entry, unique_id="1234567890")
    result = await config_entry.start_reauth_flow(hass)
    assert result["type"] == "form"
    assert result["step_id"] == "reauth_confirm"

    result = await hass.config_entries.flow.async_configure(result["flow_id"], {})
    state = oauth_state(result)
    client = await hass_client_no_auth()
    resp = await client.get(f"/auth/external/callback?code=abcd&state={state}")
    assert resp.status == HTTP_OK

    aioclient_mock.post(
        OAUTH2_TOKEN,
        json={
            "refresh_token": "wrong-account-refresh-token",
            "access_token": config_entry_oauth2_flow._encode_jwt(
                hass, {"sub": "another-account"}
            ),
            "type": "Bearer",
            "expires_in": 60,
        },
    )

    result = await hass.config_entries.flow.async_configure(result["flow_id"])

    assert result["type"] == "abort"
    assert result["reason"] == "wrong_account"


@pytest.mark.usefixtures("current_request_with_host")
async def test_oauth_create_entry_rejects_duplicate_account(
    hass: HomeAssistant,
    hass_client_no_auth: ClientSessionGenerator,
    aioclient_mock: AiohttpClientMocker,
    config_entry: MockConfigEntry,
) -> None:
    """Reject setup when the OAuth account is already configured."""
    hass.config_entries.async_update_entry(config_entry, unique_id="1234567890")
    result = await hass.config_entries.flow.async_init(
        DOMAIN, context={"source": config_entries.SOURCE_USER}
    )
    state = oauth_state(result)
    client = await hass_client_no_auth()
    resp = await client.get(f"/auth/external/callback?code=abcd&state={state}")
    assert resp.status == HTTP_OK

    aioclient_mock.post(
        OAUTH2_TOKEN,
        json={
            "refresh_token": "duplicate-account-refresh-token",
            "access_token": FAKE_ACCESS_TOKEN,
            "type": "Bearer",
            "expires_in": 60,
        },
    )

    result = await hass.config_entries.flow.async_configure(result["flow_id"])

    assert result["type"] == "abort"
    assert result["reason"] == "already_configured"


async def test_reauth_confirm_continue(
    hass: HomeAssistant,
) -> None:
    """Continue reauthentication through the user OAuth step."""
    flow = config_entries.HANDLERS[DOMAIN]()
    flow.hass = hass

    with patch.object(
        flow, "async_step_user", return_value={"type": "external"}
    ) as step_user:
        result = await flow.async_step_reauth_confirm({})

    assert result == {"type": "external"}
    step_user.assert_awaited_once()
