# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: nest/trait/product/doorbell.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'nest/trait/product/doorbell.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import duration_pb2 as google_dot_protobuf_dot_duration__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n!nest/trait/product/doorbell.proto\x12\x1bnest.trait.product.doorbell\x1a\x1egoogle/protobuf/duration.proto\"\xa5\x02\n DoorbellIndoorChimeSettingsTrait\x12Z\n\tchimeType\x18\x01 \x01(\x0e\x32G.nest.trait.product.doorbell.DoorbellIndoorChimeSettingsTrait.ChimeType\x12\x30\n\rchimeDuration\x18\x02 \x01(\x0b\x32\x19.google.protobuf.Duration\x12\x14\n\x0c\x63himeEnabled\x18\x03 \x01(\x08\"]\n\tChimeType\x12\x1a\n\x16\x43HIME_TYPE_UNSPECIFIED\x10\x00\x12\x19\n\x15\x43HIME_TYPE_MECHANICAL\x10\x01\x12\x19\n\x15\x43HIME_TYPE_ELECTRONIC\x10\x02\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'nest.trait.product.doorbell_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_DOORBELLINDOORCHIMESETTINGSTRAIT']._serialized_start=99
  _globals['_DOORBELLINDOORCHIMESETTINGSTRAIT']._serialized_end=392
  _globals['_DOORBELLINDOORCHIMESETTINGSTRAIT_CHIMETYPE']._serialized_start=299
  _globals['_DOORBELLINDOORCHIMESETTINGSTRAIT_CHIMETYPE']._serialized_end=392
# @@protoc_insertion_point(module_scope)
