charge:
  fields:
    target:
      required: true
      selector:
        device:
          integration: indevolt
    target_soc:
      required: true
      selector:
        number:
          min: 0
          max: 100
          step: 1
          unit_of_measurement: "%"
    power:
      required: true
      selector:
        number:
          min: 1
          max: 2400
          step: 1
          unit_of_measurement: "W"

discharge:
  fields:
    target:
      required: true
      selector:
        device:
          integration: indevolt
    target_soc:
      required: true
      selector:
        number:
          min: 0
          max: 100
          step: 1
          unit_of_measurement: "%"
    power:
      required: true
      selector:
        number:
          min: 1
          max: 2400
          step: 1
          unit_of_measurement: "W"

stop:
  fields:
    target:
      required: true
      selector:
        device:
          integration: indevolt

change_energy_mode:
  fields:
    target:
      required: true
      selector:
        device:
          integration: indevolt
    energy_mode:
      required: true
      selector:
        select:
          translation_key: energy_mode
          options:
            - self_consumed_prioritized
            - real_time_control
            - charge_discharge_schedule
