"""Constants for the swiss_public_transport integration."""

DOMAIN = "swiss_public_transport"

CONF_DESTINATION = "to"
CONF_START = "from"
CONF_LIMIT = "limit"
CONF_PAGE = "page"
CONF_DATE = "date"
CONF_TIME = "time"
CONF_OFFSET = "offset"
CONF_IS_ARRIVAL = "is_arrival"
CONF_TRANSPORTATIONS = "transportations"
CONF_DIRECT = "direct"
CONF_SLEEPER = "sleeper"
CONF_COUCHETTE = "couchette"
CONF_BIKE = "bike"
CONF_ACCESSIBILITY = "accessibility"
CONF_VIA = "via"

DEFAULT_NAME = "Next Destination"
DEFAULT_LIMIT = 3
MIN_LIMIT = 1
MAX_LIMIT = 16
DEFAULT_PAGE = 0
MIN_PAGE = 0
MAX_PAGE = 3
DEFAULT_IS_ARRIVAL = False
MAX_VIA = 5

SELECTOR_TRANSPORTATION_TRAIN = "train"
SELECTOR_TRANSPORTATION_TRAM = "tram"
SELECTOR_TRANSPORTATION_SHIP = "ship"
SELECTOR_TRANSPORTATION_BUS = "bus"
SELECTOR_TRANSPORTATION_CABLEWAY = "cableway"
SELECTOR_TRANSPORTATION_TYPES = [
    SELECTOR_TRANSPORTATION_TRAIN,
    SELECTOR_TRANSPORTATION_TRAM,
    SELECTOR_TRANSPORTATION_SHIP,
    SELECTOR_TRANSPORTATION_BUS,
    SELECTOR_TRANSPORTATION_CABLEWAY,
]

SELECTOR_ACCESSIBILITY_INDEPENDANT_BOARDING = "independent_boarding"
SELECTOR_ACCESSIBILITY_ASSISTED_BOARDING = "assisted_boarding"
SELECTOR_ACCESSIBILITY_ADVANCED_NOTICE = "advanced_notice"
SELECTOR_ACCESSIBILITY_TYPES = [
    SELECTOR_ACCESSIBILITY_INDEPENDANT_BOARDING,
    SELECTOR_ACCESSIBILITY_ASSISTED_BOARDING,
    SELECTOR_ACCESSIBILITY_ADVANCED_NOTICE,
]
