FROM homeassistant/home-assistant:latest

## Setup Home Assistant
RUN pip3 install --no-cache-dir -i https://test.pypi.org/simple/ mythtvservicesapi
RUN pip3 install --no-cache-dir --upgrade git+https://github.com/rajlaud/pyCEC.git@tcp-fixes
COPY *.whl /tmp/
RUN pip3 install --force-reinstall --no-deps /tmp/*.whl
WORKDIR /config
