FROM python:3.9

# Ensure RUN fails if any command fails
SHELL ["/bin/bash", "-euxo", "pipefail", "-c"]

# Install apt-get dependencies
RUN export DEBIAN_FRONTEND=noninteractive; \
    apt-get update; \
    apt-get install -y --no-install-recommends \
        # Additional library needed by some tests and accordingly by VScode Tests Discovery \
        bluez \
        libudev-dev \
        libavformat-dev \
        libavcodec-dev \
        libavdevice-dev \
        libavutil-dev \
        libswscale-dev \
        libswresample-dev \
        libavfilter-dev \
        libpcap-dev \
        libturbojpeg0 \
        libyaml-dev \
        libxml2 \
        git \
        cmake \
        # Needed by the stream component \
        ffmpeg; \
    rm -rf /var/lib/apt/lists/*

# Disable pip version check as we pin its version in requirements.txt
ENV PIP_DISABLE_PIP_VERSION_CHECK=1

# Setup hass-release
WORKDIR /usr/src/hass-release
RUN git clone --depth 1 https://github.com/home-assistant/hass-release . \
    && pip3 install -e .

# Install Python dependencies from requirements
WORKDIR /usr/src/homeassistant
COPY requirements.txt .
COPY homeassistant/package_constraints.txt homeassistant/package_constraints.txt
RUN pip3 install -r requirements.txt --use-deprecated=legacy-resolver
COPY requirements_test.txt requirements_test_pre_commit.txt ./
RUN pip3 install -r requirements_test.txt --use-deprecated=legacy-resolver
RUN rm -rf requirements.txt requirements_test.txt requirements_test_pre_commit.txt homeassistant/
