config_entry:
  versions:
    - version:
        major: 1
        minor: 1
      data:
        fields:
          host:
            required: true
            selector:
              text: {}
          port:
            required: true
            selector:
              number:
                mode: box
                min: 1
                max: 65535
            default: 9330
      options:
        fields: {}
  subentries: {}
