config_entry:
  versions:
    - version:
        major: 1
        minor: 2
      data:
        fields:
          model_family:
            required: true
            selector:
              text: {}
      options:
        fields: {}
  subentries: {}
