add_bonus_time:
  fields:
    bonus_time:
      required: true
      example: 30
      selector:
        number:
          min: -1
          max: 1440
          unit_of_measurement: minutes
          mode: box
    device_id:
      required: true
      example: 1234567890abcdef1234567890abcdef
      selector:
        device:
          integration: nintendo_parental_controls
update_pin_code:
  fields:
    pin:
      required: true
      example: "1234"
      selector:
        text:
          type: password
    device_id:
      required: true
      example: 1234567890abcdef1234567890abcdef
      selector:
        device:
          integration: nintendo_parental_controls
player_usage_report:
  fields:
    device_id:
      required: true
      example: 1234567890abcdef1234567890abcdef
      selector:
        device:
          integration: nintendo_parental_controls
    entity_id:
      required: true
      example: sensor.example_player_used_screen_time
      selector:
        entity:
          integration: nintendo_parental_controls
          domain: sensor
device_usage_report:
  fields:
    device_id:
      required: true
      example: 1234567890abcdef1234567890abcdef
      selector:
        device:
          integration: nintendo_parental_controls
update_daily_restrictions:
  fields:
    device_id:
      required: true
      example: 1234567890abcdef1234567890abcdef
      selector:
        device:
          integration: nintendo_parental_controls
    day_of_week:
      required: true
      example: "monday"
      selector:
        select:
          translation_key: day_of_week
          options:
            - "monday"
            - "tuesday"
            - "wednesday"
            - "thursday"
            - "friday"
            - "saturday"
            - "sunday"
    bedtime_start:
      example: "07:00:00"
      selector:
        time:
    bedtime_end:
      example: "20:00:00"
      selector:
        time:
    max_play_time:
      example: 120
      selector:
        number:
          min: 0
          max: 360
          unit_of_measurement: minutes
          mode: box
