config_entry:
  versions:
    - version:
        major: 1
        minor: 1
      data:
        fields:
          password:
            required: false
            selector:
              text: {}
          token:
            required: false
            selector:
              text: {}
          url:
            required: false
            selector:
              text: {}
          username:
            required: false
            selector:
              text: {}
          verify_ssl:
            required: false
            selector:
              text: {}
      options:
        fields: {}
  subentries:
    topic:
      versions:
        - version:
            major: 1
            minor: 1
          data:
            fields:
              filter_message:
                required: true
                selector:
                  text: {}
              filter_priority:
                required: true
                selector:
                  text: {}
              filter_tags:
                required: true
                selector:
                  text: {}
              filter_title:
                required: true
                selector:
                  text: {}
              topic:
                required: true
                selector:
                  text: {}
          options:
            fields: {}
