create_snapshot:
  target:
    entity:
      integration: proxmoxve
      domain:
        - binary_sensor
        - button
        - sensor
  fields:
    vm_name:
      selector:
        text:
    snapshot_name:
      selector:
        text:
    description:
      selector:
        text:
    version_entity:
      selector:
        entity:
          domain: sensor
    include_ram:
      default: false
      selector:
        boolean:
