config_entry:
  versions:
    - version:
        major: 1
        minor: 1
      data:
        fields:
          system_id:
            required: true
            selector:
              number:
                mode: box
      options:
        fields: {}
  subentries: {}
