# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from homeassistant.components.guarddionisis.util import sensor_pb2 as homeassistant_dot_components_dot_guarddionisis_dot_util_dot_sensor__pb2


class SensorServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetSensorData = channel.unary_unary(
                '/sensor.SensorService/GetSensorData',
                request_serializer=homeassistant_dot_components_dot_guarddionisis_dot_util_dot_sensor__pb2.Void.SerializeToString,
                response_deserializer=homeassistant_dot_components_dot_guarddionisis_dot_util_dot_sensor__pb2.SensorData.FromString,
                )
        self.SetSensorData = channel.unary_unary(
                '/sensor.SensorService/SetSensorData',
                request_serializer=homeassistant_dot_components_dot_guarddionisis_dot_util_dot_sensor__pb2.SensorData.SerializeToString,
                response_deserializer=homeassistant_dot_components_dot_guarddionisis_dot_util_dot_sensor__pb2.Void.FromString,
                )


class SensorServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetSensorData(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetSensorData(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SensorServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetSensorData': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSensorData,
                    request_deserializer=homeassistant_dot_components_dot_guarddionisis_dot_util_dot_sensor__pb2.Void.FromString,
                    response_serializer=homeassistant_dot_components_dot_guarddionisis_dot_util_dot_sensor__pb2.SensorData.SerializeToString,
            ),
            'SetSensorData': grpc.unary_unary_rpc_method_handler(
                    servicer.SetSensorData,
                    request_deserializer=homeassistant_dot_components_dot_guarddionisis_dot_util_dot_sensor__pb2.SensorData.FromString,
                    response_serializer=homeassistant_dot_components_dot_guarddionisis_dot_util_dot_sensor__pb2.Void.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'sensor.SensorService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class SensorService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetSensorData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/sensor.SensorService/GetSensorData',
            homeassistant_dot_components_dot_guarddionisis_dot_util_dot_sensor__pb2.Void.SerializeToString,
            homeassistant_dot_components_dot_guarddionisis_dot_util_dot_sensor__pb2.SensorData.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SetSensorData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/sensor.SensorService/SetSensorData',
            homeassistant_dot_components_dot_guarddionisis_dot_util_dot_sensor__pb2.SensorData.SerializeToString,
            homeassistant_dot_components_dot_guarddionisis_dot_util_dot_sensor__pb2.Void.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
