reconnect_client:
  fields:
    device_id:
      required: true
      selector:
        device:
          integration: unifi

remove_clients:

set_wan_failover_order:
  fields:
    device_id:
      required: true
      selector:
        device:
          multiple: true
          filter:
            - integration: unifi
              model: UniFi WAN
