"""The Qnap constants."""

DEFAULT_NAME = "QNAP"
DEFAULT_PORT = 8080
DEFAULT_TIMEOUT = 5
DEFAULT_SSL = False
DEFAULT_VERIFY_SSL = True

DOMAIN = "qnap"
NOTIFICATION_ID = "qnap_notification"
NOTIFICATION_TITLE = "QNAP Sensor Setup"
VOLUME_NAME = "volume"
