# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: weave/trait/description.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'weave/trait/description.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import wrappers_pb2 as google_dot_protobuf_dot_wrappers__pb2
from ...weave import common_pb2 as weave_dot_common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1dweave/trait/description.proto\x12\x17weave.trait.description\x1a\x1egoogle/protobuf/wrappers.proto\x1a\x12weave/common.proto\"\xd1\x01\n\x16SoftwareComponentTrait\x12g\n\x12softwareComponents\x18\x01 \x03(\x0b\x32K.weave.trait.description.SoftwareComponentTrait.SoftwareComponentTypeStruct\x1aN\n\x1bSoftwareComponentTypeStruct\x12\x15\n\rcomponentName\x18\x01 \x01(\t\x12\x18\n\x10\x63omponentVersion\x18\x02 \x01(\t\"\xec\x02\n\x13\x44\x65viceIdentityTrait\x12\x10\n\x08vendorId\x18\x01 \x01(\r\x12\x34\n\x13vendorIdDescription\x18\x02 \x01(\x0b\x32\x17.weave.common.StringRef\x12\x17\n\x0fvendorProductId\x18\x03 \x01(\r\x12\x35\n\x14productIdDescription\x18\x04 \x01(\x0b\x32\x17.weave.common.StringRef\x12\x17\n\x0fproductRevision\x18\x05 \x01(\r\x12\x14\n\x0cserialNumber\x18\x06 \x01(\t\x12\x17\n\x0fsoftwareVersion\x18\x07 \x01(\t\x12\x37\n\x11manufacturingDate\x18\x08 \x01(\x0b\x32\x1c.google.protobuf.StringValue\x12*\n\x08\x64\x65viceId\x18\t \x01(\x0b\x32\x18.weave.common.ResourceId\x12\x10\n\x08\x66\x61\x62ricId\x18\n \x01(\x04\"#\n\x12LabelSettingsTrait\x12\r\n\x05label\x18\x01 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'weave.trait.description_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SOFTWARECOMPONENTTRAIT']._serialized_start=111
  _globals['_SOFTWARECOMPONENTTRAIT']._serialized_end=320
  _globals['_SOFTWARECOMPONENTTRAIT_SOFTWARECOMPONENTTYPESTRUCT']._serialized_start=242
  _globals['_SOFTWARECOMPONENTTRAIT_SOFTWARECOMPONENTTYPESTRUCT']._serialized_end=320
  _globals['_DEVICEIDENTITYTRAIT']._serialized_start=323
  _globals['_DEVICEIDENTITYTRAIT']._serialized_end=687
  _globals['_LABELSETTINGSTRAIT']._serialized_start=689
  _globals['_LABELSETTINGSTRAIT']._serialized_end=724
# @@protoc_insertion_point(module_scope)
