config_entry:
  versions:
    - version:
        major: 1
        minor: 1
      data:
        fields:
          app_id:
            required: true
            selector:
              text: {}
          area:
            required: false
            selector:
              select:
                options: []
      options:
        fields: {}
  subentries: {}
