"""Constants for the Portainer integration."""

DOMAIN = "portainer"
DEFAULT_NAME = "Portainer"


ENDPOINT_STATUS_DOWN = 2

CONTAINER_STATE_RUNNING = "running"

STACK_STATUS_ACTIVE = 1
STACK_STATUS_INACTIVE = 2


STACK_TYPE_SWARM = 1
STACK_TYPE_COMPOSE = 2
STACK_TYPE_KUBERNETES = 3
