"""DO NOT MODIFY. Auto-generated by script/fingerprint_frontend."""

FINGERPRINTS = {
    "compatibility.js": "8e4c44b5f4288cc48ec1ba94a9bec812",
    "core.js": "d4a7cb8c80c62b536764e0e81385f6aa",
    "frontend.html": "d0142106cf282596062e5b2060128f81",
    "mdi.html": "e91f61a039ed0a9936e7ee5360da3870",
    "micromarkdown-js.html": "93b5ec4016f0bba585521cf4d18dec1a",
    "panels/ha-panel-automation.html": "72a5c1856cece8d9246328e84185ab0b",
    "panels/ha-panel-config.html": "5e2df66aa534c4dadd08c60c361f5d45",
    "panels/ha-panel-dev-event.html": "4886c821235492b1b92739b580d21c61",
    "panels/ha-panel-dev-info.html": "24e888ec7a8acd0c395b34396e9001bc",
    "panels/ha-panel-dev-service.html": "ac2c50e486927dc4443e93d79f08c06e",
    "panels/ha-panel-dev-state.html": "8f1a27c04db6329d31cfcc7d0d6a0869",
    "panels/ha-panel-dev-template.html": "82cd543177c417e5c6612e07df851e6b",
    "panels/ha-panel-hassio.html": "262d31efd9add719e0325da5cf79a096",
    "panels/ha-panel-history.html": "35177e2046c9a4191c8f51f8160255ce",
    "panels/ha-panel-iframe.html": "238189f21e670b6dcfac937e5ebd7d3b",
    "panels/ha-panel-kiosk.html": "2ac2df41bd447600692a0054892fc094",
    "panels/ha-panel-logbook.html": "7c45bd41c146ec38b9938b8a5188bb0d",
    "panels/ha-panel-map.html": "b4923812c695dd8a69ad3da380ffe7b4",
    "panels/ha-panel-shopping-list.html": "75602d06b41702c8093bd91c10374101",
    "panels/ha-panel-zwave.html": "8c8e7844d33163f560e1f691550a8369"
}
