"""The roomba constants."""
DOMAIN = "roomba"
CONF_CERT = "certificate"
CONF_CONTINUOUS = "continuous"
CONF_DELAY = "delay"
DEFAULT_CERT = "/etc/ssl/certs/ca-certificates.crt"
DEFAULT_CONTINUOUS = True
DEFAULT_DELAY = 1
DEFAULT_NAME = "Roomba"
