get_meal_plan_data:
  fields:
    device_id:
      required: true
      selector:
        device:
          integration: tuya

set_meal_plan_data:
  fields:
    device_id:
      required: true
      selector:
        device:
          integration: tuya
    data:
      required: true
      selector:
        text:
