config_entry:
  versions:
    - version:
        major: 1
        minor: 1
      data:
        fields:
          api_key:
            required: false
            selector:
              text: {}
          latitude:
            required: false
            selector:
              text: {}
          longitude:
            required: false
            selector:
              text: {}
          name:
            required: false
            selector:
              text: {}
      options:
        fields:
          radar_updates:
            required: false
            selector:
              text: {}
          station_updates:
            required: false
            selector:
              text: {}
  subentries: {}
