config_entry:
  versions:
    - version:
        major: 1
        minor: 1
      data:
        fields: {}
      options:
        fields:
          allow_nameless_uuids:
            required: false
            selector:
              object: {}
  subentries: {}
