"""Provides the constants needed for component."""

SUPPORT_ALARM_ARM_HOME = 1
SUPPORT_ALARM_ARM_AWAY = 2
SUPPORT_ALARM_ARM_NIGHT = 4
SUPPORT_ALARM_ARM_VACATION = 8
SUPPORT_ALARM_TRIGGER = 16
SUPPORT_ALARM_ARM_CUSTOM_BYPASS = 32


CONDITION_TRIGGERED = "is_triggered"
CONDITION_DISARMED = "is_disarmed"
CONDITION_ARMED_HOME = "is_armed_home"
CONDITION_ARMED_AWAY = "is_armed_away"
CONDITION_ARMED_NIGHT = "is_armed_night"
CONDITION_ARMED_VACATION = "is_armed_vacation"
CONDITION_ARMED_CUSTOM_BYPASS = "is_armed_custom_bypass"
