"""Constants for tomorrowio tests."""

from homeassistant.components.tomorrowio.const import (
    CONF_TIMESTEP,
    DEFAULT_NAME,
    DEFAULT_TIMESTEP,
)
from homeassistant.const import (
    CONF_API_KEY,
    CONF_LATITUDE,
    CONF_LOCATION,
    CONF_LONGITUDE,
    CONF_NAME,
)

API_KEY = "aa"

MIN_CONFIG = {CONF_API_KEY: API_KEY}

API_V4_ENTRY_DATA = {CONF_API_KEY: API_KEY}

TEST_LOCATION = {CONF_LATITUDE: 80.0, CONF_LONGITUDE: 80.0}
TEST_SUBENTRY_ID = "01JYYYYYYYYYYYYYYYYYYYYYYY"
TEST_SUBENTRY_DATA = {
    CONF_LOCATION: TEST_LOCATION,
    CONF_NAME: DEFAULT_NAME,
    CONF_TIMESTEP: DEFAULT_TIMESTEP,
}
BASE_UNIQUE_ID = f"{API_KEY}_80.0_80.0"
