"""Constants for caldav integration."""

CONF_ADD_CUSTOM_CALENDAR = "add_new_custom_calendars"
CONF_CALENDAR = "calendar"
CONF_CALENDAR_NEW_ID = "calendar_new_id"
CONF_CALENDAR_ID = "calendar_id"
CONF_CALENDAR_UP_ID = "calendar_update_id"
CONF_CALENDARS = "calendars"
CONF_CALENDAR_DELETE = "calendar_delete"
CONF_CUSTOM_CALENDARS = "custom_calendars"
CONF_DAYS = "days"
CONF_SEARCH = "search"
DEFAULT_VERIFY_SSL = True
DOMAIN = "caldav"
OFFSET = "!!"
