get_epex_prices_for_date:
  fields:
    config_entry:
      required: true
      selector:
        config_entry:
          integration: engie_be
    date:
      required: true
      selector:
        date:
    granularity:
      default: "hourly"
      selector:
        select:
          options:
            - "hourly"
            - "quarter_hourly"
          mode: dropdown
          translation_key: granularity
