config_entry:
  versions:
    - version:
        major: 1
        minor: 2
      data:
        fields:
          serial:
            required: true
            selector:
              select:
                options: []
      options:
        fields: {}
  subentries: {}
