"""Constants for HERE Travel Time tests."""

from homeassistant.components.here_travel_time.const import (
    CONF_DESTINATION_LATITUDE,
    CONF_DESTINATION_LONGITUDE,
    CONF_ORIGIN_LATITUDE,
    CONF_ORIGIN_LONGITUDE,
    TRAVEL_MODE_CAR,
)
from homeassistant.const import CONF_API_KEY, CONF_MODE, CONF_NAME

API_KEY = "test"

ORIGIN_LATITUDE = "38.9"
ORIGIN_LONGITUDE = "-77.04833"
DESTINATION_LATITUDE = "39.0"
DESTINATION_LONGITUDE = "-77.1"

DEFAULT_CONFIG = {
    CONF_ORIGIN_LATITUDE: float(ORIGIN_LATITUDE),
    CONF_ORIGIN_LONGITUDE: float(ORIGIN_LONGITUDE),
    CONF_DESTINATION_LATITUDE: float(DESTINATION_LATITUDE),
    CONF_DESTINATION_LONGITUDE: float(DESTINATION_LONGITUDE),
    CONF_API_KEY: API_KEY,
    CONF_MODE: TRAVEL_MODE_CAR,
    CONF_NAME: "test",
}
