"""Constants for the Android TV Remote integration."""
from __future__ import annotations

from typing import Final

DOMAIN: Final = "androidtv_remote"
KNOWN_APPS: Final = {
    "com.aetn.aetv.watch": "A&E",
    "com.amazon.a" + "vod.thirdpartyclient": "Amazon Prime Video",
    "com.amazon.a" + "vod": "Amazon Video",
    "com.apple.atve.android.appletv": "Apple TV+",
    "com.apple.atve.amazon.appletv": "Apple TV+ (Fire TV)",
    "com.apple.atve.sony.appletv": "Apple TV+ (Sony)",
    "com.google.android.tvlauncher": "Android TV Launcher",
    "com.quickplay.android.bellmediaplayer": "Bell Fibe",
    "ca.cbc.android.cbctv": "CBC Gem",
    "com.vmn.android.comedycentral": "Comedy Central",
    "ca.bellmedia.cravetv": "Crave",
    "com.dailymotion.dailymotion": "Dailymotion",
    "deezer.android.tv": "Deezer",
    "com.disney.disneyplus": "Disney+",
    "in.startv.hotstar": "Disney+ Hotstar",
    "com.synology.dsphoto": "DS photo",
    "com.synology.dsvideo": "DS video",
    "tv.emby.embyatv": "Emby",
    "com.estrongs.android.pop": "ES File Explorer",
    "com.facebook.katana": "Facebook Watch",
    "com.future.moviesByFawesomeAndroidTV": "Fawsome",
    "org.mozilla.tv.firefox": "Firefox",
    "com.amazon.venezia": "FireTV Store",
    "tv.accedo.foodnetwork": "Food Network GO",
    "fr.francetv.pluzz": "France TV",
    "com.shawmedia.smglobal": "Global TV",
    "com.google.android.katniss": "Google App",
    "com.google.android.apps.mediashell": "Google Cast",
    "com.google.android.apps.tv.launcherx": "Google TV Launcher",
    "com.haystack.android": "Haystack News",
    "eu.hbogo.androidtv.production": "HBO GO",
    "com.HBO": "HBO GO (2)",
    "com.viewlift.hoichoi": "Hoichoi",
    "com.hulu.plus": "Hulu",
    "com.hungama.movies.tv": "Hungama Play",
    "com.amazon.imdb.tv.android.app": "IMDb TV",
    "ru.iptvremote.android.iptv": "IPTV",
    "com.nst.iptvsmarterstvbox": "IPTV Smarters Pro",
    "org.jellyfin.androidtv": "Jellyfin",
    "com.jio.media.stb.ondemand": "Jio Cinema",
    "org.xbmc.kodi": "Kodi",
    "com.google.android.tv": "Live Channels",
    "de.telekom.magentatv.atv": "Magenta TV",
    "org.samsonsen.nederlandse.radio.holland.nl": "Mijn Radio",
    "tv.molotov.app": "Molotov",
    "tv.mrmc.mrmc": "MrMC",
    "tv.mrmc.mrmc.lite": "MrMC Lite",
    "com.mxtech.videoplayer.ad": "MX Player",
    "com.netflix.ninja": "Netflix",
    "nl.nlziet": "NLZIET",
    "nl.nos.app": "NOS",
    "nl.uitzendinggemist": "NPO",
    "com.orange.ocsgo": "OCS",
    "com.google.android.play.games": "Play Games",
    "com.google.android.music": "Play Music",
    "com.android.vending": "Play Store",
    "com.google.android.videos": "Play Movies & TV",
    "com.plexapp.android": "Plex",
    "com.amazon.amazonvideo.livingroom": "Prime Video",
    "com.amazon.firebat": "Prime Video (FireTV)",
    "com.android.tv.settings": "Settings",
    "com.teamsmart.videomanager.tv": "SmartTube",
    "com.liskovsoft.videomanager": "Smart YouTube TV",
    "com.sony.dtv.scrums.action": "Action Menu",
    "com.sony.dtv.osat.album": "Album",
    "com.sony.dtv.braviasyncmenu": "Sync Menu",
    "com.sony.dtv.bravialifehack": "BRAVIA Tutorials",
    "com.sony.dtv.discovery": "Discover",
    "com.sony.dtv.smarthelp": "Help",
    "com.vewd.core.integration.dia": "Internet Browser",
    "com.sonyliv": "SonyLIV",
    "com.sony.dtv.osat.music": "Music",
    "com.sony.dtv.networkapp.wifidirect": "Screen mirroring",
    "com.sony.dtv.sonyselect": "Sony Select",
    "com.sony.dtv.timers": "Timers",
    "com.sony.dtv.tvx": "TV",
    "com.sony.dtv.osat.video": "Video",
    "de.sport1.firetv.video": "Sport 1",
    "com.spotify.tv.android": "Spotify",
    "com.valvesoftware.steamlink": "Steam Link",
    "com.amazon.webapps.nbc.syfy": "Syfy",
    "tv.perception.clients.tv.android": "T-2 TV",
    "com.ted.android.tv": "TED",
    "ar.tvplayer.tv": "TiviMate",
    "tunein.player": "TuneIn Radio",
    "de.cyberdream.dreamepg.tvh.tv.player": "DreamPlayer TVHeadend",
    "tv.twitch.android.app": "Twitch",
    "tv.twitch.android.viewer": "Twitch (FireTV)",
    "com.vevo.tv": "Vevo",
    "com.mtvn.vh1android": "VH1",
    "com.vimeo.android.videoapp": "Vimeo",
    "net.gtvbox.videoplayer": "Vimu Media Player",
    "net.gtvbox.vimuhd": "Vimu Media Player",
    "org.videolan.vlc": "VLC",
    "com.phonegap.voyo": "VOYO",
    "com.ellation.vrv": "VRV",
    "de.exaring.waipu.firetv.live": "Waipu TV",
    "com.turner.tnt.android.networkapp": "Watch TNT",
    "com.google.android.youtube.tv": "YouTube",
    "com.amazon.firetv.youtube": "YouTube (FireTV)",
    "com.google.android.youtube.tvkids": "YouTube Kids",
    "com.amazon.firetv.youtube.kids": "YouTube Kids (FireTV)",
    "com.google.android.youtube.tvmusic": "YouTube Music",
    "com.google.android.youtube.tvunplugged": "YouTube TV",
    "com.graymatrix.did": "ZEE5",
    "com.ziggo.tv": "Ziggo GO TV",
}
