config_entry:
  versions:
    - version:
        major: 1
        minor: 1
      data:
        fields:
          device_input:
            required: true
            selector:
              text: {}
      options:
        fields:
          start_off:
            required: false
            selector:
              text: {}
  subentries: {}
