"""Constants for the Songpal component."""
DOMAIN = "songpal"
SET_SOUND_SETTING = "set_sound_setting"
CREATE_GROUP = "create_group"
ABORT_GROUP = "abort_group"
CONF_ENDPOINT = "endpoint"
CONF_URL = "url"
CONF_UUID = "uuid"
