send_message:
  target:
    entity:
      domain: notify
      integration: smtp
  fields:
    title:
      required: false
      selector:
        text:
      example: Home Assistant
      default: Home Assistant
    message:
      required: true
      selector:
        text:
          multiline: true
      example: Hello World
    html:
      required: false
      selector:
        text:
          multiline: true
    attachments:
      required: false
      selector:
        object:
          label_field: attachment
          description_field: filename
          multiple: true
          fields:
            attachment:
              required: true
              selector:
                media:
                  multiple: true
                  accept:
                    - "*"
            filename:
              required: false
              selector:
                text:
            content_id:
              required: false
              selector:
                text:
          translation_key: attachments
