"""Const for LIFX."""

CONF_BROADCAST = "broadcast"
CONF_DISCOVERY_INTERVAL = "discovery_interval"
CONF_DUPLICATE_DISCOVERY = "duplicate_discovery"
CONF_GRACE_PERIOD = "grace_period"
CONF_MESSAGE_TIMEOUT = "message_timeout"
CONF_RETRY_COUNT = "retry_count"
CONF_SERVER = "server"
DATA_LIFX_MANAGER = "lifx_manager"
DEFAULT_DISCOVERY_INTERVAL = 60
DEFAULT_DUPLICATE_DISCOVERY = False
DEFAULT_GRACE_PERIOD = 90
DEFAULT_MESSAGE_TIMEOUT = 1.0
DEFAULT_RETRY_COUNT = 8
DOMAIN = "lifx"
