set_hev_cycle_state:
  target:
    entity:
      integration: lifx
      domain: light
  fields:
    power:
      required: true
      example: true
      selector:
        boolean:
    duration:
      required: false
      default: 7200
      example: 3600
      selector:
        number:
          min: 0
          max: 86400
          unit_of_measurement: seconds
set_state:
  target:
    entity:
      integration: lifx
      domain: light
  fields:
    infrared:
      selector:
        number:
          min: 0
          max: 255
    zones:
      example: "[0,5]"
      selector:
        object:
    transition:
      selector:
        number:
          min: 0
          max: 3600
          unit_of_measurement: seconds
    power:
      selector:
        boolean:

effect_pulse:
  target:
    entity:
      integration: lifx
      domain: light
  fields:
    mode:
      selector:
        select:
          options:
            - "blink"
            - "breathe"
            - "ping"
            - "strobe"
            - "solid"
    brightness:
      selector:
        number:
          min: 1
          max: 255
    brightness_pct:
      selector:
        number:
          min: 1
          max: 100
          unit_of_measurement: "%"
    color_name:
      example: "red"
      selector:
        text:
    rgb_color:
      example: "[255, 100, 100]"
      selector:
        object:
    period:
      default: 1.0
      selector:
        number:
          min: 0.05
          max: 60.00
          step: 0.05
          unit_of_measurement: seconds
    cycles:
      default: 1
      selector:
        number:
          min: 1
          max: 10000
    power_on:
      default: true
      selector:
        boolean:

effect_colorloop:
  target:
    entity:
      integration: lifx
      domain: light
  fields:
    brightness:
      selector:
        number:
          min: 0
          max: 255
    brightness_pct:
      selector:
        number:
          min: 0
          max: 100
          unit_of_measurement: "%"
    saturation_min:
      default: 80
      selector:
        number:
          min: 1
          max: 100
          unit_of_measurement: "%"
    saturation_max:
      default: 100
      selector:
        number:
          min: 1
          max: 100
          unit_of_measurement: "%"
    transition:
      required: false
      selector:
        number:
          min: 0
          max: 3600
          unit_of_measurement: seconds
    period:
      default: 60
      selector:
        number:
          min: 0.05
          max: 3600.00
          step: 0.05
          unit_of_measurement: seconds
    change:
      default: 20
      selector:
        number:
          min: 0
          max: 360
          unit_of_measurement: "°"
    spread:
      default: 30
      selector:
        number:
          min: 0
          max: 360
          unit_of_measurement: "°"
    power_on:
      default: true
      selector:
        boolean:
effect_move:
  target:
    entity:
      integration: lifx
      domain: light
  fields:
    speed:
      default: 3.0
      example: 3.0
      selector:
        number:
          min: 0.1
          max: 60
          step: 0.1
          unit_of_measurement: seconds
    direction:
      default: right
      example: right
      selector:
        select:
          mode: dropdown
          options:
            - right
            - left
    theme:
      example: exciting
      default: exciting
      selector:
        select:
          mode: dropdown
          options:
            - "arctic"
            - "arlington"
            - "aurora"
            - "aurora_borealis"
            - "autumn"
            - "autumn_table"
            - "baubles"
            - "be_my_valentine"
            - "beach"
            - "bedroom_glow_up"
            - "bias_lighting"
            - "bijutsukai"
            - "blissful"
            - "blood_moon"
            - "bloodlust"
            - "book_of_the_dead"
            - "calaveras"
            - "canada_day"
            - "candy_cane"
            - "candy_cane_twist"
            - "cheerful"
            - "cherry_blossom"
            - "christmas"
            - "classic_rock"
            - "classical"
            - "clouds"
            - "coral_reef"
            - "cranberry_harvest"
            - "crystal_twist"
            - "cyberpunk"
            - "dance_pop"
            - "deck_the_halls"
            - "deep_sea"
            - "desert"
            - "dinner_for_two"
            - "disco"
            - "diwali"
            - "dream"
            - "earth"
            - "energising"
            - "energizing"
            - "epic"
            - "eternal"
            - "evening"
            - "exciting"
            - "extraterrestrial"
            - "fall"
            - "fantasy"
            - "festive"
            - "fire"
            - "focusing"
            - "forest"
            - "forrest"
            - "fright_night"
            - "funk"
            - "galaxy"
            - "garage_rock"
            - "gauguin"
            - "gentle"
            - "ghostly"
            - "gold_star"
            - "graveyard_chill"
            - "halloween"
            - "hanukkah"
            - "haunted_fog"
            - "hip_hop_rap"
            - "hokusai"
            - "holly"
            - "hygge"
            - "independence"
            - "indie_pop"
            - "intense"
            - "jazz"
            - "jupiter"
            - "kandinsky"
            - "klimt"
            - "kwanzaa"
            - "leprechaun_treasure"
            - "lo_fi"
            - "love"
            - "lucky_shamrock"
            - "mars"
            - "matisse"
            - "mellow"
            - "memorial_day"
            - "menorah"
            - "mercury"
            - "midnight_shadows"
            - "mistletoe"
            - "molly_malone"
            - "mondrian"
            - "monet"
            - "moon"
            - "movie_night_romance"
            - "neon"
            - "neptune"
            - "ocean"
            - "oktoberfest"
            - "old_glory"
            - "outback"
            - "parade"
            - "paranormal"
            - "party"
            - "peaceful"
            - "pine_glow"
            - "pluto"
            - "pop"
            - "poppy"
            - "powerful"
            - "pride"
            - "proud"
            - "psychedelic_rock"
            - "pumpkin"
            - "pumpkin_glow"
            - "pumpkin_party"
            - "pumpkin_spice"
            - "punk"
            - "ramadan"
            - "redrum"
            - "relaxing"
            - "romance"
            - "rousseau"
            - "sage_and_cedar"
            - "santa"
            - "santas_candy"
            - "santas_workshop"
            - "saturn"
            - "sci_fi"
            - "scream_queen"
            - "self_care_sanctuary"
            - "serene"
            - "shamrock"
            - "slasher"
            - "snake_banisher"
            - "snowflake"
            - "soothing"
            - "spacey"
            - "spiders_lair"
            - "sports"
            - "spring"
            - "st_patricks_day"
            - "stardust"
            - "storm_front"
            - "sun"
            - "synthwave"
            - "taps"
            - "thanksgiving"
            - "the_tricolour"
            - "toxic_cauldron"
            - "tranquil"
            - "tropical"
            - "turkey_dinner"
            - "uranus"
            - "valentines"
            - "vampires_den"
            - "van_gogh"
            - "vaporwave"
            - "venus"
            - "warm_ember"
            - "warming"
            - "water"
            - "whats_the_craic"
            - "wheat_glow"
            - "winter_night"
            - "winter_wonderland"
            - "witchs_ritual"
            - "witchy"
            - "zombie"
            - "zombie_apocalypse"
    power_on:
      default: true
      selector:
        boolean:
effect_flame:
  target:
    entity:
      integration: lifx
      domain: light
  fields:
    speed:
      default: 3
      selector:
        number:
          min: 1
          max: 25
          step: 1
          unit_of_measurement: seconds
    power_on:
      default: true
      selector:
        boolean:
effect_morph:
  target:
    entity:
      integration: lifx
      domain: light
  fields:
    speed:
      default: 3
      selector:
        number:
          min: 1
          max: 25
          step: 1
          unit_of_measurement: seconds
    palette:
      example:
        - "[[0, 100, 100, 3500], [60, 100, 100, 3500]]"
      selector:
        object:
    theme:
      selector:
        select:
          options:
            - "arctic"
            - "arlington"
            - "aurora"
            - "aurora_borealis"
            - "autumn"
            - "autumn_table"
            - "baubles"
            - "be_my_valentine"
            - "beach"
            - "bedroom_glow_up"
            - "bias_lighting"
            - "bijutsukai"
            - "blissful"
            - "blood_moon"
            - "bloodlust"
            - "book_of_the_dead"
            - "calaveras"
            - "canada_day"
            - "candy_cane"
            - "candy_cane_twist"
            - "cheerful"
            - "cherry_blossom"
            - "christmas"
            - "classic_rock"
            - "classical"
            - "clouds"
            - "coral_reef"
            - "cranberry_harvest"
            - "crystal_twist"
            - "cyberpunk"
            - "dance_pop"
            - "deck_the_halls"
            - "deep_sea"
            - "desert"
            - "dinner_for_two"
            - "disco"
            - "diwali"
            - "dream"
            - "earth"
            - "energising"
            - "energizing"
            - "epic"
            - "eternal"
            - "evening"
            - "exciting"
            - "extraterrestrial"
            - "fall"
            - "fantasy"
            - "festive"
            - "fire"
            - "focusing"
            - "forest"
            - "forrest"
            - "fright_night"
            - "funk"
            - "galaxy"
            - "garage_rock"
            - "gauguin"
            - "gentle"
            - "ghostly"
            - "gold_star"
            - "graveyard_chill"
            - "halloween"
            - "hanukkah"
            - "haunted_fog"
            - "hip_hop_rap"
            - "hokusai"
            - "holly"
            - "hygge"
            - "independence"
            - "indie_pop"
            - "intense"
            - "jazz"
            - "jupiter"
            - "kandinsky"
            - "klimt"
            - "kwanzaa"
            - "leprechaun_treasure"
            - "lo_fi"
            - "love"
            - "lucky_shamrock"
            - "mars"
            - "matisse"
            - "mellow"
            - "memorial_day"
            - "menorah"
            - "mercury"
            - "midnight_shadows"
            - "mistletoe"
            - "molly_malone"
            - "mondrian"
            - "monet"
            - "moon"
            - "movie_night_romance"
            - "neon"
            - "neptune"
            - "ocean"
            - "oktoberfest"
            - "old_glory"
            - "outback"
            - "parade"
            - "paranormal"
            - "party"
            - "peaceful"
            - "pine_glow"
            - "pluto"
            - "pop"
            - "poppy"
            - "powerful"
            - "pride"
            - "proud"
            - "psychedelic_rock"
            - "pumpkin"
            - "pumpkin_glow"
            - "pumpkin_party"
            - "pumpkin_spice"
            - "punk"
            - "ramadan"
            - "redrum"
            - "relaxing"
            - "romance"
            - "rousseau"
            - "sage_and_cedar"
            - "santa"
            - "santas_candy"
            - "santas_workshop"
            - "saturn"
            - "sci_fi"
            - "scream_queen"
            - "self_care_sanctuary"
            - "serene"
            - "shamrock"
            - "slasher"
            - "snake_banisher"
            - "snowflake"
            - "soothing"
            - "spacey"
            - "spiders_lair"
            - "sports"
            - "spring"
            - "st_patricks_day"
            - "stardust"
            - "storm_front"
            - "sun"
            - "synthwave"
            - "taps"
            - "thanksgiving"
            - "the_tricolour"
            - "toxic_cauldron"
            - "tranquil"
            - "tropical"
            - "turkey_dinner"
            - "uranus"
            - "valentines"
            - "vampires_den"
            - "van_gogh"
            - "vaporwave"
            - "venus"
            - "warm_ember"
            - "warming"
            - "water"
            - "whats_the_craic"
            - "wheat_glow"
            - "winter_night"
            - "winter_wonderland"
            - "witchs_ritual"
            - "witchy"
            - "zombie"
            - "zombie_apocalypse"
    power_on:
      default: true
      selector:
        boolean:
effect_sky:
  target:
    entity:
      integration: lifx
      domain: light
  fields:
    power_on:
      default: true
      selector:
        boolean:
    speed:
      default: 50
      example: 50
      selector:
        number:
          min: 1
          max: 86400
          step: 1
          unit_of_measurement: seconds
    sky_type:
      default: "Clouds"
      example: "Clouds"
      selector:
        select:
          options:
            - "Clouds"
            - "Sunrise"
            - "Sunset"
    cloud_saturation_min:
      default: 50
      example: 50
      selector:
        number:
          min: 0
          max: 255
    cloud_saturation_max:
      default: 180
      example: 180
      selector:
        number:
          min: 0
          max: 255
    palette:
      example:
        - "[200, 1, 1, 3500]"
        - "[241, 1, 0.01, 3500]"
        - "[189, 1, 0.08, 3500]"
        - "[40, 1, 1, 3500]"
        - "[40, 0.5, 1, 3500]"
        - "[40, 0, 1, 6500]"
      selector:
        object:
effect_stop:
  target:
    entity:
      integration: lifx
      domain: light
paint_theme:
  target:
    entity:
      integration: lifx
      domain: light
  fields:
    palette:
      example:
        - "[[0, 100, 100, 3500], [60, 100, 100, 3500]]"
      selector:
        object:
    theme:
      example: exciting
      default: exciting
      selector:
        select:
          mode: dropdown
          options:
            - "arctic"
            - "arlington"
            - "aurora"
            - "aurora_borealis"
            - "autumn"
            - "autumn_table"
            - "baubles"
            - "be_my_valentine"
            - "beach"
            - "bedroom_glow_up"
            - "bias_lighting"
            - "bijutsukai"
            - "blissful"
            - "blood_moon"
            - "bloodlust"
            - "book_of_the_dead"
            - "calaveras"
            - "canada_day"
            - "candy_cane"
            - "candy_cane_twist"
            - "cheerful"
            - "cherry_blossom"
            - "christmas"
            - "classic_rock"
            - "classical"
            - "clouds"
            - "coral_reef"
            - "cranberry_harvest"
            - "crystal_twist"
            - "cyberpunk"
            - "dance_pop"
            - "deck_the_halls"
            - "deep_sea"
            - "desert"
            - "dinner_for_two"
            - "disco"
            - "diwali"
            - "dream"
            - "earth"
            - "energising"
            - "energizing"
            - "epic"
            - "eternal"
            - "evening"
            - "exciting"
            - "extraterrestrial"
            - "fall"
            - "fantasy"
            - "festive"
            - "fire"
            - "focusing"
            - "forest"
            - "forrest"
            - "fright_night"
            - "funk"
            - "galaxy"
            - "garage_rock"
            - "gauguin"
            - "gentle"
            - "ghostly"
            - "gold_star"
            - "graveyard_chill"
            - "halloween"
            - "hanukkah"
            - "haunted_fog"
            - "hip_hop_rap"
            - "hokusai"
            - "holly"
            - "hygge"
            - "independence"
            - "indie_pop"
            - "intense"
            - "jazz"
            - "jupiter"
            - "kandinsky"
            - "klimt"
            - "kwanzaa"
            - "leprechaun_treasure"
            - "lo_fi"
            - "love"
            - "lucky_shamrock"
            - "mars"
            - "matisse"
            - "mellow"
            - "memorial_day"
            - "menorah"
            - "mercury"
            - "midnight_shadows"
            - "mistletoe"
            - "molly_malone"
            - "mondrian"
            - "monet"
            - "moon"
            - "movie_night_romance"
            - "neon"
            - "neptune"
            - "ocean"
            - "oktoberfest"
            - "old_glory"
            - "outback"
            - "parade"
            - "paranormal"
            - "party"
            - "peaceful"
            - "pine_glow"
            - "pluto"
            - "pop"
            - "poppy"
            - "powerful"
            - "pride"
            - "proud"
            - "psychedelic_rock"
            - "pumpkin"
            - "pumpkin_glow"
            - "pumpkin_party"
            - "pumpkin_spice"
            - "punk"
            - "ramadan"
            - "redrum"
            - "relaxing"
            - "romance"
            - "rousseau"
            - "sage_and_cedar"
            - "santa"
            - "santas_candy"
            - "santas_workshop"
            - "saturn"
            - "sci_fi"
            - "scream_queen"
            - "self_care_sanctuary"
            - "serene"
            - "shamrock"
            - "slasher"
            - "snake_banisher"
            - "snowflake"
            - "soothing"
            - "spacey"
            - "spiders_lair"
            - "sports"
            - "spring"
            - "st_patricks_day"
            - "stardust"
            - "storm_front"
            - "sun"
            - "synthwave"
            - "taps"
            - "thanksgiving"
            - "the_tricolour"
            - "toxic_cauldron"
            - "tranquil"
            - "tropical"
            - "turkey_dinner"
            - "uranus"
            - "valentines"
            - "vampires_den"
            - "van_gogh"
            - "vaporwave"
            - "venus"
            - "warm_ember"
            - "warming"
            - "water"
            - "whats_the_craic"
            - "wheat_glow"
            - "winter_night"
            - "winter_wonderland"
            - "witchs_ritual"
            - "witchy"
            - "zombie"
            - "zombie_apocalypse"
    transition:
      selector:
        number:
          min: 0
          max: 3600
          unit_of_measurement: seconds
    power_on:
      default: true
      selector:
        boolean:
