"""Constants for the Appwrite integration."""

DOMAIN = "appwrite"
CONF_PROJECT_ID = "project_id"
CONF_ENDPOINT = "endpoint"
CONF_TITLE = "title"
CONF_FIELDS = "fields"
SERVICE_FUNCTION = "function"
FUNCTION_BODY = "function_body"
FUNCTION_PATH = "function_path"
FUNCTION_HEADERS = "function_headers"
FUNCTION_SCHEDULED_AT = "function_scheduled_at"
FUNCTION_ASYNC = "function_async"
FUNCTION_METHOD = "function_method"
