# Describes the format for available Litter-Robot services

set_sleep_mode:
  target:
    entity:
      domain: vacuum
      integration: litterrobot
  fields:
    enabled:
      required: true
      selector:
        boolean:
    start_time:
      required: false
      example: '"22:30:00"'
      selector:
        time:

reassign_visit:
  fields:
    config_entry_id:
      required: false
      selector:
        config_entry:
          integration: litterrobot
    event_id:
      required: true
      selector:
        text:
    from_pet_id:
      required: false
      selector:
        text:
    to_pet_id:
      required: false
      selector:
        text:
