get_schedule:
  target:
    entity:
      domain: climate
      integration: eurotronic_cometblue

set_schedule:
  target:
    entity:
      domain: climate
      integration: eurotronic_cometblue
  fields:
    monday:
      example: |
        - start: 07:00:00
          end: 09:00:00
        - start: 10:00:00
          end: 12:00:00
        - start: 13:00:00
          end: 17:00:00
        - start: 20:00:00
          end: 23:00:00
      required: false
      selector:
        object:
          fields:
            schedule:
              label: Schedule
              required: false
              selector:
                object:
                  label_field: start
                  description_field: end
                  multiple: true
                  fields:
                    start:
                      label: Start
                      required: false
                      selector:
                        time:
                    end:
                      label: End
                      required: false
                      selector:
                        time:
            delete:
              label: Delete
              required: false
              selector:
                boolean:
    tuesday:
      example: |
        - start: 07:00:00
          end: 09:00:00
        - start: 10:00:00
          end: 12:00:00
        - start: 13:00:00
          end: 17:00:00
        - start: 20:00:00
          end: 23:00:00
      required: false
      selector:
        object:
          fields:
            schedule:
              label: Schedule
              required: false
              selector:
                object:
                  label_field: start
                  description_field: end
                  multiple: true
                  fields:
                    start:
                      label: Start
                      required: false
                      selector:
                        time:
                    end:
                      label: End
                      required: false
                      selector:
                        time:
            delete:
              label: Delete
              required: false
              selector:
                boolean:
    wednesday:
      example: |
        - start: 07:00:00
          end: 09:00:00
        - start: 10:00:00
          end: 12:00:00
        - start: 13:00:00
          end: 17:00:00
        - start: 20:00:00
          end: 23:00:00
      required: false
      selector:
        object:
          fields:
            schedule:
              label: Schedule
              required: false
              selector:
                object:
                  label_field: start
                  description_field: end
                  multiple: true
                  fields:
                    start:
                      label: Start
                      required: false
                      selector:
                        time:
                    end:
                      label: End
                      required: false
                      selector:
                        time:
            delete:
              label: Delete
              required: false
              selector:
                boolean:
    thursday:
      example: |
        - start: 07:00:00
          end: 09:00:00
        - start: 10:00:00
          end: 12:00:00
        - start: 13:00:00
          end: 17:00:00
        - start: 20:00:00
          end: 23:00:00
      required: false
      selector:
        object:
          fields:
            schedule:
              label: Schedule
              required: false
              selector:
                object:
                  label_field: start
                  description_field: end
                  multiple: true
                  fields:
                    start:
                      label: Start
                      required: false
                      selector:
                        time:
                    end:
                      label: End
                      required: false
                      selector:
                        time:
            delete:
              label: Delete
              required: false
              selector:
                boolean:
    friday:
      example: |
        - delete: true
      required: false
      selector:
        object:
          fields:
            schedule:
              label: Schedule
              required: false
              selector:
                object:
                  label_field: start
                  description_field: end
                  multiple: true
                  fields:
                    start:
                      label: Start
                      required: false
                      selector:
                        time:
                    end:
                      label: End
                      required: false
                      selector:
                        time:
            delete:
              label: Delete
              required: false
              selector:
                boolean:
    saturday:
      example: |
        - start: 09:00:00
          end: 12:00:00
        - start: 17:00:00
          end: 19:00:00
      required: false
      selector:
        object:
          fields:
            schedule:
              label: Schedule
              required: false
              selector:
                object:
                  label_field: start
                  description_field: end
                  multiple: true
                  fields:
                    start:
                      label: Start
                      required: false
                      selector:
                        time:
                    end:
                      label: End
                      required: false
                      selector:
                        time:
            delete:
              label: Delete
              required: false
              selector:
                boolean:
    sunday:
      example: |
        - start: 07:00:00
          end: 09:00:00
        - start: 10:00:00
          end: 12:00:00
        - start: 13:00:00
          end: 17:00:00
        - start: 20:00:00
          end: 23:00:00
      required: false
      selector:
        object:
          fields:
            schedule:
              label: Schedule
              required: false
              selector:
                object:
                  label_field: start
                  description_field: end
                  multiple: true
                  fields:
                    start:
                      label: Start
                      required: false
                      selector:
                        time:
                    end:
                      label: End
                      required: false
                      selector:
                        time:
            delete:
              label: Delete
              required: false
              selector:
                boolean:

set_holiday:
  target:
    entity:
      domain: climate
      integration: eurotronic_cometblue
  fields:
    start:
      example: 2023-12-24 17:00:00
      required: true
      selector:
        datetime:
    end:
      example: 2023-12-31 23:30:00
      required: true
      selector:
        datetime:
    temperature:
      example: 20
      required: true
      selector:
        number:
          min: 8
          max: 28
          step: 0.5
          unit_of_measurement: °C
