config_entry:
  versions:
    - version:
        major: 1
        minor: 1
      data:
        fields:
          site:
            required: true
            selector:
              select:
                multiple: false
                options: []
      options:
        fields: {}
  subentries: {}
