alarm_arm_automatic:
  target:
    entity:
      domain: alarm_control_panel
      integration: elke27
  fields:
    mode:
      required: true
      selector:
        select:
          options:
            - away
            - home
    code:
      required: true
      selector:
        text:
          type: password
