"""Component constants."""

DOMAIN = "ohme"
CONFIG_VERSION = 1
ENTITY_TYPES = ["sensor", "binary_sensor", "switch", "button", "number", "time"]

COORDINATOR_CHARGESESSIONS = 0
COORDINATOR_ACCOUNTINFO = 1
COORDINATOR_ADVANCED = 2
COORDINATOR_SCHEDULES = 3

DEFAULT_INTERVAL_CHARGESESSIONS = 0.5
DEFAULT_INTERVAL_ACCOUNTINFO = 1
DEFAULT_INTERVAL_ADVANCED = 1
DEFAULT_INTERVAL_SCHEDULES = 10
