"""Component constants."""

from homeassistant.const import Platform

DOMAIN = "ohme"
PLATFORMS = [Platform.BINARY_SENSOR]

COORDINATOR_CHARGESESSIONS = 0
COORDINATOR_ADVANCED = 1

DEFAULT_INTERVAL_CHARGESESSIONS = 0.5
DEFAULT_INTERVAL_ADVANCED = 1
