"""Component constants."""

DOMAIN = "ohme"
CONFIG_VERSION = 1
ENTITY_TYPES = ["binary_sensor"]

COORDINATOR_CHARGESESSIONS = 0
COORDINATOR_ADVANCED = 1

DEFAULT_INTERVAL_CHARGESESSIONS = 0.5
DEFAULT_INTERVAL_ADVANCED = 1
