"""Constants for the zone component."""

CONF_PASSIVE = "passive"
DOMAIN = "zone"
HOME_ZONE = "home"
ATTR_PASSIVE = "passive"
ATTR_RADIUS = "radius"
ATTR_POINTS = "points"
ATTR_TYPE = "zone_type"
DEFAULT_TYPE = "circle"
