config_entry:
  versions:
    - version:
        major: 1
        minor: 1
      data:
        fields:
          location:
            required: true
            selector:
              select:
                translation_key: location
                mode: list
                options:
                  - use_home_location
                  - specify_coordinates
                  - specify_country_code
      options:
        fields: {}
  subentries: {}
