"""Constants for the LibreNMS integration tests."""

from aiolibrenms.devices.models import LibrenmsDeviceInfo
from aiolibrenms.system.models import LibrenmsSystemInfo

from homeassistant.const import (
    CONF_API_KEY,
    CONF_HOST,
    CONF_PORT,
    CONF_SSL,
    CONF_URL,
    CONF_VERIFY_SSL,
)

MOCK_USER_DATA = {
    CONF_URL: "https://librenms",
    CONF_API_KEY: "abcdef0123456789",
    CONF_VERIFY_SSL: True,
}

MOCK_CONFIG_ENTRY_DATA = {
    CONF_HOST: "librenms",
    CONF_API_KEY: "abcdef0123456789",
    CONF_PORT: 443,
    CONF_SSL: True,
    CONF_VERIFY_SSL: True,
}

MOCK_SYSTEM_DATA = LibrenmsSystemInfo.from_dict(
    {
        "local_ver": "26.6.1",
        "local_sha": "",
        "local_date": "2026-06-18T09:10:36+02:00",
        "local_branch": "",
        "db_schema": "2026_06_09_000000_change_vsz_to_big_int_processes_table (390)",
        "php_ver": "8.4.21",
        "python_ver": "3.12.13",
        "database_ver": "MariaDB 10.5.29-MariaDB-ubu2004",
        "rrdtool_ver": "1.9.0",
        "netsnmp_ver": "5.9.5.2",
    }
)

MOCK_DEVICES_DATA = [
    LibrenmsDeviceInfo.from_dict(
        {
            "device_id": 3,
            "inserted": "2023-09-16 11:34:51",
            "hostname": "192.168.1.104",
            "sysName": "printer",
            "display": "Drucker",
            "display_template": "Drucker",
            "ip": "192.168.1.104",
            "overwrite_ip": "",
            "community": "read-only",
            "authlevel": None,
            "authname": None,
            "authpass": None,
            "authalgo": None,
            "cryptopass": None,
            "cryptoalgo": None,
            "snmpver": "v2c",
            "port": 161,
            "transport": "udp",
            "timeout": None,
            "retries": None,
            "snmp_disable": 0,
            "bgpLocalAs": None,
            "sysObjectID": ".1.3.6.1.4.1.641.52.71107331",
            "snmpEngineID": "",
            "sysDescr": "Lexmark MC2425adw version CXNZJ.250.038 kernel 6.6.86-yocto-standard All-N-1",
            "sysContact": "me",
            "version": "CXNZJ.250.038",
            "hardware": "MC2425adw",
            "features": None,
            "location_id": 3,
            "os": "lexmarkprinter",
            "status": 1,
            "status_reason": "",
            "ignore": 0,
            "disabled": 0,
            "uptime": 15830868,
            "agent_uptime": 0,
            "last_polled": "2026-07-13 22:17:46",
            "last_poll_attempted": None,
            "last_polled_timetaken": 1.7405550479889,
            "last_discovered_timetaken": 2.7769849300385,
            "last_discovered": "2026-07-13 20:00:07",
            "last_ping": "2026-07-13 22:20:03",
            "last_ping_timetaken": 0.812,
            "purpose": "",
            "type": "printer",
            "serial": "7529936145YFW",
            "icon": "lexmark.svg",
            "poller_group": 0,
            "override_sysLocation": 0,
            "notes": None,
            "port_association_mode": 1,
            "max_depth": 0,
            "disable_notify": 1,
            "ignore_status": 0,
            "mtu_status": 1,
            "dependency_parent_id": None,
            "dependency_parent_hostname": None,
            "location": "Home",
            "lat": None,
            "lng": None,
        }
    ),
    LibrenmsDeviceInfo.from_dict(
        {
            "device_id": 13,
            "inserted": "2023-09-23 19:45:29",
            "hostname": "192.168.1.5",
            "sysName": "homeassistant",
            "display": "homeassistant",
            "display_template": None,
            "ip": "192.168.1.5",
            "overwrite_ip": "",
            "community": "read-only",
            "authlevel": None,
            "authname": None,
            "authpass": None,
            "authalgo": None,
            "cryptopass": None,
            "cryptoalgo": None,
            "snmpver": "v2c",
            "port": 161,
            "transport": "udp",
            "timeout": None,
            "retries": None,
            "snmp_disable": 0,
            "bgpLocalAs": None,
            "sysObjectID": ".1.3.6.1.4.1.8072.3.2.10",
            "snmpEngineID": "80 00 1F 88 80 E7 73 4D 32 ED 2A 54 6A 00 00 00 \n00",
            "sysDescr": "Linux homeassistant 6.18.37-haos #1 SMP PREEMPT_DYNAMIC Wed Jul  1 07:35:33 UTC 2026 x86_64 (Home Assistant OS 18.1)",
            "sysContact": "me",
            "version": "6.18.37-haos",
            "hardware": "QEMU Standard PC (i440FX + PIIX, 1996)",
            "features": "Home Assistant OS 18.1",
            "location_id": 4,
            "os": "linux",
            "status": 1,
            "status_reason": "",
            "ignore": 0,
            "disabled": 0,
            "uptime": 72931,
            "agent_uptime": 0,
            "last_polled": "2026-07-13 22:17:06",
            "last_poll_attempted": None,
            "last_polled_timetaken": 1.6433110237122,
            "last_discovered_timetaken": 2.8492691516876,
            "last_discovered": "2026-07-13 20:00:10",
            "last_ping": "2026-07-13 22:20:03",
            "last_ping_timetaken": 0.772,
            "purpose": "",
            "type": "server",
            "serial": None,
            "icon": "linux.svg",
            "poller_group": 0,
            "override_sysLocation": 1,
            "notes": None,
            "port_association_mode": 1,
            "max_depth": 2,
            "disable_notify": 0,
            "ignore_status": 0,
            "mtu_status": 1,
            "dependency_parent_id": "5",
            "dependency_parent_hostname": "192.168.100.2",
            "location": "Home",
            "lat": None,
            "lng": None,
        }
    ),
    LibrenmsDeviceInfo.from_dict(
        {
            "device_id": 1,
            "inserted": "2023-09-16 11:29:40",
            "hostname": "192.168.100.1",
            "sysName": "sophosxg",
            "display": "SophosXG",
            "display_template": "SophosXG",
            "ip": "192.168.100.1",
            "overwrite_ip": "",
            "community": "read-only",
            "authlevel": None,
            "authname": None,
            "authpass": None,
            "authalgo": None,
            "cryptopass": None,
            "cryptoalgo": None,
            "snmpver": "v2c",
            "port": 161,
            "transport": "udp",
            "timeout": None,
            "retries": None,
            "snmp_disable": 0,
            "bgpLocalAs": None,
            "sysObjectID": ".1.3.6.1.4.1.2604.5",
            "snmpEngineID": "80 00 1F 88 80 BD 17 B9 64 41 DA 99 64",
            "sysDescr": "Linux localhost 6.6.116 #1 SMP Fri Feb 27 22:12:13 CST 2026 x86_64",
            "sysContact": "me",
            "version": "22.0.1 MR-1-Build490",
            "hardware": "SFVH_KV01_SFOS",
            "features": None,
            "location_id": 1,
            "os": "sophos-xg",
            "status": 1,
            "status_reason": "",
            "ignore": 0,
            "disabled": 0,
            "uptime": 2592289,
            "agent_uptime": 0,
            "last_polled": "2026-07-13 22:19:47",
            "last_poll_attempted": None,
            "last_polled_timetaken": 1.6974771022797,
            "last_discovered_timetaken": 2.6829509735107,
            "last_discovered": "2026-07-13 20:00:04",
            "last_ping": "2026-07-13 22:20:03",
            "last_ping_timetaken": 0.149,
            "purpose": "",
            "type": "appliance",
            "serial": "C01yyyyyyxxxxxx",
            "icon": "sophos-xg.png",
            "poller_group": 0,
            "override_sysLocation": 0,
            "notes": None,
            "port_association_mode": 1,
            "max_depth": 2,
            "disable_notify": 0,
            "ignore_status": 0,
            "mtu_status": 1,
            "dependency_parent_id": "5",
            "dependency_parent_hostname": "192.168.100.2",
            "location": "Home",
            "lat": None,
            "lng": None,
        }
    ),
    LibrenmsDeviceInfo.from_dict(
        {
            "device_id": 29,
            "inserted": "2024-11-13 10:47:15",
            "hostname": "104.21.87.21",
            "sysName": "firmware.esphome.io (104.21.87.21)",
            "display": "firmware.esphome.io (104.21.87.21)",
            "display_template": None,
            "ip": "104.21.87.21",
            "overwrite_ip": None,
            "community": None,
            "authlevel": None,
            "authname": None,
            "authpass": None,
            "authalgo": None,
            "cryptopass": None,
            "cryptoalgo": None,
            "snmpver": "v2c",
            "port": 161,
            "transport": "udp",
            "timeout": None,
            "retries": None,
            "snmp_disable": 1,
            "bgpLocalAs": None,
            "sysObjectID": None,
            "snmpEngineID": None,
            "sysDescr": None,
            "sysContact": None,
            "version": None,
            "hardware": "",
            "features": None,
            "location_id": None,
            "os": "ping",
            "status": 1,
            "status_reason": "",
            "ignore": 0,
            "disabled": 0,
            "uptime": None,
            "agent_uptime": 0,
            "last_polled": "2026-07-13 22:18:41",
            "last_poll_attempted": None,
            "last_polled_timetaken": 1.1394469738007,
            "last_discovered_timetaken": 1.0503590106964,
            "last_discovered": "2026-07-13 20:00:29",
            "last_ping": "2026-07-13 22:20:03",
            "last_ping_timetaken": 95.6,
            "purpose": None,
            "type": "",
            "serial": None,
            "icon": None,
            "poller_group": 0,
            "override_sysLocation": 0,
            "notes": None,
            "port_association_mode": 1,
            "max_depth": 0,
            "disable_notify": 0,
            "ignore_status": 0,
            "mtu_status": 1,
            "dependency_parent_id": None,
            "dependency_parent_hostname": None,
            "location": None,
            "lat": None,
            "lng": None,
        }
    ),
]
