"""Test fixtures for the Workday component."""
from datetime import date
from typing import Any

from homeassistant.components.workday.const import (
    CONF_ADD_HOLIDAYS,
    CONF_EXCLUDES,
    CONF_OFFSET,
    CONF_PROVINCE,
    CONF_REMOVE_HOLIDAYS,
    CONF_WORKDAYS,
    DEFAULT_EXCLUDES,
    DEFAULT_OFFSET,
    DEFAULT_WORKDAYS,
)
from homeassistant.const import CONF_COUNTRY, CONF_NAME

ASSUMED_DATE = date(2023, 2, 14)

SENSOR_DATA: dict[str, Any] = {
    CONF_NAME: "Workday Sensor",
    CONF_COUNTRY: "CA",
}

USER_INPUT: dict[str, Any] = {
    CONF_PROVINCE: "NB",
    CONF_ADD_HOLIDAYS: "",
    CONF_REMOVE_HOLIDAYS: "",
    CONF_WORKDAYS: DEFAULT_WORKDAYS,
    CONF_EXCLUDES: DEFAULT_EXCLUDES,
    CONF_OFFSET: DEFAULT_OFFSET,
}

USER_INPUT_EXCLUDE_TODAY: dict[str, Any] = {
    CONF_PROVINCE: "NB",
    CONF_ADD_HOLIDAYS: "",
    CONF_REMOVE_HOLIDAYS: "",
    CONF_WORKDAYS: ["mon", "wed", "thu", "fri"],
    CONF_EXCLUDES: DEFAULT_EXCLUDES + ["tue"],
    CONF_OFFSET: DEFAULT_OFFSET,
}

USER_INPUT_EMPTY_PROVINCE: dict[str, Any] = {
    CONF_PROVINCE: "",
    CONF_ADD_HOLIDAYS: "",
    CONF_REMOVE_HOLIDAYS: "",
    CONF_WORKDAYS: DEFAULT_WORKDAYS,
    CONF_EXCLUDES: DEFAULT_EXCLUDES,
    CONF_OFFSET: DEFAULT_OFFSET,
}

USER_INPUT_INVALID_PROVINCE: dict[str, Any] = {
    CONF_PROVINCE: "invalid",
    CONF_ADD_HOLIDAYS: "",
    CONF_REMOVE_HOLIDAYS: "",
    CONF_WORKDAYS: DEFAULT_WORKDAYS,
    CONF_EXCLUDES: DEFAULT_EXCLUDES,
    CONF_OFFSET: DEFAULT_OFFSET,
}

USER_INPUT_ADD_HOLIDAY: dict[str, Any] = {
    CONF_PROVINCE: "NB",
    CONF_ADD_HOLIDAYS: "2023-02-14",
    CONF_REMOVE_HOLIDAYS: "",
    CONF_WORKDAYS: DEFAULT_WORKDAYS,
    CONF_EXCLUDES: DEFAULT_EXCLUDES,
    CONF_OFFSET: DEFAULT_OFFSET,
}

USER_INPUT_ADD_HOLIDAY_ONLY_INCLUDED: dict[str, Any] = {
    CONF_PROVINCE: "NB",
    CONF_ADD_HOLIDAYS: "2023-02-14",
    CONF_REMOVE_HOLIDAYS: "",
    CONF_WORKDAYS: ["holiday"],
    CONF_EXCLUDES: ["sat", "sun"],
    CONF_OFFSET: DEFAULT_OFFSET,
}

USER_INPUT_ADD_HOLIDAY_NO_WORKDAYS: dict[str, Any] = {
    CONF_PROVINCE: "NB",
    CONF_ADD_HOLIDAYS: "2023-02-14",
    CONF_REMOVE_HOLIDAYS: "",
    CONF_WORKDAYS: [],
    CONF_EXCLUDES: ["sat", "sun"],
    CONF_OFFSET: DEFAULT_OFFSET,
}

USER_INPUT_ADD_HOLIDAY_NOT_EXCLUDED: dict[str, Any] = {
    CONF_PROVINCE: "NB",
    CONF_ADD_HOLIDAYS: "2023-02-14",
    CONF_REMOVE_HOLIDAYS: "",
    CONF_WORKDAYS: DEFAULT_WORKDAYS,
    CONF_EXCLUDES: ["sat", "sun"],
    CONF_OFFSET: DEFAULT_OFFSET,
}

USER_INPUT_ADD_BAD_HOLIDAY: dict[str, Any] = {
    CONF_PROVINCE: "NB",
    CONF_ADD_HOLIDAYS: "My Birthday",
    CONF_REMOVE_HOLIDAYS: "",
    CONF_WORKDAYS: DEFAULT_WORKDAYS,
    CONF_EXCLUDES: DEFAULT_EXCLUDES,
    CONF_OFFSET: DEFAULT_OFFSET,
}

USER_INPUT_REMOVE_HOLIDAYS: dict[str, Any] = {
    CONF_PROVINCE: "NB",
    CONF_ADD_HOLIDAYS: "",
    CONF_REMOVE_HOLIDAYS: "2023-01-01,Christmas Day",
    CONF_WORKDAYS: DEFAULT_WORKDAYS,
    CONF_EXCLUDES: DEFAULT_EXCLUDES,
    CONF_OFFSET: DEFAULT_OFFSET,
}

USER_INPUT_REMOVE_NONEXISTENT_HOLIDAYS: dict[str, Any] = {
    CONF_PROVINCE: "NB",
    CONF_ADD_HOLIDAYS: "",
    CONF_REMOVE_HOLIDAYS: "No Such Holiday",
    CONF_WORKDAYS: DEFAULT_WORKDAYS,
    CONF_EXCLUDES: DEFAULT_EXCLUDES,
    CONF_OFFSET: DEFAULT_OFFSET,
}
