"""Constants for the Tesla Wall Connector integration."""

DOMAIN = "tesla_wall_connector"
DEFAULT_SCAN_INTERVAL = 30
DEFAULT_SPLIT_PHASE = False

CONF_SPLIT_PHASE = "split_phase"

WALLCONNECTOR_SERIAL_NUMBER = "serial_number"

WALLCONNECTOR_DATA_VITALS = "vitals"
WALLCONNECTOR_DATA_LIFETIME = "lifetime"
WALLCONNECTOR_DATA_WIFI_STATUS = "wifi_status"

WALLCONNECTOR_DEVICE_MANUFACTURER = "Tesla"
WALLCONNECTOR_DEVICE_MODEL = "Wall Connector"
WALLCONNECTOR_DEVICE_NAME = (
    f"{WALLCONNECTOR_DEVICE_MANUFACTURER} {WALLCONNECTOR_DEVICE_MODEL}"
)
