"""Test the ISEO Argo BLE config flow."""

from collections.abc import Generator
from unittest.mock import MagicMock, patch
import uuid

from iseo_argo_ble import IseoAuthError, IseoConnectionError
import pytest

from homeassistant import config_entries
from homeassistant.components.bluetooth import BluetoothServiceInfoBleak
from homeassistant.components.iseo_argo_ble import config_flow
from homeassistant.components.iseo_argo_ble.const import (
    CONF_ADMIN_PRIV_SCALAR,
    CONF_ADMIN_UUID,
    CONF_ENABLE_ADMIN,
    CONF_PRIV_SCALAR,
    DOMAIN,
)
from homeassistant.const import CONF_ADDRESS, CONF_UUID
from homeassistant.core import HomeAssistant
from homeassistant.data_entry_flow import FlowResultType
from homeassistant.helpers.device_registry import format_mac

from . import MOCK_ADDRESS, MOCK_ADMIN_UUID_HEX, MOCK_SERVICE_INFO, MOCK_UUID_HEX

from tests.common import MockConfigEntry

# hex() of the private scalars generated by the patched identities below. The
# gateway identity is generated first, the admin one second.
MOCK_GENERATED_PRIV_SCALAR = "0xbc614e"
MOCK_GENERATED_ADMIN_PRIV_SCALAR = "0xbc614f"

ENTRY_DATA_WITHOUT_ADMIN = {
    CONF_ADDRESS: MOCK_ADDRESS,
    CONF_UUID: MOCK_UUID_HEX,
    CONF_PRIV_SCALAR: MOCK_GENERATED_PRIV_SCALAR,
}
ENTRY_DATA_WITH_ADMIN = ENTRY_DATA_WITHOUT_ADMIN | {
    CONF_ADMIN_UUID: MOCK_ADMIN_UUID_HEX,
    CONF_ADMIN_PRIV_SCALAR: MOCK_GENERATED_ADMIN_PRIV_SCALAR,
}


@pytest.fixture
def _patch_identity() -> Generator[None]:
    """Patch identity generation to avoid real crypto in config flow tests."""
    gateway_priv = MagicMock()
    gateway_priv.private_numbers.return_value = MagicMock(private_value=12345678)
    admin_priv = MagicMock()
    admin_priv.private_numbers.return_value = MagicMock(private_value=12345679)
    with (
        patch(
            "homeassistant.components.iseo_argo_ble.config_flow._generate_identity",
            side_effect=[gateway_priv, admin_priv],
        ),
        patch(
            "homeassistant.components.iseo_argo_ble.config_flow.uuid_module.uuid4",
            side_effect=[
                uuid.UUID(MOCK_UUID_HEX),
                uuid.UUID(MOCK_ADMIN_UUID_HEX),
            ],
        ),
        patch(
            "homeassistant.components.iseo_argo_ble.config_flow.async_ble_device_from_address",
            return_value=MagicMock(),
        ),
    ):
        yield


@pytest.mark.parametrize(
    ("enable_admin", "expected_data", "expected_admin_uuid_bytes"),
    [
        pytest.param(
            True,
            ENTRY_DATA_WITH_ADMIN,
            bytes.fromhex(MOCK_ADMIN_UUID_HEX),
            id="user_management_enabled",
        ),
        pytest.param(
            False,
            ENTRY_DATA_WITHOUT_ADMIN,
            None,
            id="user_management_disabled",
        ),
    ],
)
@pytest.mark.usefixtures("_patch_identity")
async def test_bluetooth_discovery_confirm_and_register(
    hass: HomeAssistant,
    mock_iseo_client: MagicMock,
    enable_admin: bool,
    expected_data: dict[str, str],
    expected_admin_uuid_bytes: bytes | None,
) -> None:
    """Test full bluetooth discovery → confirm → gw_register flow."""
    with patch(
        "homeassistant.components.iseo_argo_ble.config_flow.is_iseo_advertisement",
        return_value=True,
    ):
        result = await hass.config_entries.flow.async_init(
            DOMAIN,
            context={"source": config_entries.SOURCE_BLUETOOTH},
            data=MOCK_SERVICE_INFO,
        )

    assert result["type"] is FlowResultType.FORM
    assert result["step_id"] == "bluetooth_confirm"

    # Confirm the lock
    result2 = await hass.config_entries.flow.async_configure(
        result["flow_id"], user_input={}
    )
    assert result2["type"] is FlowResultType.FORM
    assert result2["step_id"] == "gw_register"

    # Register gateway
    result3 = await hass.config_entries.flow.async_configure(
        result2["flow_id"], user_input={CONF_ENABLE_ADMIN: enable_admin}
    )

    assert result3["type"] is FlowResultType.CREATE_ENTRY
    assert result3["title"] == "ISEO Lock"
    assert result3["data"] == expected_data
    assert result3["result"].unique_id == format_mac(MOCK_ADDRESS)

    mock_iseo_client.setup_gateway.assert_called_once()
    call_kwargs = mock_iseo_client.setup_gateway.call_args.kwargs
    assert call_kwargs["admin_uuid_bytes"] == expected_admin_uuid_bytes
    assert (call_kwargs["admin_identity_priv"] is not None) is enable_admin


@pytest.mark.usefixtures("_patch_identity")
async def test_user_step_with_device(
    hass: HomeAssistant,
    mock_iseo_client: MagicMock,
) -> None:
    """Test user step shows discovered devices and allows selection."""
    with patch(
        "homeassistant.components.iseo_argo_ble.config_flow._discover_locks",
        return_value=[MOCK_SERVICE_INFO],
    ):
        result = await hass.config_entries.flow.async_init(
            DOMAIN,
            context={"source": config_entries.SOURCE_USER},
        )

    assert result["type"] is FlowResultType.FORM
    assert result["step_id"] == "user"

    # Select the device
    result2 = await hass.config_entries.flow.async_configure(
        result["flow_id"],
        user_input={CONF_ADDRESS: MOCK_ADDRESS},
    )
    assert result2["type"] is FlowResultType.FORM
    assert result2["step_id"] == "gw_register"

    # Register gateway
    result3 = await hass.config_entries.flow.async_configure(
        result2["flow_id"], user_input={CONF_ENABLE_ADMIN: False}
    )

    assert result3["type"] is FlowResultType.CREATE_ENTRY
    assert result3["title"] == "ISEO Lock"
    assert result3["data"] == ENTRY_DATA_WITHOUT_ADMIN
    assert result3["result"].unique_id == format_mac(MOCK_ADDRESS)
    mock_iseo_client.setup_gateway.assert_called_once()


async def test_bluetooth_discovery_abort_if_already_configured(
    hass: HomeAssistant,
    mock_config_entry: MockConfigEntry,
) -> None:
    """Test bluetooth discovery aborts for already-configured locks."""
    mock_config_entry.add_to_hass(hass)

    result = await hass.config_entries.flow.async_init(
        DOMAIN,
        context={"source": config_entries.SOURCE_BLUETOOTH},
        data=MOCK_SERVICE_INFO,
    )
    assert result["type"] is FlowResultType.ABORT
    assert result["reason"] == "already_configured"


async def test_bluetooth_discovery_not_iseo(hass: HomeAssistant) -> None:
    """Test bluetooth discovery aborts for non-ISEO devices."""
    non_iseo_info = BluetoothServiceInfoBleak(
        name="SomeOtherDevice",
        address="11:22:33:44:55:66",
        rssi=-70,
        manufacturer_data={},
        service_data={},
        service_uuids=["0000180f-0000-1000-8000-00805f9b34fb"],  # not ISEO
        source="local",
        device=MagicMock(),
        advertisement=MagicMock(),
        connectable=True,
        time=0,
        tx_power=None,
    )

    with patch(
        "homeassistant.components.iseo_argo_ble.config_flow.is_iseo_advertisement",
        return_value=False,
    ):
        result = await hass.config_entries.flow.async_init(
            DOMAIN,
            context={"source": config_entries.SOURCE_BLUETOOTH},
            data=non_iseo_info,
        )
    assert result["type"] is FlowResultType.ABORT
    assert result["reason"] == "not_iseo_device"


async def test_user_step_no_devices(hass: HomeAssistant) -> None:
    """Test user step aborts when no ISEO locks found nearby."""
    with patch(
        "homeassistant.components.iseo_argo_ble.config_flow._discover_locks",
        return_value=[],
    ):
        result = await hass.config_entries.flow.async_init(
            DOMAIN,
            context={"source": config_entries.SOURCE_USER},
        )

    assert result["type"] is FlowResultType.ABORT
    assert result["reason"] == "no_devices_found"


@pytest.mark.usefixtures("_patch_identity")
async def test_gw_register_retry_after_failure_drops_admin_identity(
    hass: HomeAssistant,
    mock_iseo_client: MagicMock,
) -> None:
    """Test a retry without user management does not keep the admin identity.

    The first attempt generates one, but the lock never enrolled it, so it must
    not end up in the config entry.
    """
    mock_iseo_client.setup_gateway.side_effect = [IseoConnectionError, None]

    with patch(
        "homeassistant.components.iseo_argo_ble.config_flow.is_iseo_advertisement",
        return_value=True,
    ):
        result = await hass.config_entries.flow.async_init(
            DOMAIN,
            context={"source": config_entries.SOURCE_BLUETOOTH},
            data=MOCK_SERVICE_INFO,
        )

    result2 = await hass.config_entries.flow.async_configure(
        result["flow_id"], user_input={}
    )
    result3 = await hass.config_entries.flow.async_configure(
        result2["flow_id"], user_input={CONF_ENABLE_ADMIN: True}
    )
    assert result3["type"] is FlowResultType.FORM
    assert result3["errors"] == {"base": "cannot_connect"}

    result4 = await hass.config_entries.flow.async_configure(
        result3["flow_id"], user_input={CONF_ENABLE_ADMIN: False}
    )

    assert result4["type"] is FlowResultType.CREATE_ENTRY
    assert result4["data"] == ENTRY_DATA_WITHOUT_ADMIN


@pytest.mark.usefixtures("_patch_identity")
async def test_gw_register_connection_error(
    hass: HomeAssistant,
    mock_iseo_client: MagicMock,
) -> None:
    """Test gw_register handles connection error."""
    mock_iseo_client.setup_gateway.side_effect = IseoConnectionError

    with patch(
        "homeassistant.components.iseo_argo_ble.config_flow.is_iseo_advertisement",
        return_value=True,
    ):
        result = await hass.config_entries.flow.async_init(
            DOMAIN,
            context={"source": config_entries.SOURCE_BLUETOOTH},
            data=MOCK_SERVICE_INFO,
        )

    # Move to gw_register
    result2 = await hass.config_entries.flow.async_configure(
        result["flow_id"], user_input={}
    )
    assert result2["step_id"] == "gw_register"

    result3 = await hass.config_entries.flow.async_configure(
        result2["flow_id"], user_input={}
    )

    assert result3["type"] is FlowResultType.FORM
    assert result3["errors"] == {"base": "cannot_connect"}


@pytest.mark.usefixtures("_patch_identity")
async def test_gw_register_auth_error(
    hass: HomeAssistant,
    mock_iseo_client: MagicMock,
) -> None:
    """Test gw_register handles auth error."""
    mock_iseo_client.setup_gateway.side_effect = IseoAuthError

    with patch(
        "homeassistant.components.iseo_argo_ble.config_flow.is_iseo_advertisement",
        return_value=True,
    ):
        result = await hass.config_entries.flow.async_init(
            DOMAIN,
            context={"source": config_entries.SOURCE_BLUETOOTH},
            data=MOCK_SERVICE_INFO,
        )

    # Move to gw_register
    result2 = await hass.config_entries.flow.async_configure(
        result["flow_id"], user_input={}
    )
    assert result2["step_id"] == "gw_register"

    result3 = await hass.config_entries.flow.async_configure(
        result2["flow_id"], user_input={}
    )

    assert result3["type"] is FlowResultType.FORM
    assert result3["errors"] == {"base": "auth_failed"}


@pytest.mark.usefixtures("_patch_identity")
async def test_gw_register_no_ble_device(
    hass: HomeAssistant,
) -> None:
    """Test gw_register handles case where ble_device is None."""
    with patch(
        "homeassistant.components.iseo_argo_ble.config_flow.is_iseo_advertisement",
        return_value=True,
    ):
        result = await hass.config_entries.flow.async_init(
            DOMAIN,
            context={"source": config_entries.SOURCE_BLUETOOTH},
            data=MOCK_SERVICE_INFO,
        )

    # Move to gw_register
    result2 = await hass.config_entries.flow.async_configure(
        result["flow_id"], user_input={}
    )
    assert result2["step_id"] == "gw_register"

    with patch(
        "homeassistant.components.iseo_argo_ble.config_flow.async_ble_device_from_address",
        return_value=None,
    ):
        result3 = await hass.config_entries.flow.async_configure(
            result2["flow_id"], user_input={}
        )

    assert result3["type"] is FlowResultType.FORM
    assert result3["errors"] == {"base": "cannot_connect"}


@pytest.mark.usefixtures("_patch_identity")
async def test_gw_register_unknown_error(
    hass: HomeAssistant,
    mock_iseo_client: MagicMock,
) -> None:
    """Test gw_register handles unknown error."""
    mock_iseo_client.setup_gateway.side_effect = Exception("BOOM")

    with patch(
        "homeassistant.components.iseo_argo_ble.config_flow.is_iseo_advertisement",
        return_value=True,
    ):
        result = await hass.config_entries.flow.async_init(
            DOMAIN,
            context={"source": config_entries.SOURCE_BLUETOOTH},
            data=MOCK_SERVICE_INFO,
        )

    # Move to gw_register
    result2 = await hass.config_entries.flow.async_configure(
        result["flow_id"], user_input={}
    )
    assert result2["step_id"] == "gw_register"

    result3 = await hass.config_entries.flow.async_configure(
        result2["flow_id"], user_input={}
    )

    assert result3["type"] is FlowResultType.FORM
    assert result3["errors"] == {"base": "unknown"}


async def test_discover_locks(hass: HomeAssistant) -> None:
    """Test the _discover_locks helper function."""
    non_iseo_info = BluetoothServiceInfoBleak(
        name="Other",
        address="11:22:33:44:55:66",
        rssi=-70,
        manufacturer_data={},
        service_data={},
        service_uuids=[],
        source="local",
        device=MagicMock(),
        advertisement=MagicMock(),
        connectable=True,
        time=0,
        tx_power=None,
    )
    with patch(
        "homeassistant.components.iseo_argo_ble.config_flow.async_discovered_service_info",
        return_value=[MOCK_SERVICE_INFO, non_iseo_info],
    ):
        found = config_flow._discover_locks(hass)

    assert len(found) == 1
    assert found[0].address == MOCK_ADDRESS


async def test_generate_identity() -> None:
    """Test the _generate_identity helper function."""
    priv = config_flow._generate_identity()
    assert priv is not None
    # SECP224R1 is 224 bits
    assert priv.key_size == 224
