"""Constants for action/service checkers."""

from pylint_home_assistant.const import Platform

# Entity action methods per platform. Includes both the handler names
# registered via async_register_entity_service AND the entity methods
# those handlers delegate to (which integrations override).
PLATFORM_ACTION_METHODS: dict[str, set[str]] = {
    Platform.ALARM_CONTROL_PANEL: {
        "alarm_arm_away",
        "alarm_arm_custom_bypass",
        "alarm_arm_home",
        "alarm_arm_night",
        "alarm_arm_vacation",
        "alarm_disarm",
        "alarm_trigger",
        "async_alarm_arm_away",
        "async_alarm_arm_custom_bypass",
        "async_alarm_arm_home",
        "async_alarm_arm_night",
        "async_alarm_arm_vacation",
        "async_alarm_disarm",
        "async_alarm_trigger",
    },
    Platform.ASSIST_SATELLITE: {
        "async_announce",
        "async_start_conversation",
    },
    Platform.BUTTON: {
        "async_press",
        "press",
    },
    Platform.CALENDAR: {
        "async_create_event",
        "async_delete_event",
        "async_get_events",
        "async_update_event",
    },
    Platform.CAMERA: {
        "async_camera_image",
        "async_disable_motion_detection",
        "async_enable_motion_detection",
        "async_turn_off",
        "async_turn_on",
        "camera_image",
        "disable_motion_detection",
        "enable_motion_detection",
        "turn_off",
        "turn_on",
    },
    Platform.CLIMATE: {
        "async_set_fan_mode",
        "async_set_humidity",
        "async_set_hvac_mode",
        "async_set_preset_mode",
        "async_set_swing_horizontal_mode",
        "async_set_swing_mode",
        "async_set_temperature",
        "async_toggle",
        "async_turn_off",
        "async_turn_on",
        "set_fan_mode",
        "set_humidity",
        "set_hvac_mode",
        "set_preset_mode",
        "set_swing_horizontal_mode",
        "set_swing_mode",
        "set_temperature",
        "toggle",
        "turn_off",
        "turn_on",
    },
    Platform.COVER: {
        "async_close_cover_tilt",
        "async_close_cover",
        "async_open_cover_tilt",
        "async_open_cover",
        "async_set_cover_position",
        "async_set_cover_tilt_position",
        "async_stop_cover_tilt",
        "async_stop_cover",
        "async_toggle_tilt",
        "async_toggle",
        "close_cover_tilt",
        "close_cover",
        "open_cover_tilt",
        "open_cover",
        "set_cover_position",
        "set_cover_tilt_position",
        "stop_cover_tilt",
        "stop_cover",
        "toggle_tilt",
        "toggle",
    },
    Platform.DATE: {
        "async_set_value",
        "set_value",
    },
    Platform.DATETIME: {
        "async_set_value",
        "set_value",
    },
    Platform.FAN: {
        "async_decrease_speed",
        "async_handle_set_preset_mode_service",
        "async_handle_turn_on_service",
        "async_increase_speed",
        "async_oscillate",
        "async_set_direction",
        "async_set_percentage",
        "async_set_preset_mode",
        "async_toggle",
        "async_turn_off",
        "async_turn_on",
        "decrease_speed",
        "increase_speed",
        "oscillate",
        "set_direction",
        "set_percentage",
        "set_preset_mode",
        "toggle",
        "turn_off",
        "turn_on",
    },
    Platform.HUMIDIFIER: {
        "async_service_humidity_set",
        "async_set_humidity",
        "async_set_mode",
        "async_toggle",
        "async_turn_off",
        "async_turn_on",
        "set_humidity",
        "set_mode",
        "toggle",
        "turn_off",
        "turn_on",
    },
    Platform.IMAGE: {
        "async_image",
        "image",
    },
    Platform.LAWN_MOWER: {
        "async_dock",
        "async_pause",
        "async_start_mowing",
        "dock",
        "pause",
        "start_mowing",
    },
    Platform.LIGHT: {
        "async_toggle",
        "async_turn_off",
        "async_turn_on",
        "toggle",
        "turn_off",
        "turn_on",
    },
    Platform.LOCK: {
        "async_lock",
        "async_open",
        "async_unlock",
        "lock",
        "open",
        "unlock",
    },
    Platform.MEDIA_PLAYER: {
        "async_browse_media",
        "async_clear_playlist",
        "async_join_players",
        "async_media_next_track",
        "async_media_pause",
        "async_media_play_pause",
        "async_media_play",
        "async_media_previous_track",
        "async_media_seek",
        "async_media_stop",
        "async_mute_volume",
        "async_play_media",
        "async_search_media",
        "async_select_sound_mode",
        "async_select_source",
        "async_set_repeat",
        "async_set_shuffle",
        "async_set_volume_level",
        "async_toggle",
        "async_turn_off",
        "async_turn_on",
        "async_unjoin_player",
        "async_volume_down",
        "async_volume_up",
        "clear_playlist",
        "join_players",
        "media_next_track",
        "media_pause",
        "media_play",
        "media_previous_track",
        "media_seek",
        "media_stop",
        "mute_volume",
        "play_media",
        "select_sound_mode",
        "select_source",
        "set_repeat",
        "set_shuffle",
        "set_volume_level",
        "turn_off",
        "turn_on",
        "unjoin_player",
    },
    Platform.NOTIFY: {
        "async_send_message",
        "send_message",
    },
    Platform.NUMBER: {
        "async_set_native_value",
        "async_set_value",
        "set_native_value",
        "set_value",
    },
    Platform.REMOTE: {
        "async_delete_command",
        "async_learn_command",
        "async_send_command",
        "async_toggle",
        "async_turn_off",
        "async_turn_on",
        "delete_command",
        "learn_command",
        "send_command",
        "toggle",
        "turn_off",
        "turn_on",
    },
    Platform.SCENE: {
        "activate",
        "async_activate",
    },
    Platform.SELECT: {
        "async_select_option",
        "select_option",
    },
    Platform.SIREN: {
        "async_toggle",
        "async_turn_off",
        "async_turn_on",
        "toggle",
        "turn_off",
        "turn_on",
    },
    Platform.SWITCH: {
        "async_toggle",
        "async_turn_off",
        "async_turn_on",
        "toggle",
        "turn_off",
        "turn_on",
    },
    Platform.TEXT: {
        "async_set_value",
        "set_value",
    },
    Platform.TIME: {
        "async_set_value",
        "set_value",
    },
    Platform.TODO: {
        "async_create_todo_item",
        "async_delete_todo_items",
        "async_update_todo_item",
    },
    Platform.TTS: {
        "async_clear_cache",
        "async_speak",
    },
    Platform.UPDATE: {
        "async_install",
        "install",
    },
    Platform.VACUUM: {
        "async_clean_segments",
        "async_clean_spot",
        "async_locate",
        "async_pause",
        "async_return_to_base",
        "async_send_command",
        "async_set_fan_speed",
        "async_start",
        "async_stop",
        "clean_segments",
        "clean_spot",
        "locate",
        "pause",
        "return_to_base",
        "send_command",
        "set_fan_speed",
        "start",
        "stop",
    },
    Platform.VALVE: {
        "async_close_valve",
        "async_open_valve",
        "async_set_valve_position",
        "async_stop_valve",
        "async_toggle",
        "close_valve",
        "open_valve",
        "set_valve_position",
        "stop_valve",
        "toggle",
    },
    Platform.WATER_HEATER: {
        "async_set_operating_mode",
        "async_set_temperature",
        "async_turn_away_mode_off",
        "async_turn_away_mode_on",
        "async_turn_off",
        "async_turn_on",
        "set_operating_mode",
        "set_temperature",
        "turn_away_mode_off",
        "turn_away_mode_on",
        "turn_off",
        "turn_on",
    },
}
