# Fritz!Box VPN services

remove_unavailable_entities:
  target:
    entity:
      integration: fritzbox_vpn
  fields:
    config_entry_id:
      required: false
      selector:
        text:

repair_entity_id_suffixes:
  target:
    entity:
      integration: fritzbox_vpn
  fields:
    config_entry_id:
      required: false
      selector:
        text:
