"""Constants for Tibber integration."""

DATA_HASS_CONFIG = "tibber_hass_config"
DOMAIN = "tibber"
MANUFACTURER = "Tibber"

# Price interval options
PRICE_INTERVAL_HOURLY = "hourly"
PRICE_INTERVAL_15MIN = "15min"
DEFAULT_PRICE_INTERVAL = PRICE_INTERVAL_HOURLY

# Update interval constants (in minutes)
UPDATE_INTERVAL_15MIN = 15
UPDATE_INTERVAL_HOURLY = 60
UPDATE_INTERVAL_MAPPING = {
    PRICE_INTERVAL_15MIN: UPDATE_INTERVAL_15MIN,
    PRICE_INTERVAL_HOURLY: UPDATE_INTERVAL_HOURLY,
}
