generate_text:
  fields:
    task_name:
      example: "home summary"
      required: true
      selector:
        text:
    task_type:
      required: true
      default: "summary"
      selector:
        select:
          options:
            - "summary"
            - "generate"
    prompt:
      example: "Funny notification that garage door left open"
      required: true
    entity_id:
      required: false
      selector:
        entity:
          domain: llm_task
