# Support for (EMEA/EU-based) Honeywell TCC climate systems.
# Describes the format for available services

set_system_mode:
  fields:
    mode:
      required: true
      default: Auto
      example: Away
      selector:
        select:
          options:
            - "Auto"
            - "AutoWithEco"
            - "Away"
            - "Custom"
            - "DayOff"
            - "HeatingOff"
    period:
      example: '{"days": 28}'
      selector:
        object:
    duration:
      example: "18:00"
      selector:
        duration:
          enable_second: false

reset_system:

refresh_system:

set_zone_override:
  target:
    entity:
      integration: evohome
      domain: climate
      supported_features:
        - climate.ClimateEntityFeature.TARGET_TEMPERATURE
  fields:
    setpoint:
      required: true
      selector:
        number:
          min: 4.0
          max: 35.0
          step: 0.1
    duration:
      example: "02:15"
      selector:
        duration:
          enable_second: false

clear_zone_override:
  target:
    entity:
      integration: evohome
      domain: climate
      supported_features:
        - climate.ClimateEntityFeature.TARGET_TEMPERATURE

set_dhw_override:
  target:
    entity:
      integration: evohome
      domain: water_heater
  fields:
    state:
      required: true
      selector:
        boolean:
    duration:
      example: "02:15"
      selector:
        duration:
          enable_second: false
