get_description:
  target:
    entity:
      domain: binary_sensor
      integration: nina

get_affected_areas:
  target:
    entity:
      domain: binary_sensor
      integration: nina

get_recommended_actions:
  target:
    entity:
      domain: binary_sensor
      integration: nina
