"""FSV setting labels for Samsung EHS devices."""

FSV_LABEL_MAP = {
    "1021": "Target room temperature, Upper limit",
    "1022": "Target room temperature, Lower limit",
    "1031": "Target Water Outlet Upper Limit (Heating)",
    "1032": "Target Water Outlet Lower Limit (Heating)",
    "1051": "Maximum DHW Tank Temperature (User Limit)",
    "1052": "Target DHW Tank Temperature Lower Limit (User Limit)",
    "2011": "Water Law: Low Ambient Outdoor Temp Setpoint",
    "2012": "Water Law: High Ambient Outdoor Temp Setpoint",
    "2021": "Water Law: Flow Temp at Low Ambient (Zone 1)",
    "2022": "Water Law: Flow Temp at High Ambient (Zone 1)",
    "2031": "Water Law: Flow Temp at Low Ambient (Zone 2)",
    "2032": "Water Law: Flow Temp at High Ambient (Zone 2)",
    "2091": "External Run Input for Zone 1 (3rd Party Thermostat)",
    "2092": "External Run Input for Zone 2 (3rd Party Thermostat)",
    "2093": "Remote Controller Room Temp Control (Internal Sensor)",
    "3011": "Enable / Disable DHW Tank Function",
    "3021": "Maximum DHW tank temperature (Heat Pump limit)",
    "3022": "DHW Hysteresis: Temperature difference (HP OFF)",
    "3023": "DHW Hysteresis: Temperature difference (HP ON)",
    "3025": "Max. cylinder heating time (HP vs Space Heating)",
    "3031": "DHW Hysteresis Thermo On/Off",
    "3032": "Max. cylinder heating time (HP before Booster assist)",
    "3041": "Anti-Legionella function (Enable)",
    "3042": "Anti-Legionella Function Day",
    "3043": "Anti-Legionella Function Start Time",
    "3044": "Anti-Legionella Function Target Temperature",
    "3045": "Anti-Legionella Function Hold Time",
    "3051": "Hotwater Boost Function (Enable)",
    "3052": "Hotwater Boost Timer duration",
    "3071": "3-Way Valve Direction (0=Room Default, 1=Tank)",
    "3081": "Back Up Heater (1st Step)",
    "3082": "Back Up Heater (2nd Step)",
    "3083": "Booster Heater Capacity (kW rating)",
    "4011": "DHW / Space Heating Priority Setting",
    "4012": "Outdoor temperature for priority changeover",
    "4021": "Backup Heater Application (Enable/Disable)",
    "4041": "Mixing Valve Control (Enable)",
    "4042": "Mixing Valve Target Temperature Difference (Heating)",
    "4051": "Inverter Pump Control (Application / Enable)",
    "4052": "Inverter Pump Control (Target DeltaT)",
    "4053": "Inverter Pump Control (Control Factor / Gain)",
    "4054": "Inverter Pump Control (PWM Minimum Output)",
    "4061": "2-Zone Control (Application / Enable)",
    "5021": "DHW Saving Mode",
    "5051": "FR Control (Frequency Ratio / Compressor Limit)",
    "5081": "PV Control (Photovoltaics) Activation",
    "5083": "PV Control (Heating Setpoint Addition)",
    "5091": "Smart Grid Control",
}
