"""Constants for the Control4 integration."""

DOMAIN = "control4"

UPDATE_INTERVAL = 10
DEFAULT_SCAN_INTERVAL = 10
MIN_SCAN_INTERVAL = 1

CONF_LIGHT_TRANSITION_TIME = "light_transition_time"
CONF_LIGHT_COLD_START_TRANSITION_TIME = "light_cold_start_transition_time"
DEFAULT_LIGHT_TRANSITION_TIME = 0
DEFAULT_LIGHT_COLD_START_TRANSITION_TIME = 3

CONF_CONTROLLER_NAME = "controller_name"
