send_message:
  fields:
    config_entry_id:
      required: false
      selector:
        config_entry:
          integration: threema
    recipient:
      required: true
      selector:
        text:
    message:
      required: true
      selector:
        text:
          multiline: true
