get_forecast:
  target:
    entity:
      domain: weather
      supported_features:
        - weather.WeatherEntityFeature.FORECAST_DAILY
        - weather.WeatherEntityFeature.FORECAST_HOURLY
        - weather.WeatherEntityFeature.FORECAST_TWICE_DAILY
        - weather.WeatherEntityFeature.FORECAST_MINUTELY
  fields:
    type:
      required: true
      selector:
        select:
          options:
            - "daily"
            - "hourly"
            - "twice_daily"
            - "minutely"
          translation_key: forecast_type
get_forecasts:
  target:
    entity:
      domain: weather
      supported_features:
        - weather.WeatherEntityFeature.FORECAST_DAILY
        - weather.WeatherEntityFeature.FORECAST_HOURLY
        - weather.WeatherEntityFeature.FORECAST_TWICE_DAILY
        - weather.WeatherEntityFeature.FORECAST_MINUTELY
  fields:
    type:
      required: true
      selector:
        select:
          options:
            - "daily"
            - "hourly"
            - "twice_daily"
            - "minutely"
          translation_key: forecast_type
