"""Constants for the Yamaha component."""

DOMAIN = "yamaha"
DISCOVERY_STORE = "disco_store"
DISCOVERY_STORE_VERSION = 1
DISCOVERY_STORE_KEY = f"{DOMAIN}.discovery"
KNOWN_ZONES = "known_zones"
CURSOR_TYPE_DOWN = "down"
CURSOR_TYPE_LEFT = "left"
CURSOR_TYPE_RETURN = "return"
CURSOR_TYPE_RIGHT = "right"
CURSOR_TYPE_SELECT = "select"
CURSOR_TYPE_UP = "up"
CONF_SERIAL = "serial_number"
SERVICE_ENABLE_OUTPUT = "enable_output"
SERVICE_MENU_CURSOR = "menu_cursor"
SERVICE_SELECT_SCENE = "select_scene"
