"""Consts for AWS S3 tests."""

from homeassistant.components.aws_s3.const import (
    CONF_ACCESS_KEY_ID,
    CONF_AUTH_MODE,
    CONF_AUTH_MODE_EXPLICIT,
    CONF_AUTH_MODE_IMPLICIT,
    CONF_BUCKET,
    CONF_ENDPOINT_URL,
    CONF_SECRET_ACCESS_KEY,
)

TEST_VALID = "valid"
TEST_EMPTY = "empty"
TEST_INVALID = "invalid"

TEST_ACCESS_KEY_ID = {
    TEST_VALID: "TestTestTestTestTest",
    TEST_EMPTY: None,
}

TEST_SECRET_ACCESS_KEY = {
    TEST_VALID: "TestTestTestTestTestTestTestTestTestTest",
    TEST_EMPTY: None,
}

TEST_BUCKET = {
    TEST_VALID: "test",
    TEST_EMPTY: None,
    TEST_INVALID: "***InvalidBucket***",
}

TEST_ENDPOINT_URL = {
    TEST_VALID: "https://s3.eu-south-1.amazonaws.com",
    TEST_EMPTY: None,
    TEST_INVALID: "https://www.example.com",
}

USER_INPUT = {
    CONF_ACCESS_KEY_ID: TEST_ACCESS_KEY_ID[TEST_VALID],
    CONF_SECRET_ACCESS_KEY: TEST_SECRET_ACCESS_KEY[TEST_VALID],
    CONF_ENDPOINT_URL: TEST_ENDPOINT_URL[TEST_VALID],
    CONF_BUCKET: TEST_BUCKET[TEST_VALID],
}

USER_INPUT_VALID_IMPLICIT = {
    CONF_ACCESS_KEY_ID: TEST_ACCESS_KEY_ID[TEST_EMPTY],
    CONF_SECRET_ACCESS_KEY: TEST_SECRET_ACCESS_KEY[TEST_EMPTY],
    CONF_ENDPOINT_URL: TEST_ENDPOINT_URL[TEST_VALID],
    CONF_BUCKET: TEST_BUCKET[TEST_VALID],
    CONF_AUTH_MODE: CONF_AUTH_MODE_IMPLICIT,
}

USER_INPUT_VALID_EXPLICIT = {
    CONF_ACCESS_KEY_ID: TEST_ACCESS_KEY_ID[TEST_VALID],
    CONF_SECRET_ACCESS_KEY: TEST_SECRET_ACCESS_KEY[TEST_VALID],
    CONF_ENDPOINT_URL: TEST_ENDPOINT_URL[TEST_VALID],
    CONF_BUCKET: TEST_BUCKET[TEST_VALID],
    CONF_AUTH_MODE: CONF_AUTH_MODE_EXPLICIT,
}

USER_INPUT_VALID_IMPLICIT_NO_MODE = USER_INPUT_VALID_IMPLICIT | {CONF_AUTH_MODE: None}
USER_INPUT_VALID_EXPLICIT_NO_MODE = USER_INPUT_VALID_EXPLICIT | {CONF_AUTH_MODE: None}
