"""Constants for the WittIOT integration."""

DOMAIN = "wittiot"
LOCAL = "Local"
CONNECTION_TYPE = "connection_type"
DEVICE_NAME = "Device"
MAIN_DATA = "Main Data"
PM25_DATA = "Multi_CH PM25"
LEAK_DATA = "Multi_CH Leak"
SOIL_DATA = "Multi_CH Soil"
TEMPHUMI_DATA = "Multi_CH Temp&Humi"
TEMP_DATA = "Multi_CH Temp"
LEAF_DATA = "Multi_CH Leaf"
PM25_BATT = "PM25 Battery"
LEAK_BATT = "Leak Battery"
SOIL_BATT = "Soil Battery"
TEMPHUMI_BATT = "Temp&Humi Battery"
TEMP_BATT = "Temp Battery"
LEAF_BATT = "Leaf Battery"
