# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "debian/contrib-stretch64"
  config.vm.synced_folder "../../", "/home-assistant"
  config.vm.synced_folder "./config", "/root/.homeassistant"
  config.vm.network "forwarded_port", guest: 8123, host: 8123
  config.vm.provision "fix-no-tty", type: "shell" do |shell|
    shell.path = "provision.sh"
  end
  config.vm.provider :virtualbox do |vb|
    vb.cpus = 2
    vb.customize ['modifyvm', :id, '--memory', '1024']
  end
  config.vm.provider :hyperv do |h, override|
    override.vm.box = "generic/debian9"
    override.vm.hostname = "contrib-stretch"
    h.vmname = "home-assistant"
    h.cpus = 2
    h.memory = 1024
    h.maxmemory = 1024
  end
end
