"""Constants for the Luxtronik integration."""

ATTR_PARAMETER = "parameter"
ATTR_VALUE = "value"

CONF_INVERT_STATE = "invert"
CONF_SAFE = "safe"
CONF_GROUP = "group"
CONF_PARAMETERS = "parameters"
CONF_CALCULATIONS = "calculations"
CONF_VISIBILITIES = "visibilities"
CONF_CELSIUS = "celsius"
CONF_SECONDS = "seconds"
CONF_TIMESTAMP = "timestamp"
CONF_KELVIN = "kelvin"
CONF_BAR = "bar"
CONF_PERCENT = "percent"
CONF_ENERGY = "energy"
CONF_VOLTAGE = "voltage"
CONF_HOURS = "hours"
CONF_FLOW = "flow"

TIME_SECONDS = "s"
TIME_HOUR = "h"
TEMP_KELVIN = "K"
PERCENTAGE_PERCENT = "%"
VOLTAGE_VOLT = "V"
FLOW_LITERS_PER_MINUTE = "l/min"
