config_entry:
  versions:
    - version:
        major: 1
        minor: 1
      data:
        fields:
          2fa:
            required: true
            selector:
              text: {}
          device_name:
            required: false
            selector:
              text: {}
      options:
        fields:
          scan_interval:
            required: false
            selector:
              text: {}
  subentries: {}
