"""Validate Yardian binary sensor behavior."""

from unittest.mock import AsyncMock, patch

from freezegun.api import FrozenDateTimeFactory
import pytest
from syrupy.assertion import SnapshotAssertion

from homeassistant.components.yardian.const import DOMAIN
from homeassistant.components.yardian.coordinator import SCAN_INTERVAL
from homeassistant.const import STATE_OFF, STATE_ON, Platform
from homeassistant.core import HomeAssistant
from homeassistant.helpers import entity_registry as er
from homeassistant.util import dt as dt_util

from . import setup_integration

from tests.common import MockConfigEntry, async_fire_time_changed, snapshot_platform


@pytest.mark.usefixtures("entity_registry_enabled_by_default")
async def test_all_entities(
    hass: HomeAssistant,
    snapshot: SnapshotAssertion,
    mock_yardian_client: AsyncMock,
    mock_config_entry: MockConfigEntry,
    entity_registry: er.EntityRegistry,
) -> None:
    """Test all entities."""
    with patch("homeassistant.components.yardian.PLATFORMS", [Platform.BINARY_SENSOR]):
        await setup_integration(hass, mock_config_entry)

    await snapshot_platform(hass, entity_registry, snapshot, mock_config_entry.entry_id)


async def test_disabled_by_default_sensors(
    hass: HomeAssistant,
    mock_yardian_client: AsyncMock,
    mock_config_entry: MockConfigEntry,
    entity_registry: er.EntityRegistry,
) -> None:
    """Ensure specific binary sensors remain disabled by default."""
    await setup_integration(hass, mock_config_entry)

    # 1. Check Freeze Prevention sensor
    freeze_entity_id = entity_registry.async_get_entity_id(
        "binary_sensor", DOMAIN, f"{mock_config_entry.unique_id}-freeze_prevent"
    )
    assert freeze_entity_id is not None
    freeze_entry = entity_registry.async_get(freeze_entity_id)
    assert freeze_entry is not None
    assert freeze_entry.disabled
    assert freeze_entry.disabled_by is er.RegistryEntryDisabler.INTEGRATION

    # 2. Check all per-zone enabled sensors
    for idx in range(2):
        entity_id = entity_registry.async_get_entity_id(
            "binary_sensor", DOMAIN, f"{mock_config_entry.unique_id}-zone_enabled_{idx}"
        )
        assert entity_id is not None
        entity_entry = entity_registry.async_get(entity_id)
        assert entity_entry is not None
        assert entity_entry.disabled
        assert entity_entry.disabled_by is er.RegistryEntryDisabler.INTEGRATION


async def test_standby_sensor_edge_cases(
    hass: HomeAssistant,
    mock_yardian_client: AsyncMock,
    mock_config_entry: MockConfigEntry,
    entity_registry: er.EntityRegistry,
    freezer: FrozenDateTimeFactory,
) -> None:
    """Test standby binary sensor with future timestamps and missing data."""
    await setup_integration(hass, mock_config_entry)

    # Find the specific standby entity ID generated by HA
    entity_id = entity_registry.async_get_entity_id(
        "binary_sensor", DOMAIN, f"{mock_config_entry.unique_id}-standby"
    )
    assert entity_id is not None

    now = dt_util.utcnow()
    freezer.move_to(now)
    future_ts = int(now.timestamp()) + 3600

    # 1. Test Future Timestamp (Should be ON)
    new_oper_info = dict(mock_yardian_client.fetch_oper_info.return_value)
    new_oper_info["iStandby"] = future_ts
    mock_yardian_client.fetch_oper_info.return_value = new_oper_info

    freezer.tick(SCAN_INTERVAL)
    async_fire_time_changed(hass)
    await hass.async_block_till_done()

    assert hass.states.get(entity_id).state == STATE_ON

    # 2. Test Missing Data (Should be safely OFF)
    new_oper_info_missing = dict(mock_yardian_client.fetch_oper_info.return_value)
    new_oper_info_missing.pop("iStandby", None)
    mock_yardian_client.fetch_oper_info.return_value = new_oper_info_missing

    freezer.tick(SCAN_INTERVAL)
    async_fire_time_changed(hass)
    await hass.async_block_till_done()

    assert hass.states.get(entity_id).state == STATE_OFF


@pytest.mark.usefixtures("entity_registry_enabled_by_default")
async def test_freeze_prevent_sensor_states(
    hass: HomeAssistant,
    mock_yardian_client: AsyncMock,
    mock_config_entry: MockConfigEntry,
    entity_registry: er.EntityRegistry,
    freezer: FrozenDateTimeFactory,
) -> None:
    """Test freeze prevention binary sensor states and edge cases."""
    await setup_integration(hass, mock_config_entry)

    entity_id = entity_registry.async_get_entity_id(
        "binary_sensor", DOMAIN, f"{mock_config_entry.unique_id}-freeze_prevent"
    )
    assert entity_id is not None

    # 1. Initially ON (conftest.py mocks fFreezePrevent=1)
    assert hass.states.get(entity_id).state == STATE_ON

    # 2. Test OFF (fFreezePrevent=0)
    new_oper_info = dict(mock_yardian_client.fetch_oper_info.return_value)
    new_oper_info["fFreezePrevent"] = 0
    mock_yardian_client.fetch_oper_info.return_value = new_oper_info

    freezer.tick(SCAN_INTERVAL)
    async_fire_time_changed(hass)
    await hass.async_block_till_done()

    assert hass.states.get(entity_id).state == STATE_OFF

    # 3. Test Missing Data (Should default to OFF based on our code .get("fFreezePrevent", 0))
    new_oper_info_missing = dict(mock_yardian_client.fetch_oper_info.return_value)
    new_oper_info_missing.pop("fFreezePrevent", None)
    mock_yardian_client.fetch_oper_info.return_value = new_oper_info_missing

    freezer.tick(SCAN_INTERVAL)
    async_fire_time_changed(hass)
    await hass.async_block_till_done()

    assert hass.states.get(entity_id).state == STATE_OFF
