FROM python:3.4
MAINTAINER Paulus Schoutsen <Paulus@PaulusSchoutsen.nl>

VOLUME /config

RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

RUN pip3 install --no-cache-dir colorlog cython

# For the nmap tracker, bluetooth tracker, Z-Wave
RUN apt-get update && \
    apt-get install -y --no-install-recommends nmap net-tools cython3 libudev-dev sudo libglib2.0-dev locales-all bluetooth libbluetooth-dev && \
    apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

RUN pip3 install --no-cache-dir tox

# Copy over everything required to run tox
COPY requirements_all.txt requirements_all.txt
COPY requirements_test.txt requirements_test.txt
COPY setup.cfg setup.cfg
COPY setup.py setup.py
COPY tox.ini tox.ini
COPY homeassistant/const.py homeassistant/const.py

# Get deps
RUN tox --notest

# Copy source and run tests
COPY . .

CMD [ "tox" ]
