"""Definition of air-Q sensor platform.

This platform initialisation follows immediately after (or as the last part of) the
integration setup, defined in __init__.py.
"""
from __future__ import annotations

from homeassistant.components.sensor import (
    SensorDeviceClass,
    SensorEntity,
    SensorEntityDescription,
    SensorStateClass,
)
from homeassistant.config_entries import ConfigEntry
from homeassistant.const import (
    CONCENTRATION_MICROGRAMS_PER_CUBIC_METER,
    CONCENTRATION_MILLIGRAMS_PER_CUBIC_METER,
    CONCENTRATION_PARTS_PER_BILLION,
    CONCENTRATION_PARTS_PER_MILLION,
    PERCENTAGE,
    PRESSURE_HPA,
    TEMP_CELSIUS,
)
from homeassistant.core import HomeAssistant
from homeassistant.helpers.entity_platform import AddEntitiesCallback
from homeassistant.helpers.update_coordinator import (
    CoordinatorEntity,
    DataUpdateCoordinator,
)

from .const import DOMAIN

# Consider making key & name constants
# NOTE: keys must match those in the data dictionary
SENSOR_TYPES: list[SensorEntityDescription, ...] = [
    SensorEntityDescription(
        key="co",
        name="CO",
        device_class=SensorDeviceClass.CO,
        native_unit_of_measurement=CONCENTRATION_MILLIGRAMS_PER_CUBIC_METER,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    SensorEntityDescription(
        key="co2",
        name="CO2",
        device_class=SensorDeviceClass.CO2,
        native_unit_of_measurement=CONCENTRATION_PARTS_PER_MILLION,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    SensorEntityDescription(
        key="humidity",
        name="Humidity",
        device_class=SensorDeviceClass.HUMIDITY,
        native_unit_of_measurement=PERCENTAGE,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    SensorEntityDescription(
        key="no2",
        name="NO2",
        device_class=SensorDeviceClass.NITROGEN_DIOXIDE,
        native_unit_of_measurement=CONCENTRATION_MICROGRAMS_PER_CUBIC_METER,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    SensorEntityDescription(
        key="o3",
        name="Ozone",
        device_class=SensorDeviceClass.OZONE,
        native_unit_of_measurement=CONCENTRATION_MICROGRAMS_PER_CUBIC_METER,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    # TODO: check the definition in SensorDeviceClass.PM1. It says <= 0.1µm, not 1µm
    SensorEntityDescription(
        key="pm1",
        name="PM1",
        device_class=SensorDeviceClass.PM1,
        native_unit_of_measurement=CONCENTRATION_MICROGRAMS_PER_CUBIC_METER,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    SensorEntityDescription(
        key="pm2_5",
        name="PM25",
        device_class=SensorDeviceClass.PM25,
        native_unit_of_measurement=CONCENTRATION_MICROGRAMS_PER_CUBIC_METER,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    SensorEntityDescription(
        key="pm10",
        name="PM10",
        device_class=SensorDeviceClass.PM10,
        native_unit_of_measurement=CONCENTRATION_MICROGRAMS_PER_CUBIC_METER,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    SensorEntityDescription(
        key="pressure",
        name="Pressure",
        device_class=SensorDeviceClass.PRESSURE,
        native_unit_of_measurement=PRESSURE_HPA,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    SensorEntityDescription(
        key="so2",
        name="SO2",
        device_class=SensorDeviceClass.SULPHUR_DIOXIDE,
        native_unit_of_measurement=CONCENTRATION_MICROGRAMS_PER_CUBIC_METER,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    SensorEntityDescription(
        key="temperature",
        name="Temperature",
        device_class=SensorDeviceClass.TEMPERATURE,
        native_unit_of_measurement=TEMP_CELSIUS,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    SensorEntityDescription(
        key="tvoc",
        name="VOC",
        device_class=SensorDeviceClass.VOLATILE_ORGANIC_COMPOUNDS,
        native_unit_of_measurement=CONCENTRATION_PARTS_PER_BILLION,
        state_class=SensorStateClass.MEASUREMENT,
    ),
]


# async_setup_platform was generated by the scaffold, but in other components I see
# only async_setup_entry. TODO: understand the difference
# async def async_setup_platform(
#     hass: HomeAssistant,
#     config: ConfigType,
#     👆 pregenerated but does not have entry_id attribute
#     async_add_entities: AddEntitiesCallback,
#     discovery_info: DiscoveryInfoType | None = None,
# )->None:
#     pass
async def async_setup_entry(
    hass: HomeAssistant,
    config: ConfigEntry,
    async_add_entities: AddEntitiesCallback,
) -> None:
    """Set up sensor entities based on a config entry."""
    # NOTE: In other components this function is called async_setup_entry

    coordinator = hass.data[DOMAIN][config.entry_id]
    available_sensors = list(coordinator.data.keys())

    # Add sensors under warmup
    status = coordinator.data["Status"]
    if isinstance(status, dict):
        warming_up_sensors = [
            k for k, v in status.items() if "sensor still in warm up phase" in v
        ]
        available_sensors.extend(warming_up_sensors)

    # A potential nicer alternative to the iteration above is to fetch the list
    # of sensors from AirQ.sensors dynamic property. The issue with it is that I
    # only have access to them in __init__.async_setup_entry. The only way I see
    # to pass this info is to either define a custom coordinator (which can hold
    # both the AirQ instance, and the queried list of sensors, and anything else,
    # or to pass the list in the config entry, which I do not feel very comfortable
    # modifying (Should its .data field remain consistent with the STEP_USER_DATA_SCHEMA
    # defined in config_flow.py?

    entities = [
        AirQSensor(coordinator, description)
        for description in SENSOR_TYPES
        if description.key in available_sensors
    ]
    async_add_entities(entities)


class AirQSensor(CoordinatorEntity, SensorEntity):
    """Representation of a Sensor."""

    def __init__(
        self,
        coordinator: DataUpdateCoordinator,
        description: SensorEntityDescription,
    ) -> None:
        """Initialize a single sensor."""
        super().__init__(coordinator)
        self.entity_description = description

        # TODO: check the requirements for these two fields
        self._attr_name = f"AirQ {description.name}"
        self._attr_unique_id = f"airq_{description.key}"

    # TODO: check the guidelines on properties vs attributes...
    @property
    def native_value(self) -> float | int | None:
        """Return the value reported by the sensor."""
        # airthings has a neat way of doing it when the data returned by the API
        # are a dictionary with keys for each device, and values being dictionaries
        # of sensor values. Under this condition, the call should be:
        # return self.coordinator.data[self._id].sensors[self.entity_description.key]
        # In our case now, only one device is allowed and self.coordinator.data
        # contains the regular dict retrieved from a single device

        # .get(key, None) over [key] to guard against the keys of the warming up
        # sensors not being present in the returned dictionary
        return self.coordinator.data.get(self.entity_description.key, None)
