#!/bin/sh
# Resolve all frontend dependencies that the application requires to run.

# Stop on errors
set -e

cd "$(dirname "$0")/.."

echo "Bootstrapping frontend..."

git submodule update
cd homeassistant/components/frontend/www_static/home-assistant-polymer

# Install node modules
yarn install

# Install bower web components. Allow to download the components as root since the user in docker is root.
./node_modules/.bin/bower install --allow-root

# Development mode reads translation files from build directory since inherited
# language tags must be compiled to one file. Build the translations so that
# development mode frontend can run.
npm run frontend_trans

cd ../../../../..
