#!/bin/sh
# Builds the frontend for production

# Stop on errors
set -e

cd "$(dirname "$0")/.."

# Clean up
rm -rf homeassistant/components/frontend/www_static/core.js* \
       homeassistant/components/frontend/www_static/frontend.html* \
       homeassistant/components/frontend/www_static/webcomponents-lite.min.js* \
       homeassistant/components/frontend/www_static/panels
cd homeassistant/components/frontend/www_static/home-assistant-polymer
npm run clean

# Build frontend
npm run frontend_prod
cp bower_components/webcomponentsjs/webcomponents-lite.min.js ..
cp -r build/* ..
BUILD_DEV=0 node script/gen-service-worker.js
cp build/service_worker.js ..
cd ..

# Pack frontend
gzip -f -k -9 *.html *.js ./panels/*.html
cd ../../../..

# Generate the MD5 hash of the new frontend
script/fingerprint_frontend.py
