#!/bin/bash
[[ -z $(git ls-files --others --exclude-standard) ]] && exit 0

echo -e '\n***** ERROR\nTests are leaving files behind. Please update the tests to avoid writing any files:'

for file in `git ls-files --others --exclude-standard`; do
  echo "--> $file <--"
  cat $file
  echo
  echo "--> $file <--"
done
echo

exit 1
