#!/bin/sh

# script/cibuild: Setup environment for CI to run tests. This is primarily
#                 designed to run on the continuous integration server.

cd "$(dirname "$0")/.."

if [ "$TRAVIS_PYTHON_VERSION" = "3.5" ]; then
  echo "Verifying requirements_all.txt..."
  python3 setup.py -q develop
  tput setaf 1
  script/gen_requirements_all.py validate
  VERIFY_REQUIREMENTS_STATUS=$?
  tput sgr0
else
  VERIFY_REQUIREMENTS_STATUS=0
fi

if [ "$VERIFY_REQUIREMENTS_STATUS" != "0" ]; then
  exit $VERIFY_REQUIREMENTS_STATUS
fi

script/bootstrap_server > /dev/null
DEP_INSTALL_STATUS=$?

if [ "$DEP_INSTALL_STATUS" != "0" ]; then
  exit $DEP_INSTALL_STATUS
fi

if [ "$TRAVIS_PYTHON_VERSION" != "3.5" ]; then
  NO_LINT=1
fi

export NO_LINT

script/test coverage

STATUS=$?

coveralls

exit $STATUS
