"""Helper script to update language list from the frontend source."""
import json
import pathlib
import sys

import black
import requests

BASE = """
\"\"\"Automatically generated by languages.py.

To update, run python3 -m script.languages [frontend_tag]
\"\"\"

LANGUAGES = {{ {} }}
""".strip()

tag = sys.argv[1] if len(sys.argv) > 1 else "dev"

req = requests.get(
    f"https://raw.githubusercontent.com/home-assistant/frontend/{tag}/src/translations/translationMetadata.json"
)
data = json.loads(req.content)
languages = sorted(data.keys())

pathlib.Path("homeassistant/generated/languages.py").write_text(
    black.format_str(
        BASE.format(repr(languages)[1:-1]),
        mode=black.Mode(),
    )
)
