#!/bin/sh
# Execute lint in a docker container to spot code mistakes.

# Stop on errors
set -e

docker build -t home-assistant-test -f virtualization/Docker/Dockerfile.dev .
docker run --rm -it home-assistant-test tox -e lint
