#!/bin/sh
# Execute lint to spot code mistakes.

# Make sure that errors will halt this script with the error 
set -e

cd "$(dirname "$0")/.."

merge_base=$(git merge-base upstream/dev HEAD)
changed_files=$(git diff $merge_base --diff-filter=d --name-only)
export pyfiles=$(echo "$changed_files" | grep -e '\.py$')
echo '================================================='
echo '=                FILES CHANGED                  ='
echo '================================================='
if [ -z "$pyfiles" ] ; then
  echo "No python file changed.\n"
  exit
fi
printf "%s\n" $pyfiles
echo "=============="
echo "LINT with ruff"
echo "=============="
pre-commit run ruff --files $pyfiles
echo "================"
echo "LINT with pylint"
echo "================"
pylint_files=$(echo "$pyfiles" | grep -v '^tests.*')
if [ -z "$pylint_files" ] ; then
  echo "Only test files changed. Skipping\n"
  exit
fi
pylint $pylint_files
echo
