#!/bin/sh
# Execute lint to spot code mistakes.

cd "$(dirname "$0")/.."

if [ "$1" = "--changed" ]; then
  export files="`git diff upstream/dev... --name-only | grep -e '\.py$'`"
  echo "================================================="
  echo "FILES CHANGED (git diff upstream/dev... --name-only)"
  echo "================================================="
  if $files >/dev/null; then
    echo "No python file changed"
    exit
  fi
  printf "%s\n" $files
  echo "================"
  echo "LINT with flake8"
  echo "================"
  flake8 --doctests $files
  echo "================"
  echo "LINT with pylint"
  echo "================"
  pylint $files
  echo
else
  tox -e lint
fi
