#!/bin/sh
# Execute pylint on changed tests.

cd "$(dirname "$0")/.."

export files="`git diff upstream/dev --name-only | grep -e 'test_.\+\.py$'`"
if [ -z "$files" ] ; then
  echo "No test files changed.  Rather use pytest or tox directly."
  exit
fi
export files="`printf "%s " $files`"
echo "======"
echo "pytest -vv -- $files"
echo "======"
pytest -vv -- $files
