#!/usr/bin/env bash
# Setups the repository.

# Stop on errors
set -e

cd "$(dirname "$0")/.."

mkdir -p config

if [[ -e venv/bin/activate ]]; then
    if [[ -z "${VIRTUAL_ENV}" ]]; then
        source venv/bin/activate
    fi
    cur_python=$(python3 -V)
    if [[ ! $cur_python =~ .*3\.[78].* ]]; then
        echo $cur_python is not supported!
        exit 1
    fi
else
    if [[ -x "$(command -v python3)" && "$(python3 -V)" =~ .*3\.[78].* ]]; then
        cmd=python3
    elif [[ -x "$(command -v python3.8)" ]]; then
        cmd="python3.8"
    elif [[ -x "$(command -v python3.7)" ]]; then
        cmd="python3.7"
    else
        echo Neither Python 3.7 nor 3.8 installed!
        exit 2
    fi
    $cmd -m venv venv
    source venv/bin/activate
fi

script/bootstrap

pre-commit install
python3 -m pip install -e . --constraint homeassistant/package_constraints.txt

hass --script ensure_config -c config

echo "
logger:
  default: info
  logs:
    homeassistant.components.cloud: debug
" >> config/configuration.yaml
