#!/usr/bin/env bash
# Setups the repository.

# Stop on errors
set -e

cd "$(dirname "$0")/.."

# Add default vscode settings if not existing
SETTINGS_FILE=./.vscode/settings.json
SETTINGS_TEMPLATE_FILE=./.vscode/settings.default.json
if [ ! -f "$SETTINGS_FILE" ]; then
    echo "Copy $SETTINGS_TEMPLATE_FILE to $SETTINGS_FILE."
    cp "$SETTINGS_TEMPLATE_FILE" "$SETTINGS_FILE"
fi

IS_PYTHON_3_VERSION_3_11=$(python3 --version | grep '3\.11\.[0-9]\+')
if [ -z $IS_PYTHON_3_VERSION_3_11 ];then
  if [ ! -z $(python3.11 --version | grep '3\.11\.[0-9]\+') ]; then
    alias python3='python3.11'
  else
    echo "The default Python version is not 3.11, and neither is the python3.11 command"
    return 1
  fi
fi

mkdir -p config

if [ ! -n "$DEVCONTAINER" ] && [ ! -n "$VIRTUAL_ENV" ];then
  python3 -m venv venv
  source venv/bin/activate
fi

script/bootstrap

pre-commit install
python3 -m pip install -e . --config-settings editable_mode=compat --constraint homeassistant/package_constraints.txt
python3 -m script.translations develop --all

hass --script ensure_config -c config

if ! grep -R "logger" config/configuration.yaml >> /dev/null;then
echo "
logger:
  default: info
  logs:
    homeassistant.components.cloud: debug
" >> config/configuration.yaml
fi
