#!/bin/sh
# Excutes the tests with tox in a docker container.

# Stop on errors
set -e

docker build -t home-assistant-test -f virtualization/Docker/Dockerfile.dev .
docker run --rm -it home-assistant-test tox -e py35
