#!/bin/sh

# script/test: Run test suite for application. Optionallly pass in a path to an
#              individual test file to run a single test.

cd "$(dirname "$0")/.."

script/lint

STATUS=$?

echo "Running tests..."

if [ "$1" = "coverage" ]; then
  py.test --cov --cov-report=
else
  py.test
fi

if [ $STATUS -eq 0 ]
then
  exit $?
else
  exit $STATUS
fi
