#!/usr/bin/env bash

# Compile the current translation strings files for testing

# Safe bash settings
# -e            Exit on command fail
# -u            Exit on unset variable
# -o pipefail   Exit if piped command has error code
set -eu -o pipefail

cd "$(dirname "$0")/.."

mkdir -p build/translations-download

script/translations_upload_merge.py

# Use the generated translations upload file as the mock output from the
# Lokalise download
mv build/translations-upload.json build/translations-download/en.json

script/translations_download_split.py
