config_entry:
  versions:
    - version:
        major: 1
        minor: 1
      data:
        fields:
          api_key:
            required: true
            selector:
              text:
                type: password
      options:
        fields: {}
  subentries:
    route:
      versions:
        - version:
            major: 1
            minor: 1
          data:
            fields:
              name:
                required: true
                selector:
                  text: {}
              from:
                required: true
                selector:
                  text: {}
              to:
                required: true
                selector:
                  text: {}
              via:
                required: false
                selector:
                  text: {}
              time:
                required: false
                selector:
                  text: {}
          options:
            fields: {}
