play_rtttl:
  fields:
    device_id:
      required: true
      selector:
        device:
          filter:
            - integration: smlight
              model: SLZB-Ultima3
            - integration: smlight
              model: SLZB-Ultima4
    tone:
      required: true
      example: "Doorbell:d=4,o=5,b=100:e,c"
      selector:
        text:
