"""Compatibility re-export of the standalone Inepro Metering Modbus library."""

from inepro_metering.modbus import (
    BLUETOOTH_PAIRING_MODE_AUTO,
    BLUETOOTH_PAIRING_MODE_NEVER,
    BLUETOOTH_PAIRING_MODE_REQUIRED,
    CONF_BLE_CLIENT_FACTORY,
    CONF_BLUETOOTH_ADDRESS,
    CONF_BLUETOOTH_DEVICE,
    CONF_BLUETOOTH_DEVICE_RESOLVER,
    CONF_BLUETOOTH_FORCE_REPAIR,
    CONF_BLUETOOTH_NAME,
    CONF_BLUETOOTH_PAIRING_MODE,
    CONF_BLUETOOTH_PAIRING_PIN,
    CONF_BLUETOOTH_PAIRING_PIN_PROVIDER,
    CONF_BLUETOOTH_PAIRING_TIMEOUT,
    IneproBluetoothNotPairedError,
    IneproConnectionError,
    IneproMeteringError,
    IneproModbusClient,
    IneproReadError,
    IneproWriteError,
    async_validate_modbus_config,
)

__all__ = [
    "BLUETOOTH_PAIRING_MODE_AUTO",
    "BLUETOOTH_PAIRING_MODE_NEVER",
    "BLUETOOTH_PAIRING_MODE_REQUIRED",
    "CONF_BLE_CLIENT_FACTORY",
    "CONF_BLUETOOTH_ADDRESS",
    "CONF_BLUETOOTH_DEVICE",
    "CONF_BLUETOOTH_DEVICE_RESOLVER",
    "CONF_BLUETOOTH_FORCE_REPAIR",
    "CONF_BLUETOOTH_NAME",
    "CONF_BLUETOOTH_PAIRING_MODE",
    "CONF_BLUETOOTH_PAIRING_PIN",
    "CONF_BLUETOOTH_PAIRING_PIN_PROVIDER",
    "CONF_BLUETOOTH_PAIRING_TIMEOUT",
    "IneproBluetoothNotPairedError",
    "IneproConnectionError",
    "IneproMeteringError",
    "IneproModbusClient",
    "IneproReadError",
    "IneproWriteError",
    "async_validate_modbus_config",
]
