"""Constants for ebus component."""
DOMAIN = "ebusd"
VALID_SENSOR_TYPES: dict[str, set[str]] = {
    "700": {
        "ActualFlowTemperatureDesired",
        "MaxFlowTemperatureDesired",
        "MinFlowTemperatureDesired",
        "PumpStatus",
        "HCSummerTemperatureLimit",
        "HolidayTemperature",
        "HWTemperatureDesired",
        "HWActualTemperature",
        "HWTimerMonday",
        "HWTimerTuesday",
        "HWTimerWednesday",
        "HWTimerThursday",
        "HWTimerFriday",
        "HWTimerSaturday",
        "HWTimerSunday",
        "HWOperativeMode",
        "WaterPressure",
        "Zone1RoomZoneMapping",
        "Zone1NightTemperature",
        "Zone1DayTemperature",
        "Zone1HolidayTemperature",
        "Zone1RoomTemperature",
        "Zone1ActualRoomTemperatureDesired",
        "Zone1TimerMonday",
        "Zone1TimerTuesday",
        "Zone1TimerWednesday",
        "Zone1TimerThursday",
        "Zone1TimerFriday",
        "Zone1TimerSaturday",
        "Zone1TimerSunday",
        "Zone1OperativeMode",
        "ContinuosHeating",
        "PowerEnergyConsumptionLastMonth",
        "PowerEnergyConsumptionThisMonth",
    },
    "ehp": {
        "HWTemperature",
        "OutsideTemp",
    },
    "bai": {
        "HotWaterTemperature",
        "StorageTemperature",
        "DesiredStorageTemperature",
        "OutdoorsTemperature",
        "WaterPressure",
        "AverageIgnitionTime",
        "MaximumIgnitionTime",
        "MinimumIgnitionTime",
        "ReturnTemperature",
        "CentralHeatingPump",
        "HeatingSwitch",
        "DesiredFlowTemperature",
        "FlowTemperature",
        "Flame",
        "PowerEnergyConsumptionHeatingCircuit",
        "PowerEnergyConsumptionHotWaterCircuit",
        "RoomThermostat",
        "HeatingPartLoad",
        "StateNumber",
        "ModulationPercentage",
    },
}
