#!/bin/sh
# Installs a modified coap client with support for dtls for use with IKEA Tradfri

# Stop on errors
set -e

apt-get install -y --no-install-recommends git autoconf automake libtool

git clone --depth 1 --recursive -b dtls https://github.com/home-assistant/libcoap.git
cd libcoap
./autogen.sh
./configure --disable-documentation --disable-shared --without-debug CFLAGS="-D COAP_DEBUG_FD=stderr"
make
make install
