#!/bin/bash
# Sets up gactions for the google_assistant component.

# Stop on errors
set -e

curl -LSO https://dl.google.com/gactions/updates/bin/linux/amd64/gactions/gactions
mv gactions /usr/bin/gactions
chmod +x /usr/bin/gactions
/usr/bin/gactions -V
