#!/bin/bash
# Sets up locales.

# Stop on errors
set -e

apt-get update
apt-get install -y --no-install-recommends locales

# Set the locale
sed -i -e 's/# en_US.UTF-8 UTF-8/en_US.UTF-8 UTF-8/' /etc/locale.gen
locale-gen
