#!/bin/bash
# Sets up ssocr to support Seven Segments Display.

# Stop on errors
set -e

PACKAGES=(
  libimlib2 libimlib2-dev
)

apt-get install -y --no-install-recommends ${PACKAGES[@]}

cd /usr/src/app/
mkdir -p build && cd build

# Clone the latest code from GitHub
git clone --depth 1 https://github.com/auerswal/ssocr.git ssocr
cd ssocr/

# Compile the library
make -j$(nproc)

# Install the binaries/libraries to your local system (prefix is /usr/local)
make install
