#!/bin/bash
# Sets up ssocr to support Seven Segments Display.

# Stop on errors
set -e

PACKAGES=(
  libimlib2 libimlib2-dev
)

apt-get install -y --no-install-recommends ${PACKAGES[@]}

# Clone the latest code from GitHub
git clone --depth 1 https://github.com/auerswal/ssocr.git /usr/local/src/ssocr

# Build ssocr
(
  # Setup the build directory
  cd /usr/local/src/ssocr

  # compile the library
  make

  # Install the binaries/libraries to your local system (prefix is /usr/local)
  make install

  # Cleanup
  make clean
)
