#!/bin/bash
# Sets up tellstick.

# Stop on errors
set -e

PACKAGES=(
  # homeassistant.components.tellstick
  libtelldus-core2
)

# Add Tellstick repository
echo "deb http://download.telldus.com/debian/ stable main" >> /etc/apt/sources.list.d/telldus.list
wget -qO - http://download.telldus.com/debian/telldus-public.key | apt-key add -

apt-get update
apt-get install -y --no-install-recommends ${PACKAGES[@]}
