"""Constants for the Microsoft Speech integration."""

from typing import Final

DOMAIN = "microsoft_speech"
DATA_SPEECH_CONFIG = "speech_config"
DATA_VOICES = "voices"
SUPPORTED_LANGUAGES: Final[list[str]] = [
    "ar-AE",
    "ar-BH",
    "ar-EG",
    "ar-IQ",
    "ar-JO",
    "ar-KW",
    "ar-LB",
    "ar-OM",
    "ar-QA",
    "ar-SA",
    "ar-SY",
    "bg-BG",
    "ca-ES",
    "cs-CZ",
    "da-DK",
    "de-DE",
    "el-GR",
    "en-AU",
    "en-CA",
    "en-GB",
    "en-HK",
    "en-IE",
    "en-IN",
    "en-NZ",
    "en-PH",
    "en-SG",
    "en-US",
    "en-ZA",
    "es-AR",
    "es-ES",
    "es-MX",
    "es-US",
    "fi-FI",
    "fr-CA",
    "fr-FR",
    "gu-IN",
    "hi-IN",
    "hr-HR",
    "hu-HU",
    "it-IT",
    "ja-JP",
    "ko-KR",
    "lt-LT",
    "lv-LV",
    "mr-IN",
    "nb-NO",
    "nl-NL",
    "pl-PL",
    "pt-BR",
    "pt-PT",
    "ro-RO",
    "ru-RU",
    "sk-SK",
    "sl-SI",
    "sv-SE",
    "ta-IN",
    "te-IN",
    "th-TH",
    "tr-TR",
    "zh-CN",
    "zh-HK",
    "zh-TW",
]
