"""Constants for the Microsoft Speech integration."""

from typing import Final

DOMAIN = "microsoft_speech"

# REST API endpoint templates
VOICES_ENDPOINT = (
    "https://{region}.tts.speech.microsoft.com/cognitiveservices/voices/list"
)
STT_ENDPOINT = "https://{region}.stt.speech.microsoft.com/speech/recognition/conversation/cognitiveservices/v1"

SUPPORTED_LANGUAGES: Final[list[str]] = [
    "ar-AE",
    "ar-BH",
    "ar-EG",
    "ar-IQ",
    "ar-JO",
    "ar-KW",
    "ar-LB",
    "ar-OM",
    "ar-QA",
    "ar-SA",
    "ar-SY",
    "bg-BG",
    "ca-ES",
    "cs-CZ",
    "da-DK",
    "de-DE",
    "el-GR",
    "en-AU",
    "en-CA",
    "en-GB",
    "en-HK",
    "en-IE",
    "en-IN",
    "en-NZ",
    "en-PH",
    "en-SG",
    "en-US",
    "en-ZA",
    "es-AR",
    "es-ES",
    "es-MX",
    "es-US",
    "fi-FI",
    "fr-CA",
    "fr-FR",
    "gu-IN",
    "hi-IN",
    "hr-HR",
    "hu-HU",
    "it-IT",
    "ja-JP",
    "ko-KR",
    "lt-LT",
    "lv-LV",
    "mr-IN",
    "nb-NO",
    "nl-NL",
    "pl-PL",
    "pt-BR",
    "pt-PT",
    "ro-RO",
    "ru-RU",
    "sk-SK",
    "sl-SI",
    "sv-SE",
    "ta-IN",
    "te-IN",
    "th-TH",
    "tr-TR",
    "zh-CN",
    "zh-HK",
    "zh-TW",
]

SUPPORTED_REGIONS = [
    "australiacentral",
    "australiacentral2",
    "australiaeast",
    "australiasoutheast",
    "brazilsouth",
    "brazilsoutheast",
    "canadacentral",
    "canadaeast",
    "centralus",
    "eastasia",
    "eastus",
    "eastus2",
    "francecentral",
    "francesouth",
    "germanynorth",
    "germanywestcentral",
    "indiaeast",
    "indiacentral",
    "japaneast",
    "japanwest",
    "koreacentral",
    "koreasouth",
    "northeurope",
    "northcentralus",
    "norwayeast",
    "norwaywest",
    "southafricanorth",
    "southafricawest",
    "southeastasia",
    "southcentralus",
    "switzerlandnorth",
    "switzerlandwest",
    "uaecentral",
    "uaenorth",
    "uksouth",
    "ukwest",
    "westeurope",
    "westus",
    "westus2",
    "westus3",
]
