get_packages:
  fields:
    package_state:
      selector:
        select:
          multiple: true
          options:
            - "not_found"
            - "in_transit"
            - "expired"
            - "ready_to_be_picked_up"
            - "undelivered"
            - "delivered"
            - "alert"
          translation_key: package_state
    config_entry_id:
      required: true
      selector:
        config_entry:
          integration: seventeentrack
add_package:
  fields:
    package_tracking_number:
      required: true
      selector:
        text:
    package_friendly_name:
      required: true
      selector:
        text:
    config_entry_id:
      required: true
      selector:
        config_entry:
          integration: seventeentrack

archive_package:
  fields:
    package_tracking_number:
      required: true
      selector:
        text:
    config_entry_id:
      required: true
      selector:
        config_entry:
          integration: seventeentrack

set_carrier:
  fields:
    package_tracking_number:
      required: true
      selector:
        text:
    first_carrier:
      required: true
      example: 190271
      selector:
        number:
          min: 1
          max: 999999
          mode: box
    second_carrier:
      example: 19251
      selector:
        number:
          min: 0
          max: 999999
          mode: box
    config_entry_id:
      required: true
      selector:
        config_entry:
          integration: seventeentrack
