config_entry:
  versions:
    - version:
        major: 1
        minor: 1
      data:
        fields: {}
      options:
        fields:
          all:
            required: false
            selector:
              text: {}
          device_class:
            required: false
            selector:
              text: {}
          entities:
            required: false
            selector:
              text: {}
          hide_members:
            required: false
            selector:
              text: {}
          ignore_non_numeric:
            required: false
            selector:
              text: {}
          round_digits:
            required: false
            selector:
              text: {}
          state_class:
            required: false
            selector:
              text: {}
          type:
            required: false
            selector:
              text: {}
          unit_of_measurement:
            required: false
            selector:
              text: {}
          name:
            required: false
            selector:
              text: {}
  subentries: {}
