"""Constants for the asyncua integration."""
DOMAIN = "asyncua"

"""Constant required for asnycua hub"""
CONF_HUB_ID = "name"
CONF_HUB_MANUFACTURER = "manufacturer"
CONF_HUB_MODEL = "model"
CONF_HUB_SCAN_INTERVAL = "scan_interval"
CONF_HUB_URL = "url"
CONF_HUB_USERNAME = "username"
CONF_HUB_PASSWORD = "password"

"""Constant required for opcua entities"""
CONF_NODES = "nodes"
CONF_NODE_DEVICE_CLASS = "device_class"
CONF_NODE_HUB = "hub"
CONF_NODE_ID = "nodeid"
CONF_NODE_NAME = "name"
CONF_NODE_STATE_CLASS = "state_class"
CONF_NODE_UNIQUE_ID = "unique_id"
CONF_NODE_UNIT_OF_MEASUREMENT = "unit_of_measurement"

"""COnstant required to set values"""
ATTR_NODE_HUB = "hub"
ATTR_NODE_ID = "nodeid"
ATTR_VALUE = "value"
SERVICE_SET_VALUE = "set_value"
