"""Test data for the tests of the SwitchBee integration."""

MOCK_GET_CONFIGURATION = {
    "status": "OK",
    "data": {
        "mac": "XX-XX-XX-XX-XX-XX",
        "name": "Home",
        "version": "1.4.3(0)",
        "lastConfChange": 1650533050421,
        "zones": [
            {
                "name": "קומה ראשית",
                "items": [
                    {
                        "operations": [
                            {"itemId": 2, "value": 29},
                            {"itemId": 1, "value": 35},
                            {"itemId": 22, "value": 29},
                            {"itemId": 31, "value": 29},
                            {"itemId": 41, "value": 29},
                            {"itemId": 21, "value": 29},
                        ],
                        "id": 100040,
                        "name": "שלב אור",
                        "hw": "VIRTUAL",
                        "type": "SCENARIO",
                    },
                    {
                        "id": 561,
                        "name": "תקרה",
                        "hw": "DIMMABLE_SWITCH",
                        "type": "SWITCH",
                    },
                    {
                        "operations": [
                            {"itemId": 2, "value": 0},
                            {"itemId": 1, "value": 0},
                            {"itemId": 22, "value": 0},
                            {"itemId": 31, "value": 0},
                            {"itemId": 41, "value": 0},
                            {"itemId": 21, "value": 0},
                        ],
                        "id": 100030,
                        "name": "סגירת חלונות",
                        "hw": "VIRTUAL",
                        "type": "SCENARIO",
                    },
                    {
                        "id": 181,
                        "name": "מדרגות קיר עליו",
                        "hw": "DIMMABLE_SWITCH",
                        "type": "DIMMER",
                    },
                    {
                        "id": 571,
                        "name": "Repeater",
                        "hw": "REPEATER",
                        "type": "REPEATER",
                    },
                    {
                        "id": 121,
                        "name": "מחסן (תחת מדרגות)",
                        "hw": "DIMMABLE_SWITCH",
                        "type": "SWITCH",
                    },
                    {
                        "id": 182,
                        "name": "מדרגות תחתון",
                        "hw": "DIMMABLE_SWITCH",
                        "type": "SWITCH",
                    },
                ],
            },
            {
                "name": "סלון ראשי",
                "items": [
                    {
                        "id": 592,
                        "name": "תאורה צפונית",
                        "hw": "DIMMABLE_SWITCH",
                        "type": "SWITCH",
                    },
                    {
                        "id": 591,
                        "name": "תאורה דרומית",
                        "hw": "DIMMABLE_SWITCH",
                        "type": "SWITCH",
                    },
                    {
                        "id": 71,
                        "name": "קיר",
                        "hw": "DIMMABLE_SWITCH",
                        "type": "DIMMER",
                    },
                    {
                        "id": 593,
                        "name": "לד מזנון",
                        "hw": "DIMMABLE_SWITCH",
                        "type": "SWITCH",
                    },
                    {
                        "operations": [593, 581, 171],
                        "id": 481,
                        "name": "Leds",
                        "hw": "DIMMABLE_SWITCH",
                        "type": "GROUP_SWITCH",
                    },
                    {"id": 22, "name": "מזרחי", "hw": "SHUTTER", "type": "SHUTTER"},
                    {"id": 21, "name": "צפוני", "hw": "SHUTTER", "type": "SHUTTER"},
                ],
            },
            {
                "name": "סלון",
                "items": [
                    {
                        "id": 12,
                        "name": "קיר",
                        "hw": "DIMMABLE_SWITCH",
                        "type": "DIMMER",
                    },
                    {"id": 1, "name": "צפוני", "hw": "SHUTTER", "type": "SHUTTER"},
                    {"id": 2, "name": "מערבי", "hw": "SHUTTER", "type": "SHUTTER"},
                    {
                        "id": 11,
                        "name": "תקרה",
                        "hw": "DIMMABLE_SWITCH",
                        "type": "SWITCH",
                    },
                ],
            },
            {
                "name": "מטבח",
                "items": [
                    {
                        "id": 132,
                        "name": "פס צבירה",
                        "hw": "DIMMABLE_SWITCH",
                        "type": "SWITCH",
                    },
                    {
                        "id": 131,
                        "name": "חדר אוכל",
                        "hw": "DIMMABLE_SWITCH",
                        "type": "SWITCH",
                    },
                    {"id": 31, "name": "מטבח", "hw": "SHUTTER", "type": "SHUTTER"},
                    {"id": 41, "name": "חדר אוכל", "hw": "SHUTTER", "type": "SHUTTER"},
                    {
                        "id": 91,
                        "name": "ממ״ד",
                        "hw": "DIMMABLE_SWITCH",
                        "type": "SWITCH",
                    },
                    {
                        "id": 581,
                        "name": "לד ",
                        "hw": "DIMMABLE_SWITCH",
                        "type": "SWITCH",
                    },
                    {
                        "id": 171,
                        "name": "לד",
                        "hw": "DIMMABLE_SWITCH",
                        "type": "SWITCH",
                    },
                    {
                        "operations": [581, 171],
                        "id": 100520,
                        "name": "לדים",
                        "hw": "VIRTUAL",
                        "type": "GROUP_SWITCH",
                    },
                ],
            },
            {
                "name": "Two Way Zone",
                "items": [
                    {
                        "operations": [221],
                        "id": 281,
                        "name": "תאורת קיר מיטה",
                        "hw": "DIMMABLE_SWITCH",
                        "type": "TWO_WAY",
                    },
                    {
                        "operations": [182],
                        "id": 292,
                        "name": "מדרגות",
                        "hw": "DIMMABLE_SWITCH",
                        "type": "TWO_WAY",
                    },
                    {
                        "operations": [301],
                        "id": 321,
                        "name": "מסדרון תקרה",
                        "hw": "DIMMABLE_SWITCH",
                        "type": "TWO_WAY",
                    },
                    {
                        "operations": [301],
                        "id": 331,
                        "name": "מסדרון תקרה",
                        "hw": "DIMMABLE_SWITCH",
                        "type": "TWO_WAY",
                    },
                    {
                        "operations": [352],
                        "id": 362,
                        "name": "תאורת תקרה",
                        "hw": "DIMMABLE_SWITCH",
                        "type": "TWO_WAY",
                    },
                    {
                        "operations": [351],
                        "id": 361,
                        "name": "קיר ימין",
                        "hw": "DIMMABLE_SWITCH",
                        "type": "TWO_WAY",
                    },
                    {
                        "operations": [353],
                        "id": 363,
                        "name": "קיר שמאל",
                        "hw": "DIMMABLE_SWITCH",
                        "type": "TWO_WAY",
                    },
                    {
                        "operations": [301],
                        "id": 161,
                        "name": "מסדרון תקרה",
                        "hw": "DIMMABLE_SWITCH",
                        "type": "TWO_WAY",
                    },
                    {
                        "operations": [511],
                        "id": 532,
                        "name": "מדרגות",
                        "hw": "DIMMABLE_SWITCH",
                        "type": "TWO_WAY",
                    },
                    {
                        "operations": [561],
                        "id": 51,
                        "name": "תקרה מסדרון ראש",
                        "hw": "DIMMABLE_SWITCH",
                        "type": "TWO_WAY",
                    },
                    {
                        "operations": [212],
                        "id": 242,
                        "name": "לד",
                        "hw": "DIMMABLE_SWITCH",
                        "type": "TWO_WAY",
                    },
                    {
                        "operations": [212],
                        "id": 271,
                        "name": "לד",
                        "hw": "DIMMABLE_SWITCH",
                        "type": "TWO_WAY",
                    },
                    {
                        "operations": [192],
                        "id": 342,
                        "name": "תקרה",
                        "hw": "DIMMABLE_SWITCH",
                        "type": "TWO_WAY",
                    },
                    {
                        "operations": [302],
                        "id": 322,
                        "name": "קיר",
                        "hw": "DIMMABLE_SWITCH",
                        "type": "TWO_WAY",
                    },
                    {
                        "operations": [302],
                        "id": 332,
                        "name": "קיר",
                        "hw": "DIMMABLE_SWITCH",
                        "type": "TWO_WAY",
                    },
                    {
                        "operations": [302],
                        "id": 162,
                        "name": "קיר",
                        "hw": "DIMMABLE_SWITCH",
                        "type": "TWO_WAY",
                    },
                    {
                        "operations": [211],
                        "id": 282,
                        "name": "קיר",
                        "hw": "DIMMABLE_SWITCH",
                        "type": "TWO_WAY",
                    },
                    {
                        "operations": [211],
                        "id": 232,
                        "name": "קיר",
                        "hw": "DIMMABLE_SWITCH",
                        "type": "TWO_WAY",
                    },
                    {
                        "operations": [181],
                        "id": 291,
                        "name": "מדרגות עליון",
                        "hw": "DIMMABLE_SWITCH",
                        "type": "TWO_WAY",
                    },
                    {
                        "operations": [592],
                        "id": 72,
                        "name": "תאורה צפונית",
                        "hw": "DIMMABLE_SWITCH",
                        "type": "TWO_WAY",
                    },
                    {
                        "operations": [213],
                        "id": 272,
                        "name": "ספוטים חש",
                        "hw": "DIMMABLE_SWITCH",
                        "type": "TWO_WAY",
                    },
                    {
                        "operations": [213],
                        "id": 241,
                        "name": "ספוטים חש",
                        "hw": "DIMMABLE_SWITCH",
                        "type": "TWO_WAY",
                    },
                ],
            },
            {
                "name": "שירותי אורחים",
                "items": [
                    {
                        "id": 102,
                        "name": "וונטה",
                        "hw": "DIMMABLE_SWITCH",
                        "type": "SWITCH",
                    },
                    {
                        "id": 101,
                        "name": "תאורה",
                        "hw": "DIMMABLE_SWITCH",
                        "type": "SWITCH",
                    },
                ],
            },
            {
                "name": "משרד",
                "items": [
                    {
                        "id": 343,
                        "name": "קיר שמאל",
                        "hw": "DIMMABLE_SWITCH",
                        "type": "SWITCH",
                    },
                    {
                        "id": 341,
                        "name": "קיר ימין",
                        "hw": "DIMMABLE_SWITCH",
                        "type": "SWITCH",
                    },
                    {"id": 191, "name": "חלון ", "hw": "SHUTTER", "type": "SHUTTER"},
                    {
                        "id": 192,
                        "name": "תקרה",
                        "hw": "DIMMABLE_SWITCH",
                        "type": "SWITCH",
                    },
                ],
            },
            {
                "name": "מקלחת ילדים",
                "items": [
                    {"id": 201, "name": "חלון", "hw": "SHUTTER", "type": "SHUTTER"}
                ],
            },
            {
                "name": "מקלחת הורים",
                "items": [
                    {
                        "id": 432,
                        "name": "תאורת מראה",
                        "hw": "DIMMABLE_SWITCH",
                        "type": "SWITCH",
                    },
                    {
                        "id": 433,
                        "name": "וונטה",
                        "hw": "DIMMABLE_SWITCH",
                        "type": "SWITCH",
                    },
                    {
                        "id": 421,
                        "name": "חלון צפוני",
                        "hw": "SHUTTER",
                        "type": "SHUTTER",
                    },
                    {
                        "id": 431,
                        "name": "תאורת תקרה",
                        "hw": "DIMMABLE_SWITCH",
                        "type": "SWITCH",
                    },
                    {
                        "id": 551,
                        "name": "מחמם מגבות",
                        "hw": "DIMMABLE_SWITCH",
                        "type": "SWITCH",
                    },
                ],
            },
            {
                "name": "חדר ארונות",
                "items": [
                    {
                        "id": 413,
                        "name": "תאורת תקרה",
                        "hw": "DIMMABLE_SWITCH",
                        "type": "SWITCH",
                    },
                    {
                        "id": 411,
                        "name": "חלון מזרחי",
                        "hw": "SHUTTER",
                        "type": "SHUTTER",
                    },
                ],
            },
            {
                "name": "חדר שינה",
                "items": [
                    {
                        "id": 221,
                        "name": "תאורת קיר מיטה",
                        "hw": "DIMMABLE_SWITCH",
                        "type": "SWITCH",
                    },
                    {
                        "id": 251,
                        "name": "טואלט",
                        "hw": "DIMMABLE_SWITCH",
                        "type": "SWITCH",
                    },
                    {
                        "id": 262,
                        "name": "חלון צפוני",
                        "hw": "SHUTTER",
                        "type": "SHUTTER",
                    },
                    {
                        "id": 261,
                        "name": "חלון מערבי",
                        "hw": "SHUTTER",
                        "type": "SHUTTER",
                    },
                    {
                        "id": 212,
                        "name": "לד חדר שינה",
                        "hw": "DIMMABLE_SWITCH",
                        "type": "DIMMER",
                    },
                    {
                        "id": 231,
                        "name": "תאורת קריאה דרו",
                        "hw": "DIMMABLE_SWITCH",
                        "type": "DIMMER",
                    },
                    {
                        "id": 211,
                        "name": "קיר",
                        "hw": "DIMMABLE_SWITCH",
                        "type": "DIMMER",
                    },
                    {
                        "id": 222,
                        "name": "מיטה צד שמאל",
                        "hw": "DIMMABLE_SWITCH",
                        "type": "DIMMER",
                    },
                    {
                        "id": 213,
                        "name": "ספוטים",
                        "hw": "DIMMABLE_SWITCH",
                        "type": "DIMMER",
                    },
                ],
            },
            {
                "name": "מסדרון קומה 2",
                "items": [
                    {
                        "id": 301,
                        "name": "תאורת תקרה",
                        "hw": "DIMMABLE_SWITCH",
                        "type": "SWITCH",
                    },
                    {
                        "id": 302,
                        "name": "תאורת קיר",
                        "hw": "DIMMABLE_SWITCH",
                        "type": "DIMMER",
                    },
                    {
                        "id": 601,
                        "name": "בוילר",
                        "hw": "TIMED_POWER_SWITCH",
                        "type": "TIMED_POWER",
                    },
                ],
            },
            {
                "name": "מחסן חיצוני",
                "items": [
                    {
                        "id": 152,
                        "name": "קיר חוץ",
                        "hw": "DIMMABLE_SWITCH",
                        "type": "SWITCH",
                    },
                    {
                        "id": 151,
                        "name": "תקרה חוץ",
                        "hw": "DIMMABLE_SWITCH",
                        "type": "SWITCH",
                    },
                    {
                        "id": 311,
                        "name": "תקרה פנים",
                        "hw": "DIMMABLE_SWITCH",
                        "type": "SWITCH",
                    },
                ],
            },
            {
                "name": "מרפסת כניסה",
                "items": [
                    {
                        "id": 112,
                        "name": "ספוטים",
                        "hw": "DIMMABLE_SWITCH",
                        "type": "SWITCH",
                    },
                    {
                        "id": 141,
                        "name": "כניסה",
                        "hw": "DIMMABLE_SWITCH",
                        "type": "SWITCH",
                    },
                    {
                        "id": 142,
                        "name": "שקוע רצפה",
                        "hw": "DIMMABLE_SWITCH",
                        "type": "SWITCH",
                    },
                    {
                        "id": 111,
                        "name": "שרשרת",
                        "hw": "DIMMABLE_SWITCH",
                        "type": "SWITCH",
                    },
                    {
                        "id": 502,
                        "name": "מדרגות",
                        "hw": "DIMMABLE_SWITCH",
                        "type": "SWITCH",
                    },
                ],
            },
            {
                "name": "חדר שינה מערבי",
                "items": [
                    {
                        "id": 353,
                        "name": "קיר שמאל",
                        "hw": "DIMMABLE_SWITCH",
                        "type": "SWITCH",
                    },
                    {
                        "id": 351,
                        "name": "קיר ימין",
                        "hw": "DIMMABLE_SWITCH",
                        "type": "SWITCH",
                    },
                    {
                        "id": 352,
                        "name": "תאורת תקרה",
                        "hw": "DIMMABLE_SWITCH",
                        "type": "SWITCH",
                    },
                    {
                        "id": 372,
                        "name": "חלון מערבי",
                        "hw": "SHUTTER",
                        "type": "SHUTTER",
                    },
                    {
                        "id": 371,
                        "name": "חלון דרומי",
                        "hw": "SHUTTER",
                        "type": "SHUTTER",
                    },
                ],
            },
            {
                "name": "חוץ",
                "items": [
                    {
                        "id": 381,
                        "name": "אפ/דאון דרומי",
                        "hw": "DIMMABLE_SWITCH",
                        "type": "SWITCH",
                    },
                    {
                        "id": 442,
                        "name": "פרוז'קטורים צפון",
                        "hw": "DIMMABLE_SWITCH",
                        "type": "SWITCH",
                    },
                    {
                        "id": 441,
                        "name": "פרוז'קטורים מערב",
                        "hw": "DIMMABLE_SWITCH",
                        "type": "SWITCH",
                    },
                    {
                        "id": 452,
                        "name": "פרוז'קטורים מערב",
                        "hw": "DIMMABLE_SWITCH",
                        "type": "SWITCH",
                    },
                    {
                        "id": 451,
                        "name": "פרוז'קטורים מזרח",
                        "hw": "DIMMABLE_SWITCH",
                        "type": "SWITCH",
                    },
                    {
                        "id": 382,
                        "name": "אפ/דאון צפוני",
                        "hw": "DIMMABLE_SWITCH",
                        "type": "SWITCH",
                    },
                    {
                        "id": 462,
                        "name": "אפ/דאון מערבי",
                        "hw": "DIMMABLE_SWITCH",
                        "type": "SWITCH",
                    },
                    {
                        "id": 461,
                        "name": "אפ/דאון מזרחי",
                        "hw": "DIMMABLE_SWITCH",
                        "type": "SWITCH",
                    },
                    {
                        "operations": [442, 441, 452, 451],
                        "id": 100400,
                        "name": "פרוז׳קטורים",
                        "hw": "VIRTUAL",
                        "type": "GROUP_SWITCH",
                    },
                ],
            },
            {
                "name": "גדר",
                "items": [
                    {
                        "id": 391,
                        "name": "אפ/דאון גדר פנים מזרח",
                        "hw": "DIMMABLE_SWITCH",
                        "type": "SWITCH",
                    },
                    {
                        "id": 392,
                        "name": "אפ/דאון גדר פנים צפון",
                        "hw": "DIMMABLE_SWITCH",
                        "type": "SWITCH",
                    },
                    {
                        "id": 401,
                        "name": "ספוטים מזרחיים",
                        "hw": "DIMMABLE_SWITCH",
                        "type": "SWITCH",
                    },
                    {
                        "id": 483,
                        "name": "אפ/דאון שער חוץ",
                        "hw": "DIMMABLE_SWITCH",
                        "type": "SWITCH",
                    },
                    {
                        "id": 482,
                        "name": "אפ/דאון כניסה חוץ",
                        "hw": "DIMMABLE_SWITCH",
                        "type": "SWITCH",
                    },
                    {
                        "id": 491,
                        "name": "ספוטים כניסה",
                        "hw": "DIMMABLE_SWITCH",
                        "type": "SWITCH",
                    },
                    {
                        "id": 402,
                        "name": "ספוטים צפון",
                        "hw": "DIMMABLE_SWITCH",
                        "type": "SWITCH",
                    },
                    {
                        "id": 493,
                        "name": "אפ דאון מערב",
                        "hw": "DIMMABLE_SWITCH",
                        "type": "SWITCH",
                    },
                ],
            },
            {
                "name": "סצנות",
                "items": [
                    {
                        "operations": [142, 381, 382, 462, 461, 483, 482],
                        "id": 100310,
                        "name": "תאורת חוץ",
                        "hw": "VIRTUAL",
                        "type": "GROUP_SWITCH",
                    },
                    {
                        "operations": [
                            {"itemId": 21, "value": 100},
                            {"itemId": 22, "value": 100},
                            {"itemId": 1, "value": 100},
                            {"itemId": 2, "value": 100},
                            {"itemId": 31, "value": 100},
                            {"itemId": 41, "value": 100},
                        ],
                        "id": 100350,
                        "name": "פתיחת חלונות קומה 1",
                        "hw": "VIRTUAL",
                        "type": "SCENARIO",
                    },
                    {
                        "operations": [
                            {"itemId": 21, "value": 0},
                            {"itemId": 22, "value": 0},
                            {"itemId": 1, "value": 0},
                            {"itemId": 2, "value": 0},
                            {"itemId": 31, "value": 0},
                            {"itemId": 41, "value": 0},
                            {"itemId": 201, "value": 0},
                            {"itemId": 421, "value": 0},
                            {"itemId": 411, "value": 0},
                            {"itemId": 262, "value": 0},
                            {"itemId": 261, "value": 0},
                            {"itemId": 372, "value": 0},
                            {"itemId": 371, "value": 0},
                        ],
                        "id": 62,
                        "name": "סגירת חלונות",
                        "hw": "DIMMABLE_SWITCH",
                        "type": "SCENARIO",
                    },
                    {
                        "operations": [
                            {"itemId": 21, "value": 0},
                            {"itemId": 22, "value": 0},
                            {"itemId": 1, "value": 0},
                            {"itemId": 2, "value": 0},
                            {"itemId": 31, "value": 0},
                            {"itemId": 41, "value": 0},
                        ],
                        "id": 100360,
                        "name": "סגירת חלונות קומה 1",
                        "hw": "VIRTUAL",
                        "type": "SCENARIO",
                    },
                    {
                        "operations": [
                            {"itemId": 201, "value": 0},
                            {"itemId": 421, "value": 0},
                            {"itemId": 411, "value": 0},
                            {"itemId": 262, "value": 0},
                            {"itemId": 261, "value": 0},
                            {"itemId": 372, "value": 0},
                            {"itemId": 371, "value": 0},
                        ],
                        "id": 100370,
                        "name": "סגירת חלונות קומה 2",
                        "hw": "VIRTUAL",
                        "type": "SCENARIO",
                    },
                    {
                        "operations": [
                            {"itemId": 201, "value": 100},
                            {"itemId": 421, "value": 100},
                            {"itemId": 411, "value": 100},
                            {"itemId": 262, "value": 100},
                            {"itemId": 261, "value": 100},
                            {"itemId": 372, "value": 100},
                            {"itemId": 371, "value": 100},
                        ],
                        "id": 100380,
                        "name": "פתיחת חלונות קומה 2",
                        "hw": "VIRTUAL",
                        "type": "SCENARIO",
                    },
                    {
                        "operations": [511, 531],
                        "id": 100440,
                        "name": "מדרגות",
                        "hw": "VIRTUAL",
                        "type": "GROUP_SWITCH",
                    },
                    {
                        "operations": [
                            {"itemId": 21, "value": 33},
                            {"itemId": 22, "value": 30},
                            {"itemId": 1, "value": 34},
                            {"itemId": 2, "value": 32},
                            {"itemId": 31, "value": 30},
                            {"itemId": 41, "value": 35},
                        ],
                        "id": 61,
                        "name": "שלב אור קומה 1",
                        "hw": "DIMMABLE_SWITCH",
                        "type": "SCENARIO",
                    },
                    {
                        "operations": [
                            {"itemId": 121, "value": 0},
                            {"itemId": 182, "value": 0},
                            {"itemId": 561, "value": 0},
                            {"itemId": 181, "value": 0},
                            {"itemId": 21, "value": 0},
                            {"itemId": 22, "value": 0},
                            {"itemId": 71, "value": 0},
                            {"itemId": 593, "value": 0},
                            {"itemId": 592, "value": 0},
                            {"itemId": 591, "value": 0},
                            {"itemId": 11, "value": 0},
                            {"itemId": 1, "value": 0},
                            {"itemId": 2, "value": 0},
                            {"itemId": 12, "value": 0},
                            {"itemId": 132, "value": 0},
                            {"itemId": 131, "value": 0},
                            {"itemId": 31, "value": 0},
                            {"itemId": 41, "value": 0},
                            {"itemId": 91, "value": 0},
                            {"itemId": 581, "value": 0},
                            {"itemId": 171, "value": 0},
                            {"itemId": 102, "value": 0},
                            {"itemId": 101, "value": 0},
                            {"itemId": 343, "value": 0},
                            {"itemId": 341, "value": 0},
                            {"itemId": 191, "value": 0},
                            {"itemId": 192, "value": 0},
                            {"itemId": 201, "value": 0},
                            {"itemId": 432, "value": 0},
                            {"itemId": 433, "value": 0},
                            {"itemId": 421, "value": 0},
                            {"itemId": 431, "value": 0},
                            {"itemId": 551, "value": 0},
                            {"itemId": 413, "value": 0},
                            {"itemId": 411, "value": 0},
                            {"itemId": 221, "value": 0},
                            {"itemId": 251, "value": 0},
                            {"itemId": 262, "value": 0},
                            {"itemId": 261, "value": 0},
                            {"itemId": 212, "value": 0},
                            {"itemId": 231, "value": 0},
                            {"itemId": 211, "value": 0},
                            {"itemId": 301, "value": 0},
                            {"itemId": 302, "value": 0},
                            {"itemId": 601, "value": 0},
                            {"itemId": 152, "value": 0},
                            {"itemId": 151, "value": 0},
                            {"itemId": 311, "value": 0},
                            {"itemId": 353, "value": 0},
                            {"itemId": 351, "value": 0},
                            {"itemId": 352, "value": 0},
                            {"itemId": 372, "value": 0},
                            {"itemId": 371, "value": 0},
                            {"itemId": 511, "value": 0},
                            {"itemId": 512, "value": 0},
                            {"itemId": 513, "value": 0},
                            {"itemId": 531, "value": 0},
                            {"itemId": 523, "value": 0},
                            {"itemId": 522, "value": 0},
                            {"itemId": 521, "value": 0},
                            {"itemId": 542, "value": 0},
                        ],
                        "id": 100540,
                        "name": "Good Nigh",
                        "hw": "VIRTUAL",
                        "type": "SCENARIO",
                    },
                ],
            },
            {
                "name": "קומה 3",
                "items": [
                    {
                        "id": 511,
                        "name": "קיר מדרגות",
                        "hw": "DIMMABLE_SWITCH",
                        "type": "SWITCH",
                    },
                    {
                        "id": 512,
                        "name": "תקרה (מ.כביסה)",
                        "hw": "DIMMABLE_SWITCH",
                        "type": "SWITCH",
                    },
                    {
                        "id": 513,
                        "name": "תקרה",
                        "hw": "DIMMABLE_SWITCH",
                        "type": "SWITCH",
                    },
                    {
                        "id": 531,
                        "name": "תקרה (מדרגות)",
                        "hw": "DIMMABLE_SWITCH",
                        "type": "SWITCH",
                    },
                ],
            },
            {
                "name": "גג",
                "items": [
                    {
                        "id": 523,
                        "name": "פרוז׳קטור צפון",
                        "hw": "DIMMABLE_SWITCH",
                        "type": "SWITCH",
                    },
                    {
                        "id": 522,
                        "name": "פרוז׳קטור מזרח",
                        "hw": "DIMMABLE_SWITCH",
                        "type": "SWITCH",
                    },
                    {
                        "id": 521,
                        "name": "פרוז׳קטור דרום",
                        "hw": "DIMMABLE_SWITCH",
                        "type": "SWITCH",
                    },
                ],
            },
            {
                "name": "חדר שינה מזרחי",
                "items": [
                    {
                        "id": 542,
                        "name": "תקרה",
                        "hw": "DIMMABLE_SWITCH",
                        "type": "SWITCH",
                    }
                ],
            },
        ],
    },
}

MOCK_FAILED_TO_LOGIN_MSG = (
    "Central Unit replied with failure: {'status': 'LOGIN_FAILED'}"
)
MOCK_INVALID_TOKEN_MGS = "Error fetching switchbee data: Error communicating with API: data Request failed due to INVALID_TOKEN, trying to re-login"
