#!/bin/sh

set -e

echo "Installing homebridge..."

APP_PATH=`pwd`
HASS_PATH=`which hass`
USER_NAME=`whoami`

cp scripts/org.home-assistant.plist ~/Library/LaunchAgents/org.home-assistant.plist

sed -i '' -e "s#%USER%#$USER_NAME#g" ~/Library/LaunchAgents/org.home-assistant.plist
sed -i '' -e "s#%PATH%#$APP_PATH#g" ~/Library/LaunchAgents/org.home-assistant.plist
sed -i '' -e "s#%HASS_PATH%#$HASS_PATH#g" ~/Library/LaunchAgents/org.home-assistant.plist

launchctl load -w -F ~/Library/LaunchAgents/org.home-assistant.plist
