"""Tests for the Electric Kiwi integration."""
CLIENT_ID = "1234"
CLIENT_SECRET = "5678"
REDIRECT_URI = "https://example.com/auth/external/callback"
SCOPES = "read_connection_detail+read_billing_frequency+read_account_running_balance+read_consumption_summary+read_consumption_averages+read_hop_intervals_config+read_hop_connection+save_hop_connection+read_session"
