"""Hass.io const variables."""

DOMAIN = "hassio"

ATTR_ADDON = "addon"
ATTR_ADDONS = "addons"
ATTR_ADMIN = "admin"
ATTR_CONFIG = "config"
ATTR_DISCOVERY = "discovery"
ATTR_ENABLE = "enable"
ATTR_FOLDERS = "folders"
ATTR_HOMEASSISTANT = "homeassistant"
ATTR_ICON = "icon"
ATTR_INPUT = "input"
ATTR_NAME = "name"
ATTR_PANELS = "panels"
ATTR_PASSWORD = "password"
ATTR_SERVICE = "service"
ATTR_SNAPSHOT = "snapshot"
ATTR_TITLE = "title"
ATTR_USERNAME = "username"
ATTR_UUID = "uuid"
ATTR_WS_EVENT = "event"

X_HASSIO = "X-Hassio-Key"
X_INGRESS_PATH = "X-Ingress-Path"
X_HASS_USER_ID = "X-Hass-User-ID"
X_HASS_IS_ADMIN = "X-Hass-Is-Admin"


WS_TYPE = "type"
WS_DATA = "data"
WS_ID = "id"
WS_TYPE_EVENT = "supervisor/event"
WS_TYPE_SNAPSHOT_NEW_FULL = "supervisor/snapshots/new/full"
WS_TYPE_SNAPSHOT_NEW_PARTIAL = "supervisor/snapshots/new/partial"

EVENT_SUPERVISOR_EVENT = "supervisor_event"
