"""Constants for the yolink integration."""

DOMAIN = "yolink"
MANUFACTURER = "YoLink"
HOME_ID = "homeId"
HOME_SUBSCRIPTION = "home_subscription"
ATTR_PLATFORM_SENSOR = "sensor"
ATTR_DEVICE = "devices"
ATTR_DEVICE_TYPE = "type"
ATTR_CLIENT = "client"
ATTR_MQTT_CLIENT = "mqtt_client"
ATTR_DEVICE_ID = "deviceId"
ATTR_DEVICE_DOOR_SENSOR = "DoorSensor"
