"""Constants for the yolink integration."""

DOMAIN = "yolink"
MANUFACTURER = "YoLink"
HOME_ID = "homeId"
ATTR_HOME_INSTANCE = "home_instance"
ATTR_COORDINATORS = "coordinators"
ATTR_DEVICE = "devices"
ATTR_DEVICE_TYPE = "type"
ATTR_DEVICE_NAME = "name"
ATTR_DEVICE_STATE = "state"
ATTR_DEVICE_ID = "deviceId"
