play_media:
  target:
    entity:
      integration: jellyfin
      domain: media_player
  fields:
    media:
      required: true
      selector:
        media:
      example: '{"media_content_id": "https://home-assistant.io/images/cast/splash.png", "media_content_type": "music"}'
    enqueue:
      required: false
      selector:
        select:
          options:
            - "play"
            - "next"
            - "add"
            - "replace"
          translation_key: enqueue
    shuffle:
      required: false
      default: false
      selector:
        boolean:
