config_entry:
  versions:
    - version:
        major: 1
        minor: 2
      data:
        fields: {}
      options:
        fields:
          entity_id:
            required: false
            selector:
              text: {}
          hysteresis:
            required: false
            selector:
              text: {}
          lower:
            required: false
            selector:
              text: {}
          name:
            required: false
            selector:
              text: {}
          upper:
            required: false
            selector:
              text: {}
  subentries: {}
