config_entry:
  versions:
    - version:
        major: 1
        minor: 1
      data:
        fields:
          location:
            required: false
            selector:
              text: {}
      options:
        fields:
          language_override:
            required: false
            selector:
              text: {}
  subentries: {}
