set_cover_position_and_tilt:
  target:
    entity:
      integration: wmspro
      domain: cover
      supported_features:
        - - cover.CoverEntityFeature.SET_POSITION
          - cover.CoverEntityFeature.SET_TILT_POSITION
  fields:
    position:
      required: true
      selector:
        number:
          translation_key: "position"
          min: 0
          max: 100
          mode: slider
          unit_of_measurement: "%"
    tilt_position:
      required: true
      selector:
        number:
          translation_key: "tilt_position"
          min: 0
          max: 100
          mode: slider
          unit_of_measurement: "%"
