toggle_shade:
  target:
    entity:
      domain: cover
      integration: powershades

set_upper_limit:
  target:
    entity:
      domain: cover
      integration: powershades

set_lower_limit:
  target:
    entity:
      domain: cover
      integration: powershades

clear_limits:
  target:
    entity:
      domain: cover
      integration: powershades

step_up:
  target:
    entity:
      domain: cover
      integration: powershades

step_down:
  target:
    entity:
      domain: cover
      integration: powershades

jog_up:
  target:
    entity:
      domain: cover
      integration: powershades

jog_down:
  target:
    entity:
      domain: cover
      integration: powershades

set_shade_name:
  target:
    entity:
      domain: cover
      integration: powershades
  fields:
    name:
      required: true
      example: "Living Room Left"
      selector:
        text:
