"""WebSocket API commands for the Span Panel integration."""

from __future__ import annotations

from typing import TYPE_CHECKING, Any

import voluptuous as vol

from homeassistant.components import websocket_api
from homeassistant.config_entries import ConfigEntryState
from homeassistant.core import HomeAssistant
from homeassistant.helpers import device_registry as dr, entity_registry as er

from .const import DOMAIN

if TYPE_CHECKING:
    from . import SpanPanelRuntimeData

# Mapping from unique_id suffixes to semantic role names for circuit sensors.
# Mapping from unique_id suffixes (as generated by build_circuit_unique_id via
# get_user_friendly_suffix) to semantic role names used in the topology response.
# NOTE: build_circuit_unique_id maps API keys through CIRCUIT_SUFFIX_MAPPING,
# so unique_ids end with e.g. "_power" not "_instantPowerW".
_SENSOR_ROLE_SUFFIXES: dict[str, str] = {
    "_power": "power",
    "_energy_produced": "produced_energy",
    "_energy_consumed": "consumed_energy",
    "_energy_net": "net_energy",
    "_current": "current",
    "_breaker_rating": "breaker_rating",
}


def async_register_commands(hass: HomeAssistant) -> None:
    """Register WebSocket commands for the Span Panel integration."""
    websocket_api.async_register_command(hass, handle_panel_topology)


@websocket_api.websocket_command(
    {
        vol.Required("type"): "span_panel/panel_topology",
        vol.Required("device_id"): str,
    }
)
@websocket_api.require_admin
@websocket_api.async_response
async def handle_panel_topology(
    hass: HomeAssistant,
    connection: websocket_api.ActiveConnection,
    msg: dict[str, Any],
) -> None:
    """Return the full panel topology with entity mappings.

    Admin users must pass the HA device registry ID for the **main SPAN panel**
    device only (not BESS/EVSE sub-devices). Returns panel metadata, circuits
    with tabs/entity mappings, and sub-devices (BESS, EVSE).
    """
    device_id = msg["device_id"]

    device_registry = dr.async_get(hass)
    device_entry = device_registry.async_get(device_id)

    if device_entry is None:
        connection.send_error(msg["id"], "device_not_found", "Device not found")
        return

    is_span_device = any(domain == DOMAIN for domain, _ in device_entry.identifiers)
    if not is_span_device:
        connection.send_error(
            msg["id"], "not_span_panel", "Device is not a SPAN Panel device"
        )
        return

    # Sub-devices (BESS, EVSE) register with via_device_id pointing at the panel.
    if device_entry.via_device_id is not None:
        connection.send_error(
            msg["id"],
            "not_panel_device",
            "Use the SPAN panel device registry ID, not a BESS or EVSE sub-device.",
        )
        return

    # Find the config entry for this device.
    config_entry_id = _find_config_entry_id(device_entry)
    if config_entry_id is None:
        connection.send_error(
            msg["id"], "not_span_panel", "Device is not a SPAN Panel device"
        )
        return

    config_entry = hass.config_entries.async_get_entry(config_entry_id)
    if config_entry is None:
        connection.send_error(
            msg["id"], "not_loaded", "SPAN Panel config entry not found"
        )
        return

    if config_entry.state is not ConfigEntryState.LOADED:
        connection.send_error(
            msg["id"], "not_loaded", "SPAN Panel integration is not loaded"
        )
        return

    runtime_data: SpanPanelRuntimeData = config_entry.runtime_data
    coordinator = runtime_data.coordinator
    snapshot = coordinator.data

    # Build entity lookup grouped by device_id for sub-device section.
    entity_registry = er.async_get(hass)
    all_entities = er.async_entries_for_config_entry(entity_registry, config_entry_id)

    entities_by_device: dict[str, list[er.RegistryEntry]] = {}
    for entity in all_entities:
        if entity.device_id:
            entities_by_device.setdefault(entity.device_id, []).append(entity)

    # Single pass over all entities to build circuit_id to role to entity_id
    # map. EVSE feed circuit sensors live on the EVSE sub-device, so we
    # search all entities for the config entry, not just panel-device ones.
    circuit_ids = {
        cid for cid in snapshot.circuits if not cid.startswith("unmapped_tab_")
    }
    entity_map = _build_circuit_entity_map(circuit_ids, all_entities)

    # Build circuits section.
    circuits: dict[str, dict[str, Any]] = {}
    for circuit_id, circuit in snapshot.circuits.items():
        if circuit_id not in circuit_ids:
            continue

        tabs = sorted(circuit.tabs) if circuit.tabs else []
        circuits[circuit_id] = {
            "tabs": tabs,
            "name": circuit.name or None,
            "voltage": 240 if len(tabs) == 2 else 120,
            "device_type": circuit.device_type,
            "relay_state": circuit.relay_state,
            "is_user_controllable": circuit.is_user_controllable,
            "breaker_rating_a": circuit.breaker_rating_a,
            "entities": entity_map.get(circuit_id, {}),
        }

    # Build sub-devices section from devices linked via via_device_id.
    sub_devices: dict[str, dict[str, Any]] = {}

    for dev in dr.async_entries_for_config_entry(device_registry, config_entry_id):
        if dev.id == device_id:
            continue
        if dev.via_device_id != device_id:
            continue

        sub_device_entities = entities_by_device.get(dev.id, [])
        sub_device_type = _classify_sub_device(dev)

        sub_devices[dev.id] = {
            "name": dev.name,
            "type": sub_device_type,
            "manufacturer": dev.manufacturer,
            "model": dev.model,
            "serial_number": dev.serial_number,
            "sw_version": dev.sw_version,
            "entities": {
                ent.entity_id: {
                    "domain": ent.domain,
                    "original_name": ent.original_name,
                    "unique_id": ent.unique_id,
                }
                for ent in sub_device_entities
            },
        }

    connection.send_result(
        msg["id"],
        {
            "serial": snapshot.serial_number,
            "firmware": snapshot.firmware_version,
            "panel_size": snapshot.panel_size,
            "device_id": device_id,
            "device_name": device_entry.name,
            "circuits": circuits,
            "sub_devices": sub_devices,
        },
    )


def _find_config_entry_id(device_entry: dr.DeviceEntry) -> str | None:
    """Find the SPAN Panel config entry ID for a device."""
    is_span_device = any(domain == DOMAIN for domain, _ in device_entry.identifiers)
    if not is_span_device:
        return None

    # Return the first config entry; a SPAN device only belongs to one.
    for config_entry_id in device_entry.config_entries:
        return config_entry_id
    return None


def _classify_sub_device(device_entry: dr.DeviceEntry) -> str:
    """Classify a sub-device as 'bess' or 'evse' based on its identifiers."""
    for _, identifier in device_entry.identifiers:
        if "_bess" in identifier:
            return "bess"
        if "_evse_" in identifier:
            return "evse"
    return "unknown"


def _build_circuit_entity_map(
    circuit_ids: set[str],
    entities: list[er.RegistryEntry],
) -> dict[str, dict[str, str]]:
    """Build a circuit_id to {role: entity_id} map in a single pass.

    Iterates over entities once, matching each to a circuit by checking
    whether its unique_id contains a known circuit UUID.
    """
    result: dict[str, dict[str, str]] = {}

    for entity in entities:
        uid = entity.unique_id

        # Skip entities without a unique_id, as we cannot reliably match them.
        if not uid:
            continue

        # Find which circuit this entity belongs to.
        matched_circuit_id: str | None = None
        for cid in circuit_ids:
            # Avoid plain substring matching to prevent collisions like "1" in "15".
            idx = uid.find(cid)
            if idx == -1:
                continue

            # Require delimiters (or string boundaries) around the circuit_id.
            before_ok = idx == 0 or uid[idx - 1] in "_-"
            after_index = idx + len(cid)
            after_ok = after_index == len(uid) or uid[after_index] in "_-"

            if before_ok and after_ok:
                matched_circuit_id = cid
                break

        if matched_circuit_id is None:
            continue

        mapped = result.setdefault(matched_circuit_id, {})

        if entity.domain == "switch":
            mapped["switch"] = entity.entity_id
        elif entity.domain == "select":
            mapped["select"] = entity.entity_id
        elif entity.domain == "sensor":
            role = _classify_sensor_role(uid)
            if role:
                mapped[role] = entity.entity_id

    return result


def _classify_sensor_role(unique_id: str) -> str | None:
    """Classify a sensor's role from its unique_id suffix."""
    for suffix, role in _SENSOR_ROLE_SUFFIXES.items():
        if unique_id.endswith(suffix):
            return role
    return None
