get_codes:
  target:
    entity:
      domain: lock
      integration: schlage

add_code:
  target:
    entity:
      domain: lock
      integration: schlage
  fields:
    name:
      required: true
      example: "Example Person"
      selector:
        text:
          multiline: false
    code:
      required: true
      example: "1111"
      selector:
        text:
          multiline: false
          type: password
    notify_on_use:
      required: false
      default: true
      selector:
        boolean:
    start_datetime:
      required: false
      example: "2024-12-25 18:00:00"
      selector:
        datetime:
    end_datetime:
      required: false
      example: "2024-12-26 08:00:00"
      selector:
        datetime:

delete_code:
  target:
    entity:
      domain: lock
      integration: schlage
  fields:
    name:
      required: true
      example: "Example Person"
      selector:
        text:
          multiline: false
