get_codes:
  target:
    entity:
      integration: schlage
      domain: lock
add_code:
  target:
    entity:
      integration: schlage
      domain: lock
  fields:
    name:
      required: true
      example: "Example Person"
      selector:
        text:
          multiline: false
    code:
      required: true
      example: "1111"
      selector:
        text:
          multiline: false
          type: password
    notify_on_use:
      required: false
      default: true
      selector:
        boolean:
    start_datetime:
      required: false
      example: "2026-09-01 15:00"
      selector:
        datetime:
    end_datetime:
      required: false
      example: "2026-09-01 16:00"
      selector:
        datetime:
delete_code:
  target:
    entity:
      integration: schlage
      domain: lock
  fields:
    name:
      required: false
      example: "Example Person"
      selector:
        text:
          multiline: false
    access_code_id:
      required: false
      example: "abc123"
      selector:
        text:
          multiline: false
update_code:
  target:
    entity:
      integration: schlage
      domain: lock
  fields:
    access_code_id:
      required: true
      example: "abc123"
      selector:
        text:
          multiline: false
    name:
      required: false
      example: "Example Person"
      selector:
        text:
          multiline: false
    code:
      required: false
      example: "1111"
      selector:
        text:
          multiline: false
    notify_on_use:
      required: false
      selector:
        boolean:
    disabled:
      required: false
      selector:
        boolean:
    start_datetime:
      required: false
      example: "2026-09-01 15:00"
      selector:
        datetime:
    end_datetime:
      required: false
      example: "2026-09-01 16:00"
      selector:
        datetime:
