"""Constants for the Amazon Polly text to speech service."""

from __future__ import annotations

from typing import Final

CONF_REGION: Final = "region_name"
CONF_ACCESS_KEY_ID: Final = "aws_access_key_id"
CONF_SECRET_ACCESS_KEY: Final = "aws_secret_access_key"

DEFAULT_REGION: Final = "us-east-1"
SUPPORTED_REGIONS: Final[list[str]] = [
    "af-south-1",
    "ap-east-1",
    "ap-northeast-1",
    "ap-northeast-2",
    "ap-northeast-3",
    "ap-south-1",
    "ap-south-2",
    "ap-southeast-1",
    "ap-southeast-2",
    "ap-southeast-3",
    "ap-southeast-4",
    "ca-central-1",
    "ca-west-1",
    "eu-central-1",
    "eu-central-2",
    "eu-north-1",
    "eu-south-1",
    "eu-south-2",
    "eu-west-1",
    "eu-west-2",
    "eu-west-3",
    "il-central-1",
    "me-central-1",
    "me-south-1",
    "sa-east-1",
    "us-east-1",
    "us-east-2",
    "us-gov-east-1",
    "us-gov-west-1",
    "us-west-1",
    "us-west-2",
]

CONF_ENGINE: Final = "engine"
CONF_VOICE: Final = "voice"
CONF_OUTPUT_FORMAT: Final = "output_format"
CONF_SAMPLE_RATE: Final = "sample_rate"
CONF_TEXT_TYPE: Final = "text_type"

# list of supported voices generated by voices.py script
SUPPORTED_VOICES: Final[list[str]] = [
    "Aditi",  # Indian English (en-IN)
    "Adriano",  # Italian (it-IT)
    "Amy",  # British English (en-GB)
    "Andres",  # Mexican Spanish (es-MX)
    "Aria",  # New Zealand English (en-NZ)
    "Arlet",  # Catalan (ca-ES)
    "Arthur",  # British English (en-GB)
    "Astrid",  # Swedish (sv-SE)
    "Ayanda",  # South African English (en-ZA)
    "Bianca",  # Italian (it-IT)
    "Brian",  # British English (en-GB)
    "Burcu",  # Turkish (tr-TR)
    "Camila",  # Brazilian Portuguese (pt-BR)
    "Carla",  # Italian (it-IT)
    "Carmen",  # Romanian (ro-RO)
    "Celine",  # French (fr-FR)
    "Chantal",  # Canadian French (fr-CA)
    "Conchita",  # Castilian Spanish (es-ES)
    "Cristiano",  # Portuguese (pt-PT)
    "Daniel",  # German (de-DE)
    "Danielle",  # US English (en-US)
    "Dora",  # Icelandic (is-IS)
    "Elin",  # Swedish (sv-SE)
    "Emma",  # British English (en-GB)
    "Enrique",  # Castilian Spanish (es-ES)
    "Ewa",  # Polish (pl-PL)
    "Filiz",  # Turkish (tr-TR)
    "Gabrielle",  # Canadian French (fr-CA)
    "Geraint",  # Welsh English (en-GB-WLS)
    "Giorgio",  # Italian (it-IT)
    "Gregory",  # US English (en-US)
    "Gwyneth",  # Welsh (cy-GB)
    "Hala",  # Gulf Arabic (ar-AE)
    "Hannah",  # Austrian German (de-AT)
    "Hans",  # German (de-DE)
    "Hiujin",  # Cantonese (yue-CN)
    "Ida",  # Norwegian (nb-NO)
    "Ines",  # Portuguese (pt-PT)
    "Isabelle",  # Belgian French (fr-BE)
    "Ivy",  # US English (en-US)
    "Jacek",  # Polish (pl-PL)
    "Jan",  # Polish (pl-PL)
    "Joanna",  # US English (en-US)
    "Joey",  # US English (en-US)
    "Justin",  # US English (en-US)
    "Kajal",  # Indian English (en-IN)
    "Karl",  # Icelandic (is-IS)
    "Kazuha",  # Japanese (ja-JP)
    "Kendra",  # US English (en-US)
    "Kevin",  # US English (en-US)
    "Kimberly",  # US English (en-US)
    "Laura",  # Dutch (nl-NL)
    "Lea",  # French (fr-FR)
    "Liam",  # Canadian French (fr-CA)
    "Lisa",  # Belgian Dutch (nl-BE)
    "Liv",  # Norwegian (nb-NO)
    "Lotte",  # Dutch (nl-NL)
    "Lucia",  # Castilian Spanish (es-ES)
    "Lupe",  # US Spanish (es-US)
    "Mads",  # Danish (da-DK)
    "Maja",  # Polish (pl-PL)
    "Marlene",  # German (de-DE)
    "Mathieu",  # French (fr-FR)
    "Matthew",  # US English (en-US)
    "Maxim",  # Russian (ru-RU)
    "Mia",  # Mexican Spanish (es-MX)
    "Miguel",  # US Spanish (es-US)
    "Mizuki",  # Japanese (ja-JP)
    "Naja",  # Danish (da-DK)
    "Niamh",  # Irish English (en-IE)
    "Nicole",  # Australian English (en-AU)
    "Ola",  # Polish (pl-PL)
    "Olivia",  # Australian English (en-AU)
    "Pedro",  # US Spanish (es-US)
    "Penelope",  # US Spanish (es-US)
    "Raveena",  # Indian English (en-IN)
    "Remi",  # French (fr-FR)
    "Ricardo",  # Brazilian Portuguese (pt-BR)
    "Ruben",  # Dutch (nl-NL)
    "Russell",  # Australian English (en-AU)
    "Ruth",  # US English (en-US)
    "Salli",  # US English (en-US)
    "Seoyeon",  # Korean (ko-KR)
    "Sergio",  # Castilian Spanish (es-ES)
    "Sofie",  # Danish (da-DK)
    "Stephen",  # US English (en-US)
    "Suvi",  # Finnish (fi-FI)
    "Takumi",  # Japanese (ja-JP)
    "Tatyana",  # Russian (ru-RU)
    "Thiago",  # Brazilian Portuguese (pt-BR)
    "Tomoko",  # Japanese (ja-JP)
    "Vicki",  # German (de-DE)
    "Vitoria",  # Brazilian Portuguese (pt-BR)
    "Zayd",  # Gulf Arabic (ar-AE)
    "Zeina",  # Arabic (arb)
    "Zhiyu",  # Chinese Mandarin (cmn-CN)
]

SUPPORTED_OUTPUT_FORMATS: Final[list[str]] = ["mp3", "ogg_vorbis", "pcm"]

SUPPORTED_ENGINES: Final[list[str]] = ["generative", "long-form", "neural", "standard"]

SUPPORTED_SAMPLE_RATES: Final[list[str]] = ["8000", "16000", "22050", "24000"]

SUPPORTED_SAMPLE_RATES_MAP: Final[dict[str, list[str]]] = {
    "mp3": ["8000", "16000", "22050", "24000"],
    "ogg_vorbis": ["8000", "16000", "22050"],
    "pcm": ["8000", "16000"],
}

SUPPORTED_TEXT_TYPES: Final[list[str]] = ["text", "ssml"]

CONTENT_TYPE_EXTENSIONS: Final[dict[str, str]] = {
    "audio/mpeg": "mp3",
    "audio/ogg": "ogg",
    "audio/pcm": "pcm",
}

DEFAULT_ENGINE: Final = "standard"
DEFAULT_VOICE: Final = "Joanna"
DEFAULT_OUTPUT_FORMAT: Final = "mp3"
DEFAULT_TEXT_TYPE: Final = "text"

DEFAULT_SAMPLE_RATES: Final[dict[str, str]] = {
    "mp3": "22050",
    "ogg_vorbis": "22050",
    "pcm": "16000",
}

AWS_CONF_CONNECT_TIMEOUT: Final = 10
AWS_CONF_READ_TIMEOUT: Final = 5
AWS_CONF_MAX_POOL_CONNECTIONS: Final = 1
