"""Constants for Airthings BLE."""

DOMAIN = "airthings_ble"
MFCT_ID = 820

VOLUME_BECQUEREL = "Bq/m³"
VOLUME_PICOCURIE = "pCi/L"

DEVICE_MODEL = "device_model"

DEFAULT_SCAN_INTERVAL = 300
RADON_SCAN_INTERVAL = 1800

MAX_RETRIES_AFTER_STARTUP = 5
