# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: wdl-event-importance.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'wdl-event-importance.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1awdl-event-importance.proto\x12\x03wdl*\xbe\x01\n\x0f\x45ventImportance\x12 \n\x1c\x45VENT_IMPORTANCE_UNSPECIFIED\x10\x00\x12(\n$EVENT_IMPORTANCE_PRODUCTION_CRITICAL\x10\x01\x12(\n$EVENT_IMPORTANCE_PRODUCTION_STANDARD\x10\x02\x12\x19\n\x15\x45VENT_IMPORTANCE_INFO\x10\x03\x12\x1a\n\x16\x45VENT_IMPORTANCE_DEBUG\x10\x04\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'wdl_event_importance_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EVENTIMPORTANCE']._serialized_start=36
  _globals['_EVENTIMPORTANCE']._serialized_end=226
# @@protoc_insertion_point(module_scope)
