config_entry:
  versions:
    - version:
        major: 1
        minor: 1
      data:
        fields: {}
      options:
        fields:
          enable_long_press:
            required: false
            selector:
              text: {}
          enable_subscription:
            required: false
            selector:
              text: {}
  subentries: {}
