get_prices:
  fields:
    config_entry_id:
      required: true
      selector:
        config_entry:
          integration: green_planet_energy
    hours:
      required: true
      selector:
        number:
          min: 0.25
          max: 24
          step: 0.25
          unit_of_measurement: hours
