# Describes the format for available Green Planet Energy services

get_cheapest_duration:
  fields:
    duration:
      required: true
      example: 2.5
      selector:
        number:
          min: 0.5
          max: 24
          step: 0.5
          unit_of_measurement: "h"
    time_range:
      required: false
      default: "full_day"
      selector:
        select:
          options:
            - label: Full day (00:00-24:00)
              value: "full_day"
            - label: Day (06:00-18:00)
              value: "day"
            - label: Night (18:00-06:00)
              value: "night"
