"""Constants for the tests for the feedreader component."""

from homeassistant.components.feedreader.const import (
    CONF_MAX_ENTRIES,
    DEFAULT_MAX_ENTRIES,
)
from homeassistant.const import CONF_URL

URL = "http://some.rss.local/rss_feed.xml"
# VALID_CONFIG_1 = {DOMAIN: {CONF_URLS: [URL]}}
# VALID_CONFIG_2 = {DOMAIN: {CONF_URLS: [URL], CONF_SCAN_INTERVAL: 60}}
# VALID_CONFIG_3 = {DOMAIN: {CONF_URLS: [URL], CONF_MAX_ENTRIES: 100}}
# VALID_CONFIG_4 = {DOMAIN: {CONF_URLS: [URL], CONF_MAX_ENTRIES: 5}}
# VALID_CONFIG_5 = {DOMAIN: {CONF_URLS: [URL], CONF_MAX_ENTRIES: 1}}

VALID_CONFIG_DEFAULT = {CONF_URL: URL, CONF_MAX_ENTRIES: DEFAULT_MAX_ENTRIES}
VALID_CONFIG_100 = {CONF_URL: URL, CONF_MAX_ENTRIES: 100}
VALID_CONFIG_5 = {CONF_URL: URL, CONF_MAX_ENTRIES: 5}
VALID_CONFIG_1 = {CONF_URL: URL, CONF_MAX_ENTRIES: 1}
