# Velux Integration services

set_velocity:
  fields:
    device_id:
      required: true
      selector:
        device:
          integration: velux
          entity:
            domain: cover
    velocity:
      required: true
      selector:
        select:
          options:
            - "default"
            - "silent"
            - "fast"
