"""Constants for the climaveneta_imxw integration."""
from datetime import timedelta

from homeassistant.const import Platform

DOMAIN = "climaveneta_imxw"

PLATFORMS = [Platform.CLIMATE, Platform.SENSOR]

DEFAULT_MODBUS_HUB = "modbus_hub"
DEFAULT_SERIAL_SLAVE_ID = 1

CONF_HUB_STRING = "Modbus hub name"

TIMEOUT = 60


ACTUAL_AIR_TEMPERATURE_REGISTER = 0x1002
ACTUAL_WATER_TEMPERATURE_REGISTER = 0x1004

STATE_READ_ON_OFF_REGISTER = 0x100F
STATE_READ_FAN_ONLY_REGISTER = 0x1010
STATE_READ_SEASON_REGISTER = 0x1013
STATE_READ_FAN_AUTO_REGISTER = 0x1017
STATE_READ_FAN_STOP_REGISTER = 0x1018
STATE_READ_FAN_MIN_SPEED_REGISTER = 0x1019
STATE_READ_FAN_MED_SPEED_REGISTER = 0x101A
STATE_READ_FAN_MAX_SPEED_REGISTER = 0x101B
STATE_READ_EV_WATER_REGISTER = 0x101C

ALARM_T1_REGISTER = 0x1028
ALARM_T3_REGISTER = 0x102A
ALARM_WATER_DRAIN_REGISTER = 0x102B

TARGET_TEMPERATURE_SUMMER_REGISTER = 0x102D
TARGET_TEMPERATURE_WINTER_REGISTER = 0x102E

STATE_WRITE_ON_OFF_REGISTER = 0x105C
STATE_WRITE_MODE_REGISTER = 0x105D
STATE_WRITE_FAN_SPEED_REGISTER = 0x105E

MODE_SUMMER = 0
MODE_WINTER = 1

MODE_OFF = 0
MODE_ON = 1


SCAN_INTERVAL = timedelta(seconds=30)
