config_entry:
  versions:
    - version:
        major: 1
        minor: 1
      data:
        fields:
          vedo_pin:
            required: false
            selector:
              text: {}
          host:
            required: true
            selector:
              text: {}
          port:
            required: true
            selector:
              text: {}
          pin:
            required: false
            selector:
              text: {}
          type:
            required: true
            selector:
              text: {}
      options:
        fields: {}
  subentries: {}
