"""Tests for Transmission."""

from homeassistant.const import (
    CONF_HOST,
    CONF_NAME,
    CONF_PASSWORD,
    CONF_PORT,
    CONF_USERNAME,
)

MOCK_CONFIG = {
    CONF_NAME: "Transmission",
    CONF_HOST: "1.2.3.4",
    CONF_USERNAME: "user",
    CONF_PASSWORD: "pass",
    CONF_PORT: 9091,
}

SESSION_FIELDS = {
    "alt-speed-down": 50,
    "alt-speed-enabled": False,
    "alt-speed-time-begin": 540,
    "alt-speed-time-day": 127,
    "alt-speed-time-enabled": False,
    "alt-speed-time-end": 1020,
    "alt-speed-up": 50,
    "blocklist-enabled": False,
    "blocklist-size": 0,
    "blocklist-url": "http://www.example.com/blocklist",
    "cache-size-mb": 4,
    "config-dir": "/data/transmission",
    "dht-enabled": True,
    "download-dir": "/share/downloads",
    "download-dir-free-space": 390560174080,
    "download-queue-enabled": True,
    "download-queue-size": 5,
    "downloadSpeed": 0,
    "uploadSpeed": 0,
    "activeTorrentCount": 0,
    "encryption": "preferred",
    "idle-seeding-limit": 30,
    "idle-seeding-limit-enabled": False,
    "incomplete-dir": "/share/incomplete",
    "incomplete-dir-enabled": True,
    "lpd-enabled": False,
    "peer-limit-global": 200,
    "peer-limit-per-torrent": 50,
    "peer-port": 51413,
    "peer-port-random-on-start": False,
    "pex-enabled": True,
    "port-forwarding-enabled": True,
    "queue-stalled-enabled": True,
    "queue-stalled-minutes": 30,
    "rename-partial-files": True,
    "rpc-version": 16,
    "rpc-version-minimum": 1,
    "script-torrent-done-enabled": False,
    "script-torrent-done-filename": "",
    "seed-queue-enabled": False,
    "seed-queue-size": 10,
    "seedRatioLimit": 2,
    "seedRatioLimited": False,
    "session-id": "M9Ms7QbxOP81GkRr243LssRz9YDQ71tGqFZDIpDZxio4atE3",
    "speed-limit-down": 100,
    "speed-limit-down-enabled": False,
    "speed-limit-up": 100,
    "speed-limit-up-enabled": False,
    "start-added-torrents": True,
    "trash-original-torrent-files": False,
    "units": {
        "memory-bytes": 1024,
        "memory-units": ["KiB", "MiB", "GiB", "TiB"],
        "size-bytes": 1000,
        "size-units": ["kB", "MB", "GB", "TB"],
        "speed-bytes": 1000,
        "speed-units": ["kB/s", "MB/s", "GB/s", "TB/s"],
    },
    "utp-enabled": True,
    "version": "3.00 (bb6b5a062e)",
}
