config_entry:
  versions:
    - version:
        major: 1
        minor: 1
      data:
        fields:
          cloudhook:
            required: true
            selector:
              text: {}
          secret:
            required: true
            selector:
              text: {}
      options:
        fields: {}
  subentries: {}
