"""Constants for the Volvo integration."""

from homeassistant.const import Platform

DOMAIN = "volvo"
PLATFORMS: list[Platform] = [Platform.BINARY_SENSOR, Platform.SENSOR]

API_NONE_VALUE = "UNSPECIFIED"
API_OIL_LEVEL_WARNING_VALUES = ("SERVICE_REQUIRED", "TOO_LOW", "TOO_HIGH")
API_SERVICE_WARNING_VALUES = (
    "DISTANCE_DRIVEN_ALMOST_TIME_FOR_SERVICE",
    "DISTANCE_DRIVEN_OVERDUE_FOR_SERVICE",
    "DISTANCE_DRIVEN_TIME_FOR_SERVICE",
    "ENGINE_HOURS_ALMOST_TIME_FOR_SERVICE",
    "ENGINE_HOURS_OVERDUE_FOR_SERVICE",
    "ENGINE_HOURS_TIME_FOR_SERVICE",
    "REGULAR_MAINTENANCE_ALMOST_TIME_FOR_SERVICE",
    "REGULAR_MAINTENANCE_OVERDUE_FOR_SERVICE",
    "REGULAR_MAINTENANCE_TIME_FOR_SERVICE",
    "UNKNOWN_WARNING",
)
API_TIRE_WARNING_VALUES = ("VERY_LOW_PRESSURE", "LOW_PRESSURE", "HIGH_PRESSURE")
API_WINDOW_WARNING_VALUES = ("OPEN", "AJAR")
API_DOOR_WARNING_VALUES = ("OPEN", "AJAR")

CONF_VIN = "vin"
DATA_BATTERY_CAPACITY = "battery_capacity_kwh"
MANUFACTURER = "Volvo"
