"""Diagnostics support for Sunricher DALI."""

from __future__ import annotations

from typing import Any

from PySrDaliGateway import Device, Scene
from PySrDaliGateway.types import SceneDeviceType

from homeassistant.components.diagnostics import REDACTED, async_redact_data
from homeassistant.const import (
    CONF_HOST,
    CONF_NAME,
    CONF_PASSWORD,
    CONF_PORT,
    CONF_USERNAME,
)
from homeassistant.core import HomeAssistant

from .const import CONF_SERIAL_NUMBER
from .types import DaliCenterConfigEntry

TO_REDACT = {
    CONF_HOST,
    CONF_USERNAME,
    CONF_PASSWORD,
    CONF_SERIAL_NUMBER,
    "dev_sn",
}

ALLOWED_ENTRY_KEYS = frozenset(
    {
        CONF_HOST,
        CONF_PORT,
        CONF_NAME,
        CONF_USERNAME,
        CONF_PASSWORD,
        CONF_SERIAL_NUMBER,
    }
)


def _serialize_entry_data(entry: DaliCenterConfigEntry) -> dict[str, Any]:
    """Serialize config entry data using an explicit key whitelist.

    Only keys listed in ``ALLOWED_ENTRY_KEYS`` are exported; any other
    keys added to ``entry.data`` in the future must be explicitly opted
    in here after a PII/secrets review.
    """
    return {key: entry.data[key] for key in ALLOWED_ENTRY_KEYS if key in entry.data}


def _serialize_device(device: Device) -> dict[str, Any]:
    """Serialize a Device using an explicit field whitelist.

    The whitelist is enforced by EXPECTED_DEVICE_KEYS in test_diagnostics.py.
    Any change here must be mirrored there.
    """
    return {
        "dev_id": device.dev_id,
        "unique_id": device.unique_id,
        "name": device.name,
        "dev_type": device.dev_type,
        "channel": device.channel,
        "address": device.address,
        "status": device.status,
        "dev_sn": device.dev_sn,
        "area_name": device.area_name,
        "area_id": device.area_id,
        "model": device.model,
    }


def _serialize_scene(scene: Scene) -> dict[str, Any]:
    """Serialize a Scene using an explicit field whitelist.

    Only the unique_id of each member device is exported, intentionally
    skipping gw_sn_obj and property fields from SceneDeviceType to avoid
    leaking gw_sn aliases or runtime light state.
    """
    members: list[SceneDeviceType] = scene.devices
    return {
        "scene_id": scene.scene_id,
        "name": scene.name,
        "channel": scene.channel,
        "area_id": scene.area_id,
        "unique_id": scene.unique_id,
        "device_unique_ids": [member["unique_id"] for member in members],
    }


def _strip_gw_sn(data: Any, gw_sn: str) -> Any:
    """Recursively replace the gateway serial number in any string value.

    Device and scene identifiers generated by PySrDaliGateway embed
    ``gw_sn`` as a suffix (e.g., ``0101000102ABC123``). Since
    ``async_redact_data`` only matches on dict keys, such identifiers
    would otherwise leak the serial even when ``serial_number`` itself
    is redacted. This function walks the already-redacted payload and
    masks every occurrence of ``gw_sn`` inside string values, so no
    representation of the serial remains in the output.
    """
    if not gw_sn:
        return data
    if isinstance(data, dict):
        return {key: _strip_gw_sn(value, gw_sn) for key, value in data.items()}
    if isinstance(data, list):
        return [_strip_gw_sn(item, gw_sn) for item in data]
    if isinstance(data, str):
        return data.replace(gw_sn, REDACTED)
    return data


async def async_get_config_entry_diagnostics(
    hass: HomeAssistant, entry: DaliCenterConfigEntry
) -> dict[str, Any]:
    """Return diagnostics for a config entry."""
    data = entry.runtime_data
    payload = {
        "entry_data": _serialize_entry_data(entry),
        "devices": [_serialize_device(device) for device in data.devices],
        "scenes": [_serialize_scene(scene) for scene in data.scenes],
    }
    return _strip_gw_sn(async_redact_data(payload, TO_REDACT), data.gateway.gw_sn)
