"""Constants for the rpi_gpio_pwm integration."""

from homeassistant.components.light import (
    SUPPORT_BRIGHTNESS,
    SUPPORT_COLOR,
    SUPPORT_TRANSITION,
)

DOMAIN = "rpi_gpio_pwm"

CONF_LEDS = "leds"
CONF_NUMBERS = "numbers"
CONF_DRIVER = "driver"
CONF_PINS = "pins"
CONF_PIN = "pin"
CONF_FREQUENCY = "frequency"
CONF_INVERT = "invert"
CONF_STEP = "step"

CONF_DRIVER_GPIO = "gpio"
CONF_DRIVER_PCA9685 = "pca9685"
CONF_DRIVER_TYPES = [CONF_DRIVER_GPIO, CONF_DRIVER_PCA9685]

CONF_LED_TYPE_SIMPLE = "simple"
CONF_LED_TYPE_RGB = "rgb"
CONF_LED_TYPE_RGBW = "rgbw"
CONF_LED_TYPES = [CONF_LED_TYPE_SIMPLE, CONF_LED_TYPE_RGB, CONF_LED_TYPE_RGBW]

DEFAULT_BRIGHTNESS = 255
DEFAULT_COLOR = [0, 0]

SUPPORT_SIMPLE_LED = SUPPORT_BRIGHTNESS | SUPPORT_TRANSITION
SUPPORT_RGB_LED = SUPPORT_BRIGHTNESS | SUPPORT_COLOR | SUPPORT_TRANSITION

MODE_SLIDER = "slider"
MODE_BOX = "box"
MODE_AUTO = "auto"

ATTR_FREQUENCY = "frequency"
ATTR_INVERT = "invert"
