name: Build IOT
on:
  workflow_dispatch:
jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        pip install build twine
        
    - name: Build package
      run: |
        python -m build
        
    - name: Publish to GitHub Packages
      run: |
        python -m twine upload --repository github dist/* --verbose
      env:
        TWINE_USERNAME: ${{ github.actor }}
        TWINE_PASSWORD: ${{ secrets.GHUB_TOKEN }}
        TWINE_REPOSITORY_URL: https://github.com/${{ github.repository_owner }}/${{ github.event.repository.name }}/packages
