name: Build HA
on:
  workflow_dispatch:  # 手动触发
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4  # 更新到 v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        pip install build twine
        
    - name: Build package
      run: |
        python -m build
        
    - name: Upload artifacts
      uses: actions/upload-artifact@v4  # 更新到 v4
      with:
        name: ha-package
        path: dist/
