name: Build images

# yamllint disable-line rule:truthy
on:
  workflow_dispatch:
    inputs:
      from_base_image:
        required: true
      version:
        required: true
      publish:
        type: boolean
        required: true

env:
  BUILD_TYPE: core
  DEFAULT_PYTHON: "3.13"
  PIP_TIMEOUT: 60
  UV_HTTP_TIMEOUT: 60
  UV_SYSTEM_PYTHON: "true"

jobs:
  build_base:
    name: Build & publish armv7 base core image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
      
    steps:
      - name: Checkout the repository version ${{ github.event.inputs.version }}
        uses: actions/checkout@v5.0.0
        with:
          ref: ${{ github.event.inputs.version }}

      # TODO: handle translations

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3.5.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Patch build.yaml
        run: |
          rm build.yaml
          cat << EOF > file.txt
          image: ghcr.io/${{ github.repository_owner }}/armv7-homeassistant
          build_from:
            armv7:${{ github.event.inputs.from_base_image }}
          EOF
          
      - name: Build base image
        uses: home-assistant/builder@2025.03.0
        with:
          args: |
            --docker-hub "ghcr.io/${{ github.repository_owner }}" \
            --armv7 \
            --target /data \
            --generic ${{ github.event.inputs.version }}
