name: Pre-checks

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - dev
      - master
      - rc
  pull_request: ~
  workflow_dispatch: ~

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  prek:
    name: Run pre-checks
    runs-on: ubuntu-latest
    permissions:
      contents: read # To check out the repository
    steps:
      - name: Checkout the repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Set up Python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version-file: ".python-version"

      - name: Cache prek environments
        uses: actions/cache@668228422ae6a00e4ad889ee87cd7109ec5666a7 # v5.0.4
        with:
          path: ~/.cache/prek
          key: prek-${{ runner.os }}-${{ hashFiles('.pre-commit-config.yaml') }}
          restore-keys: |
            prek-${{ runner.os }}-

      - name: Install prek
        run: pip install prek==0.3.8

      - name: Install Git shims
        run: prek install

      - name: Run all hooks
        run: prek run --all-files
