config_entry:
  versions:
    - version:
        major: 1
        minor: 1
      data:
        fields:
          repositories:
            required: true
            selector:
              select:
                options: []
                multiple: true
      options:
        fields:
          repositories:
            required: false
            selector:
              text: {}
  subentries: {}
